### ISSUE TITLE
Define "model" as string literal union type

### ISSUE THREAD

**Issue by custardcream98** [openai/openai-node#100]
### Describe the feature or improvement you're requesting

I am currently trying to post multiple requests using both chat completion and text completion at a same time using `Promise.race` like this.

```ts
const { data } = await Promise.race([
    openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content: prompt,
        },
      ],
      temperature: 0.9,
      n: 1,
    }),
    openai.createCompletion({
      model: "text-davinci-003",
      prompt,
      temperature: 0.9,
      n: 1,
      max_tokens: 2000,
    }),
  ]);
```

Both `CreateChatCompletionResponse | CreateCompletionResponse` has same key `model`, but I can't narrow type of response like this.

```ts
if (data.model === "gpt-3.5-turbo") {
  const { message } = data.choices[0]; // error!
}
```

but, if type of `model` is defined as string literal union type like below, it will resolve the error. (so that it can be distinguished using discreminated union)

```ts
type ChatCompletionModel = "gpt-3.5-turbo" | "gpt-3.5-turbo-0301";
interface CreateChatCompletionResponse = {
  model: ChatCompletionModel;
  /* ... */
}

if (data.model === "gpt-3.5-turbo") {
   /* now the type checker knows the type of `data` is `CreateChatCompletionResponse` */
}
```

I know the type of `model` should be `string` because of the fine-tuned models, but if possible, could you please define `model` type? I can resolve this issue by using custom type guards, but I think it would be nice to have more narrow type of `model`.

thank you!

**Comment by kitfit-dave** [comment]
Hi,
You can do this with a couple of type predicates:

```
const isCreateChatCompletionResponse = (data: CreateChatCompletionResponse | CreateCompletionResponse): data is CreateChatCompletionResponse => {
	return data.model === 'gpt-3.5-turbo'
}
const isCreateCompletionResponse = (data: CreateChatCompletionResponse | CreateCompletionResponse): data is CreateCompletionResponse => {
	return data.model === 'text-davinci-003'
}

if (isCreateChatCompletionResponse(data)) {
	const { message } = data.choices[0] // not an error
	/* ... */
} else if (isCreateCompletionResponse(data)) {
	const { message } = data.choices[0] // still (correctly) an error
	/* ... */
}
```

one proviso is that you have to guarantee that if the model is 'gpt-3.5-turbo' then it's definitely a CreateChatCompletionResponse etc. Consider: there could be models that support both createChatCompletion and createCompletion; and there are already other endpoints for the same model, e.g. createEdit which you (or someone else) could add to your race

**Comment by custardcream98** [comment]
@kitfit-dave Thanks for the tip! I Thought it would be great if library gives me this type predicates, but as you said it has some edge cases so... I'll take your advice 😁
