### ISSUE TITLE
Add pagination support for Files list method

### ISSUE THREAD

**Issue by m-zuro** [openai/openai-node#1008]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I have a need to retrieve all files uploaded to OpenAI. Currently `files.list()` returns only first 10.000 files.
Could you add pagination to mentioned endpoint please, similar to one for `assistants.list()`?

**Comment by m-zuro** [comment]
I just realised that this might be limitation in underlying OpenAI API, if so please let me know and I will file a feature request in OpenAI Dev community

**Comment by RobertCraigie** [comment]
AFAIK the underlying API does not support pagination for the list files endpoint, please file a feature request in the dev community.
