### ISSUE TITLE
OpenAI in browser

### ISSUE THREAD

**Issue by hpssjellis** [openai/openai-node#102]
### Describe the feature or improvement you're requesting

I have been using huggingFaceJS and inputting my token through a input text field. Can the same tecnique be used with openAI Javascript, and if anyone has done it can you send me a link or an example to load a basic object detection code.

**Comment by martin12333** [comment]
related:

https://observablehq.com/@trebor/gpt-3-tools-example

> Define an [Observable secret](https://observablehq.com/@observablehq/secrets) called open-ai-api-key with that API key.

**Comment by martin12333** [comment]
seems possible?

```
site:stackblitz.com openai
```

**Comment by sandaru1** [comment]
I wanted to develop a Chrome Extension with OpenAI API and facing the same issue.

I forked the repository and made it browser compatible : https://github.com/sandaru1/openai-web

**Comment by rattrayalex** [comment]
Browser support has been added in our [upcoming v4](https://github.com/openai/openai-node/discussions/182)! Give it a try with `npm install openai@v4.0.0-beta.4` and please report back.

Note that we expect to require a config option like `dangerouslyAllowAPIKeyInBrowser: true` for this use-case in the near future.
