### ISSUE TITLE
Avoid redundant memory copies during file uploads

### ISSUE THREAD

**Issue by isac322** [openai/openai-node#1034]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

`files.create` convert the value of `file` using `toFile` whenever it is `Uploadable`. The problem is that even if it has already been converted to a File, such as `client.files.create({ file: await OpenAI.toFile(someStream, "filename", purpose: "assistants" })`, `toFile` is executed one more time, and by calling `arrayBuffer()` on https://github.com/openai/openai-node/blob/5e29cb2f2825d5abcdb536d843dcafe4ee980698/src/uploads.ts#L148, memory copying occurs one more time.

### To Reproduce

```typescript
const fs = require("node:fs")

const client = new OpenAI()
const stream = fs.createReadStream("some-file")
const file = await OpenAI.toFile(stream, "new_file_name")          // toFile create buffer and copy from stream
await client.files.create({ file, purpose: "assistants" })  // internally call `toFile` again and it create a new buffer
```

### OS

Linux

### Node version

Node v18.20.4

### Library version

openai v4.56.0

**Comment by RobertCraigie** [comment]
This is fixed in v4.58.0!
