### ISSUE TITLE
Limit For The Embeddings Return

### ISSUE THREAD

**Issue by NadirSahllal** [openai/openai-node#104]
### Describe the feature or improvement you're requesting

When using the current API to get the embeddings for text it seems to return an arrays of over 1500 embeddings and no matter How long I tried to search there seems to be no parameter to limit the number of embeddings gotten

**Comment by ryancasburn-KAI** [comment]
An embedding is a vector with a certain dimension. In the OpenAI text embedding model, that dimension is 1536. So the array you are receiving is a single embedding vector.
