### ISSUE TITLE
Add streaming support for Audio

### ISSUE THREAD

**Issue by NinoSkopac** [openai/openai-node#1048]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Currently, it's easy to stream in Python as per docs, but I haven't been able to pull it off in Node. Concurrency works just great, tho.

we need a `response.stream_to_file("output.mp3")`

**Comment by RobertCraigie** [comment]
> we need a response.stream_to_file("output.mp3")

Unfortunately it's unlikely that we can add something like that as JS doesn't always have file system access or a runtime independent way of writing files.

> Currently, it's easy to stream in Python as per docs, but I haven't been able to pull it off in Node.

I'm curious what you've tried so far in case there's any docs we could update?

We do have an example script [here](https://github.com/openai/openai-node/blob/master/examples/audio.ts) that shows how to stream the response to a file.

**Comment by RobertCraigie** [comment]
I'm going to close this due to the above mentioned reasons, please let us know if there are any docs we could improve here!
