### ISSUE TITLE
Structured Outputs: JSON Schema 'nullable' modifier ignored

### ISSUE THREAD

**Issue by lirbank** [openai/openai-node#1049]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

In Zod one can make a field nullable in two ways, with A) a union (eg. `authorName1` below) or using B) the .nullable() method (eg. `authorName2` below).

A: `z.union([z.string(), z.null()]`
B: `z.string().nullable()`

The final JSON schema will also be different:

A: `{ "type": ["string", "null"] }`
B: `{ "type": "string", "nullable": true }`

When using the later, B, the LLM (gpt-4o-2024-08-06) always return a string and never null. The former, A, works well.

I would imagine B is quite a bit more common in Zod schemas so it would make sense to support it. I see many ways to fix this, including just clarifying that "nullable" has no effect in the docs.

### To Reproduce

Consider this Zod schema, `authorName1` and `authorName2` are both nullable strings using two different syntaxes.

```ts
const SomeSchema = z.object({
  authorName1: z.union([z.string(), z.null()], {
    description: [
      `The name of the author of the provided document.`,
      `This field is is null if the author name does not exist in the input data.`,
    ].join(" "),
  }),
  authorName2: z
    .string({
      description: [
        `The name of the author of the provided document.`,
        `This field is is null if the author name does not exist in the input data.`,
      ].join(" "),
    })
    .nullable(),
});
```

Passing it through `zodResponseFormat`:

```ts
const responseFormat = zodResponseFormat(SomeSchema, "documentData");
console.log(JSON.stringify(responseFormat, null, 2));
```

Output:

```json
{
  "type": "json_schema",
  "json_schema": {
    "name": "documentData",
    "strict": true,
    "schema": {
      "type": "object",
      "properties": {
        "authorName1": {
          "type": [
            "string",
            "null"
          ],
          "description": "The name of the author of the provided document. This field is is null if the author name does not exist in the input data."
        },
        "authorName2": {
          "type": "string",
          "nullable": true,
          "description": "The name of the author of the provided document. This field is is null if the author name does not exist in the input data."
        }
      },
      "required": [
        "authorName1",
        "authorName2"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
}
```

As you can see in the generated output, responseFormat also use two different syntaxes to make the two fields nullable. The model (gpt-4o-2024-08-06) seem to ignore the later `"nullable": true`.

```ts
await openai.beta.chat.completions.parse({
  top_p: 1,
  model: "gpt-4o-2024-08-06",
  n: 1,
  temperature: 0,
  response_format: zodResponseFormat(SomeSchema, "documentData"),
  messages,
});
```

### OS

macOS and Linux

### Node version

Node 20

### Library version

openai 4.58.1

**Comment by RobertCraigie** [comment]
Thanks for reporting! We're investigating

**Comment by RobertCraigie** [comment]
@lirbank the API has been updated to support `nullable`, please try it again!

**Comment by lirbank** [comment]
Nice @RobertCraigie, thanks a lot! 🙏

https://x.com/MikaelLirbank/status/1837104862489637044

**Comment by dquang-tran** [comment]
```
z.object({
  foo: z.string().nullable(),
  bar: z
    .array(
      z.object({
        baz: z.number().nullable(),
      }),
    )
    .nullable(),
});
```

As far as I've tested, doesn't work for cases when it's nested. Baz here will always be populated

**Comment by lirbank** [comment]
@dquang-tran you should probably open a new issue and make a reference to this issue. Since this issue is closed as completed the team may not find your note.

**Comment by TheBestMoshe** [comment]
> As far as I've tested, doesn't work for cases when it's nested. Baz here will always be populated

I've observed this issue as well. My solution was to tell it to set to 0 if null. This worked for my use case. If I didn't give it this option, it just hallucinated values.

Is there another issue where this is being tracked?

**Comment by lirbank** [comment]
Hi @TheBestMoshe, search the issues and if not plz create a new issue. Would be cool if you link to this issue in your new issue so people ending up here see the reference.
