### ISSUE TITLE
Missing Authorization header in requests

### ISSUE THREAD

**Issue by y-nk** [openai/openai-node#105]
### Describe the bug

When running `createCompletion`, the error printed mentions that the request sent to openai does not have the Authorization header, even though i passed the apiKey to the client.

```
data: {
      error: {
        message: "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        type: 'invalid_request_error',
        param: null,
        code: null
      }
    }
```

### To Reproduce

1. Run the code below with your own API key
2. See the error

### Code snippets

```JavaScript
import { OpenAIApi } from "openai";

const client = new OpenAIApi({ apiKey: 'the_api_key_just_generated' })

await client.createCompletion({
  prompt: 'what is yellow and is waiting',
  max_tokens: 10,
})
```
```


### OS

macOS

### Node version

18

### Library version

3.2.1

**Comment by Runtus** [comment]
The OpenAIApi class accepts a Configuration object, and your apiKey should  be placed in the Configuration class (which  import from openai).
### Example
```ts
import { Configuration, OpenAIApi } from 'openai'

const configuration = new Configuration({
    apiKey: your_api_key,
  });

const openai = new OpenAIApi(configuration);
```
You can learn more about the detailed usage from the [OpenAI documentation](https://platform.openai.com/docs/libraries).

**Comment by y-nk** [comment]
i understand, thank you for your answer.

as for curiosity and DX appeal, is there a reason why the configuration is a class and not a plain object with types?

**Comment by RobertCraigie** [comment]
This has been changed in our upcoming [v4.0.0 release](https://github.com/openai/openai-node/discussions/182) to use a plain object.
