### ISSUE TITLE
Support withResponse() for Parse Completion

### ISSUE THREAD

**Issue by margostino** [openai/openai-node#1057]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Currently for chat completion we can use `withResponse()` to get the parsed response data and the raw `Response` instance. In my case to extract `headers`.

This feature request is to support the same when Parse Completion is used.

I created [this PR](https://github.com/openai/openai-node/pull/1056) to reflect the intention of it.

**Comment by RobertCraigie** [comment]
This will be fixed in the next release! `v4.59.0` https://github.com/openai/openai-node/pull/1059
