### ISSUE TITLE
Issue with using 'stream' option in TypeScript with CreateChatCompletionResponse

### ISSUE THREAD

**Issue by amlxv** [openai/openai-node#107]
### Describe the bug

I have been exploring how to use the 'stream' option in TypeScript for discussion #18. While trying to implement it, I found that the CreateChatCompletionResponse does not have a property 'on', which is required to stream the data.

To overcome this issue, I converted the CreateChatCompletionResponse to Readable type, and it worked perfectly. However, I believe this is a problem that needs to be addressed as it is not intuitive for TypeScript users.

### To Reproduce

1. Use the createChatCompletion method to create a chat completion.
2. Add the 'stream' property and set it to 'true' to enable streaming.
3. Add the 'responseType' property to the axios config object and set it to 'stream' to specify the data format.
4. Try to access the 'on' property in the response data, which is not available in TypeScript.

### Code snippets

```JavaScript
const completion = await openai.createChatCompletion(
  {
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'user',
        content: 'Hello, how are you?',
      },
    ],
    stream: true,
  },
  { responseType: 'stream' }
);

completion.data.on('data', (data: Buffer) => {
  console.log(data.toString());
});
```

### OS

Windows 11 22621.1413

### Node version

Node v18.8.0

### Library version

openai v3.2.1

**Comment by SunghyunKwon** [comment]
I was able to modify the issue by inheriting the **CreateChatCompletionResponse** Interface through a **Readable**.

`import { Readable } from 'stream'  `
`export interface CreateChatCompletionResponse ->  `
`export interface CreateChatCompletionResponse extends Readable`

**OS** 
macOS 
**Node Version**
Node v19.4.0
**Library Version**
openai v3.2.1

**Comment by lukelu520** [comment]
Same problem, hope to hear your expertise.

**Comment by zamoshchin** [comment]
Same problem

**Comment by dev-bre** [comment]
is there any update on this subject? 
can you clarify your solution: "I converted the CreateChatCompletionResponse to Readable type"?

**Comment by SunghyunKwon** [comment]
In api.ts file,  the CreateChatCompletionResponse interface has been defined.
The interface has not data member.
So I solved the problem as follows.

Original Source
`
/**
 *
 * @export
 * @interface CreateChatCompletionResponse
 */
export interface CreateChatCompletionResponse {
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'id': string;
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'object': string;
    /**
     *
     * @type {number}
     * @memberof CreateChatCompletionResponse
     */
    'created': number;
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'model': string;
    /**
     *
     * @type {Array<CreateChatCompletionResponseChoicesInner>}
     * @memberof CreateChatCompletionResponse
     */
    'choices': Array<CreateChatCompletionResponseChoicesInner>;
    /**
     *
     * @type {CreateCompletionResponseUsage}
     * @memberof CreateChatCompletionResponse
     */
    'usage'?: CreateCompletionResponseUsage;
}
`

Resolved
`
/**
 *
 * @export
 * @interface CreateChatCompletionResponse
 */
import { Readable } from 'stream' 
export interface CreateChatCompletionResponse **extends Readable** {
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'id': string;
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'object': string;
    /**
     *
     * @type {number}
     * @memberof CreateChatCompletionResponse
     */
    'created': number;
    /**
     *
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    'model': string;
    /**
     *
     * @type {Array<CreateChatCompletionResponseChoicesInner>}
     * @memberof CreateChatCompletionResponse
     */
    'choices': Array<CreateChatCompletionResponseChoicesInner>;
    /**
     *
     * @type {CreateCompletionResponseUsage}
     * @memberof CreateChatCompletionResponse
     */
    'usage'?: CreateCompletionResponseUsage;
}
`

**Comment by hiroshinishio** [comment]
This is my workaround untill update.

```
// Throw an early error if the response is not a stream
if (!("on" in response.data)) throw new Error("No data received from OpenAI");
if (!(response.data instanceof Readable)) throw new Error("response data does not have Readable.on stream method");

response.data.on("data", (chunk: Buffer) => {....

```

**Comment by rattrayalex** [comment]
Hi, we have an [upcoming version v4.0.0](https://github.com/openai/openai-node/discussions/182) that has rewritten our streaming support; please give it a try and let us know in the thread whether it suits your needs!
