### ISSUE TITLE
Unknown request URL: GET /v1/fine-tunes

### ISSUE THREAD

**Issue by kjaerb** [openai/openai-node#1077]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm seeing an issue, where the openai object has a function that returns an error. Either the endpoint needs to be changed or the function should not exist at all. 

I want to be able to list the finetunes I've created on my account. This is not possible as the current `listFineTunes()` function returns an error object. I can however list all of the models using the `listModels()` function. 

### To Reproduce

1. Create an openai object with the node SDK:
```javascript
const config = new Configuration({
  apiKey: OPEN_API_KEY,
});

const openai = new OpenAIApi(config);
```

2. Try to call the function on the openai object:
```javascript
openai.listFineTunes()
```

### OS

Windows 11

### Node version

Node v20.0.9

### Library version

openai v4.61.0

**Comment by RobertCraigie** [comment]
Hey @kjaerb, it looks like you're using v3 of this library which is no longer supported.

Here's a guide on using the latest SDK version with fine tuning: https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset.

**Comment by kjaerb** [comment]
Hi @RobertCraigie.

My mistake. After looking over the dependencies, we've been working with the 'openai-edge' package and not the official openai SDK. Sorry for the waste of time and can confirm it's working properly again.

**Comment by RobertCraigie** [comment]
No worries! Any particular reason you're still using `openai-edge`? v4 of this SDK should work in edge environments.

**Comment by kjaerb** [comment]
The project is about a year old and we're first getting to maintaining and adding new features now. We'll be switching and going away from the `openai-edge` package now.
