### ISSUE TITLE
[Whisper] Support OGG file extension

### ISSUE THREAD

**Issue by idoyana** [openai/openai-node#109]
### Describe the feature or improvement you're requesting

Dear OpenAI Team,

I am writing to request the addition of OGG file format support in the Whisper model. As you know, OGG is a popular open-source multimedia container format that is widely used for streaming, storing, and transmitting digital multimedia content such as audio and video.

Currently, the Whisper model supports only a limited number of audio file formats, such as WAV and MP3. However, many users, including myself, prefer to use OGG format due to its superior compression, quality, and open-source nature.

Therefore, I would like to request that the OpenAI team considers adding OGG file format support to the Whisper model. This would allow users to process and generate high-quality audio content in OGG format, which is important for many applications such as music production, podcasting, and voiceover work.

I believe that adding support for OGG file format in the Whisper model would be a valuable addition to the platform, and would help to expand the range of options available to users. Thank you for your consideration, and I look forward to hearing your response.

Sincerely,
Ido

### Additional context
Specifically `opus codecs`

**Comment by maxpain** [comment]
OGG also is used in Telegram, so it will be easier to integrate Whisper into Telegram Bots.

**Comment by Stvad** [comment]
It's also used for Matrix chat audio messages, came here in hope of being able to transcribe those

**Comment by Pachocastillosr** [comment]
Any workarounds that you can recommend in the meantime? Maybe an API audio converter?

**Comment by ChristianWeyer** [comment]
Is there already an opinion on whether to support this @rattrayalex? This would be super useful (also for WhatsApp integration).
Thanks!

**Comment by rattrayalex** [comment]
I don't have an opinion I can share on this, but it might be helpful to share why this would be useful for a WhatsApp integration.

**Comment by GeyseR** [comment]
OGG and FLAC files are already supported in Whisper API https://github.com/openai/whisper/discussions/799#discussioncomment-6432285

**Comment by rattrayalex** [comment]
Great! @GeyseR or @ChristianWeyer can you confirm that uploading the OGG and FLAC files you have works as expected with this SDK?

I've proposed a change to the OpenAPI spec accordingly here: https://github.com/openai/openai-openapi/pull/64

**Comment by maxpain** [comment]
@rattrayalex Yes, it's working!

```typescript
const file = await ctx.getFile()
const stream = got.stream(
	`https://api.telegram.org/file/bot${process.env.BOT_TOKEN}/${file.file_path}`,
) as unknown as ReadStream

stream.path = 'voice.ogg'

const { data } = await client.createTranscription(
	stream as any,
	'whisper-1',
)
```

**Comment by rattrayalex** [comment]
Great! That'd look a bit different in the upcoming v4 of this library FWIW, but I'm sure it'd work just as well. I'll close this out! 🎉

**Comment by yleflour** [comment]
In case anyone ends up on this page, the new API can be used in the following way with ReadableStreams (either node or browser ones):

```ts
import { OpenAI, toFile } from 'openai';

const res = await client.audio.transcriptions.create({
  file: await toFile(audioStream, 'voice.ogg'),
  model: 'whisper-1',
  prompt: 'Hello, welcome to my lecture.',
});
```

With axios:
```ts
const res = await axios.get(whatsappFile.url, {
  headers: {
    Authorization: `Bearer ${process.env.WHATSAPP_API_TOKEN}`,
  },
  responseType: 'stream',
});

const audioStream = res.data;
```

With wretch:
```ts
const res = await wretch(whatsappFile.url)
   .auth('Bearer ' + process.env.WHATSAPP_API_TOKEN)
   .get()
   .res();

const audioStream = res.body;
```
