### ISSUE TITLE
Timeout on extremely simple query

### ISSUE THREAD

**Issue by davidwitten** [openai/openai-node#110]
### Describe the bug

I've run into a set of issues with the latency of OpenAI's API.

Specifically, every once in a while a request takes an **extremely** long time. For example, the request below took 145 seconds.

One potential cause is I did this query three times in a row. Maybe I was throttled?

### To Reproduce

Run the same request three times in a row, the third or fourth time, it will take an extremely long time (> 50 seconds)

### Code snippets

```JavaScript
I initially tried: 

const response = await openai.createChatCompletion({
        model: 'gpt-3.5-turbo',
        messages: [
            { "role": "system", "content": 'this is a test'},
        ],
        temperature: 0,
        max_tokens: 200
    });
```

but I also tried the raw HTTP request

```
const response = await axios.post(
    'https://api.openai.com/v1/chat/completions',
    {
        model: 'gpt-3.5-turbo',
        messages: [
            { "role": "system", "content": 'say this is a test' },
            // { "role": "user", "content": user_string },
        ],
        temperature: 0,
        max_tokens: 200
    },
    {
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + process.env['OPEN_AI']
        }
    }
).catch((e) => {console.log(e);});
```

### OS

macOS

### Node version

Node v14.20.0

### Library version

3.2.1

**Comment by Olovorr** [comment]
I noticed the same thing. I can run close to 4000 tokens `createChatCompletion` call, and it would take 11-13 seconds, but every 5th call or so it just takes 200 seconds. It would be great if someone could look into this or have any advice what we might be doing wrong 😇

**Comment by davidwitten** [comment]
I switched from `gpt-3.5-turbo` to `text-davinci-003` and it works perfectly (latency-wise, at least)

```
    const response = await openai.createCompletion(
        {
            model: "text-davinci-003",
            prompt: system_string + "\n" + user_string,
            temperature: 0,
            max_tokens: 200,
        });
```
