### ISSUE TITLE
Improve error for incorrect model name

### ISSUE THREAD

**Issue by mattorp** [openai/openai-node#111]
### Describe the bug

If using an incorrect model name, e.g. gpt-3-turbo instead of gpt-3.5-turbo, it returns 404. Would it be possible to catch these routes to return a response with "unsupported model name requested". And/or use the model names instead of string for the typescript definition instead of string to catch this?

### To Reproduce

```js
openai.createChatCompletion({
        model: 'gpt-3-turbo',
        messages,
})
```

### OS

macOS

### Node version

v18.12.1

### Library version

v3.2.1

**Comment by rattrayalex** [comment]
Our upcoming v4 includes better error message delivery: https://github.com/openai/openai-node/discussions/182
