### ISSUE TITLE
Add edge folder

### ISSUE THREAD

**Issue by stephenasuncionDEV** [openai/openai-node#112]
### Describe the feature or improvement you're requesting

Instead of having other libraries like `https://github.com/dan-kwiat/openai-edge` , OpenAI's node library should support edge out of the box. like so: `import { Configuration, OpenAIApi } from "openai/edge";`

**Comment by rattrayalex** [comment]
Support for edge has been added in our [upcoming v4](https://github.com/openai/openai-node/discussions/182)! Please give it a try.
