### ISSUE TITLE
Can't use v1 assistants with the nodejs sdk anymore

### ISSUE THREAD

**Issue by ziyaaktas** [openai/openai-node#1123]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I am using the nodejs SDK 4.36.0, and when I try to create an assistant with an uploaded file it gives me an error like "vector store with id 'asst_*' not found."

### To Reproduce

```
const openai = new OpenAI({
    defaultHeaders: { 'OpenAI-Beta': 'assistants=v1' },
  });
const assistant = await openai.beta.assistants.create({
    instructions:
      '...',
    model: 'gpt-4-turbo',
    tools: [
      {
        type: 'retrieval',
      },
    ],
    file_ids: [fileID],
  });
```

### Code snippets

```JavaScript
const openai = new OpenAI({
    defaultHeaders: { 'OpenAI-Beta': 'assistants=v1' },
  });
const assistant = await openai.beta.assistants.create({
    instructions:
      '...',
    model: 'gpt-4-turbo',
    tools: [
      {
        type: 'retrieval',
      },
    ],
    file_ids: [fileID],
  });
```
```


### OS

macOS

### Node version

Node v18-20

### Library version

openai 4.36.0

**Comment by RobertCraigie** [comment]
Hey @ziyaaktas, sorry for the delayed response. Did you manage to figure this out?

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com) if you still need help?
