### ISSUE TITLE
Setting `x-stainless-retry-count` to null in defaultHeaders gets ignored

### ISSUE THREAD

**Issue by spaceemotion** [openai/openai-node#1124]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The recent addition of the `x-stainless-retry-count` header (https://github.com/openai/openai-node/commit/33e5e9b88f2cdb2ae90e355b394cb8c79f5e22a8) uses the local `headers` object, which does not include the default headers:

https://github.com/openai/openai-node/blob/785ef4b579637d3a6a205c0a9c51aa71987bf30e/src/core.ts#L391

### To Reproduce

1. Create a new OpenAI instance
2. Set the defaultHeaders to include `'x-stainless-retry-count': null`
3. See the header being included nonetheless

### OS

Windows

### Node version

Node v20

### Library version

openai 4.67.1

**Comment by RobertCraigie** [comment]
Thanks for the report, this should be fixed in `v4.68.1`!
