### ISSUE TITLE
chatgpt-3.5-turbo automatically changes to chatgpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by yongyi520** [openai/openai-node#113]
### Describe the bug

I was simply calling the "chatgpt-3.5-turbo" model for chatCompletion

**Error:** 

I noticed the model returned from response was chatgpt-3.5-turbo-0301. Is this normal?

**Here's the code snippet that I used to call**
<img width="564" alt="Screen Shot 2023-03-23 at 15 37 40" src="https://user-images.githubusercontent.com/10789851/227147832-9f4506a3-980c-4cf9-bf32-c436223336b0.png">

**Here's the response**
<img width="631" alt="Screen Shot 2023-03-23 at 15 33 33" src="https://user-images.githubusercontent.com/10789851/227147532-482f3406-60d8-4366-9169-2d9ec46f292a.png">

### To Reproduce

1. Call chatCompletionAPI
`const completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: messages,
    });`

    
2. Check response

`const data = completion?.data

    if(data && data.choices) {
      console.log('data', data)
      const choices = data.choices
      console.log('choices', choices)
    } else {
      console.log('no data? completion', completion)
    }`

### OS

macOS

### Node version

node v16.15.1

### Library version

"openai": "^3.2.1",

**Comment by medv** [comment]
`gpt-3.5-turbo` becomes `gpt-3.5-turbo-0301` 
`gpt-4` becomes `gpt-4-0314`

This is also reflected in the billing statements.
It's a great idea to lock to a snapshot version for production environments, but being unable to pick anything other than the snapshot is confusing and is not documented.

**Comment by SFantasy** [comment]
Is there any progress on this issue ?

**Comment by SFantasy** [comment]
> Is there any progress on this issue ?

Update: I found it is not an issue with openai-node, using https://platform.openai.com/docs/api-reference/chat also causes this problem.

**Comment by zaarheed** [comment]
This is expected behaviour as described in the model docs here: https://platform.openai.com/docs/models/gpt-3-5

‘gpt-3.5-turbo’ will be updated with the latest model iteration. In production you should lock it down to a snapshot by specifying the iteration number, eg. ‘gpt-3.5-turbo-0301’

**Comment by OctaM** [comment]
I don't really understand. Currently there-s only gpt-3.5-turbo-0301 and gpt-3.5-turbo. Is this the same version? Are there any more versions in between?

**Comment by medv** [comment]
There is just a misunderstanding of the wording in the documentation. It's not super clear to all readers that the `latest` version does not get continuously updated outside of the provided pinned versions (like a git master branch would), and is instead a simple alias to the latest version number.
