### ISSUE TITLE
RealTime API to generate TTS with ChatContext

### ISSUE THREAD

**Issue by JpEncausse** [openai/openai-node#1130]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

To my understanding, 
- The TTS model generate Text2Speech without context using OAI voices. And can't change voice style
- The RealtimeAPI can change voice style (like a Drunk Pirate) but requires a RealTime client ?

I'm looking for a very simple way (with Azure)
1. to send a ChatMessage (with context, etc ...)
2. and receive the text + audio on realtime model

This would open the path to many simple usecase to get audio aside the text but with all the amazing voice effects.

### Additional context

I'm working with Azure Model and API keys not directly OpenAI. My starting point is [this part of the documentation](https://github.com/openai/openai-node?tab=readme-ov-file#microsoft-azure-openai).

I tried using "client.audio.speech.create()" with realtime model but get the error:
`Error: 400 The audio operation does not work with the specified model, gpt-4o-realtime-preview. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.`

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
