### ISSUE TITLE
When accessing the createChatCompletion API method using a proxy,the status shows as 403

### ISSUE THREAD

**Issue by yenava** [openai/openai-node#116]
### Describe the bug

when i run this code
```
(async () => {
    
    const { Configuration, OpenAIApi } = require("openai");
    const configuration = new Configuration({
      apiKey: 'openai_api_key',
    });
    
    const openai = new OpenAIApi(configuration);

    const response = await openai.createCompletion({
      model: "gpt-3.5-turbo",
      prompt: "Say this is a test",
      messages: [{role: 'user', content: '翻译：大海'}],
      max_tokens: 100,
      temperature: 0,
    });
    console.log(response);
  })();
```

and error:
```
data: {
      error: {
        message: 'The OpenAI API can only be accessed over HTTPS. You should access https://api.openai.com rather than the current URL.',
        type: 'invalid_request_error'
      }
```

but my current URL is "https://api.openai.com/v1/completions"

### To Reproduce

1, (node openai3.2.1) use openai.createChatCompletion method with proxy, connect error, status=403
2, (python openai 0.27.2) use openai.ChatCompletion.create method with same proxy, connect successful, and get correct data.

### OS

macOS

### Node version

Node v19.8.1

### Library version

openai v3.1.2

**Comment by GladosAI** [comment]
这不是我提的那个Reproduce吗/笑，我的问题好像解决了。没看出来你用代理了呀，你可以看看我怎么解决的

**Comment by KeyToLove** [comment]
> 这不是我提的那个Reproduce吗/笑，我的问题好像解决了。没看出来你用代理了呀，你可以看看我怎么解决的[#115 (comment)](https://github.com/openai/openai-node/issues/115#issuecomment-1482327571)

thx, i fixed the proxy problem ahh👍
