### ISSUE TITLE
Publish to JSR

### ISSUE THREAD

**Issue by lishaduck** [openai/openai-node#1164]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the ~~Node~~Deno library

### Describe the feature or improvement you're requesting

I'd prefer to import the Deno library from the Deno-native JSR registry rather than deno.land.

### Additional context

[openai/openai-deno-build](https://github.com/openai/openai-deno-build) says to file issues here.

**Comment by gustawdaniel** [comment]
Probably my question on SO is connected with this issue https://stackoverflow.com/q/79153048/6398044

**Comment by gustawdaniel-statscore** [comment]
I do not understand. There is package: https://jsr.io/@agent/openai

but for https://jsr.io/@openai/openai there is still `versions: 0`

**Comment by lishaduck** [comment]
the `@agent` package is a different package. The offical one is `@openai`, but it's not finished yet.

**Comment by lishaduck** [comment]
Closer! The package works, CD just needs better auth.

**Comment by lishaduck** [comment]
Yay! It's been published!
@kwhinnery-openai, it lists you as the publisher, so thanks!

I don't know how automated this is, so my last request would be to update [the requirements list in the docs](https://jsr.io/@openai/openai#requirements) to note that `jsr:` is supported.
