### ISSUE TITLE
Parameter Limit Exceeded (100) with Structured Output Using zodResponseFormat in OpenAI API

### ISSUE THREAD

**Issue by Xaypanya** [openai/openai-node#1176]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I'm encountering a parameter limit issue when using the OpenAI API with structured output. Specifically, I'm working with a schema that has 144 parameters, which exceeds the 100-parameter limit. I'm using zodResponseFormat from openai/helpers/zod to define my schema.

###  Steps to Reproduce
- Create a schema with more than 100 parameters (in this case, 144) using Zod.
- Attempt to use zodResponseFormat to format the response in OpenAI's structured output.
- Observe the error indicating that the schema exceeds the parameter limit.
### Expected Behavior
The OpenAI API should support schemas with a higher parameter count or provide a clear way to handle larger schemas.
### Observed Behavior
The API returns the following error:

`Error processing AP JSON generation: Error: OpenAI request failed: 400 Invalid schema for response_format 'accounts_payable_invoice': 144 parameters exceed the limit of 100.
`
### Environment
- OpenAI SDK version: 4.71.0
- Node.js version: 18.20.4

### Additional context

I'm building a schema for accounts payable invoices, which naturally requires more than 100 parameters. It would be beneficial if there were either support for higher parameter counts or recommendations on managing schemas of this size within the API constraints.

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by Xaypanya** [comment]
> Thanks for reporting!
> 
> This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue.
> 
> Would you mind reposting at [community.openai.com](https://community.openai.com)?

Thank you for your attention to this matter! It appears that this issue is related to the underlying OpenAI API rather than the SDK itself. I will go ahead and repost this on community.openai.com as suggested.

Thanks again for your support!
