### ISSUE TITLE
Support for new GPT4 models 

### ISSUE THREAD

**Issue by ColumbusK** [openai/openai-node#118]
### Describe the feature or improvement you're requesting

`const configuration = new Configuration({
  apiKey: OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

function createCompletion(questionText) {
  const request = openai
    .createCompletion({
      model: "gpt-3.5-turbo",
      prompt: questionText,
      max_tokens: 1200,
      temperature: 0.7,
    })
  return request.then((response) => {
    return response.data
  })
}`

When I set the model to new model "gpt-3.5-turbo", I got 404

**Comment by ezzcodeezzlife** [comment]
your "gpt-3.5-turbo" request has to look like something like this: 

```
const { Configuration, OpenAIApi } = require("openai");

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

const completion = await openai.createChatCompletion({
  model: "gpt-3.5-turbo",
  messages: [{role: "user", content: "Hello world"}],
});
console.log(completion.data.choices[0].message);
```

https://platform.openai.com/docs/api-reference/chat/create?lang=node.js

**Comment by ralyodio** [comment]
How do I tell it to use `gpt-4`?

**Comment by ezzcodeezzlife** [comment]
@ralyodio set `model: "gpt-3.5-turbo",` to `gpt-4`. You have to get access though via the waitlist.

**Comment by ralyodio** [comment]
I'll give that  a try. I currently used `text-davinci-003`

**Comment by ralyodio** [comment]
Doesn't work I get a 404.

**Comment by ralyodio** [comment]
is there something I'm doing wrong? I wish they would document their api for this library:

```
			const res = await this.ai.createChatCompletion({
				model: "gpt-3.5-turbo",
				// prompt: aiPrompt,
				messages: [{ role: 'user', content: aiPrompt}],
				temperature: 0.4,
				max_tokens: 4000 - aiPrompt.length,
				top_p: 1,
				frequency_penalty: 0,
				presence_penalty: 0,
				stop: ["\"\"\""],
			});
```
