### ISSUE TITLE
When trying to use gpt-4 as model, its return 404

### ISSUE THREAD

**Issue by GFernandesS** [openai/openai-node#119]
### Describe the bug

I am implementing an API in Node to call the GPT-4 chat completion feature, however, it is returning a 404 error both when calling directly through the API and using the library. Is this model not yet available for use?

<img width="253" alt="issue_1" src="https://user-images.githubusercontent.com/49794902/227950948-cb1bd887-50f1-4839-a240-ff61fb459508.png">

<img width="181" alt="issue_2" src="https://user-images.githubusercontent.com/49794902/227950999-ce6ec2f0-be28-4b1d-84f4-e044a9a79dfd.png">

### To Reproduce

Just use the method of chat completion with GPT-4 as model

### OS

Windows

### Node version

18.15.0

### Library version

openai v3.2.1

**Comment by unicomp23** [comment]
https://github.com/openai/openai-node/issues/118

**Comment by nunocachada** [comment]
Hey @GFernandesS. 

I think you just need to generate a new api key. It worked for me. 
Best regards

**Comment by GFernandesS** [comment]
> Hey @GFernandesS. 
> 
> I think you just need to generate a new api key. It worked for me. 
> Best regards

Thanks for replying. I will try. 
Best regards :)

**Comment by marytal** [comment]
Hiya!

I'm making the this request, which works just fine:
```typescript
  const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: req.body.messages,
  });
  ```
  But when I try to change the model to `"gpt-4"`,  I get a 500 error:
  
<img width="660" alt="image" src="https://user-images.githubusercontent.com/8573756/229222265-552d0f97-2f90-428a-995d-22f3f7298c5a.png">

I can make requests to GPT4 in postman, so I don't think it's my API key. 

Any thoughts?

**Comment by GFernandesS** [comment]
> Hiya!
> 
> I'm making this request, which works just fine:
> 
> ```ts
>   const completion = await openai.createChatCompletion({
>     model: "gpt-3.5-turbo",
>     messages: req.body.messages,
>   });
> ```
> 
> But when I try to change the model to `"gpt-4"`, I get a 500 error:
> 
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/8573756/229222265-552d0f97-2f90-428a-995d-22f3f7298c5a.png">
> 
> I can make requests to GPT4 in postman, so I don't think it's my API key.
> 
> Any thoughts?

I think its better to open a new issue, but maybe you are sending a invalid content on messages property. What is the value of your body.messages?

**Comment by marytal** [comment]
Hmm the error seems to have resolved. I guess something else must have been going on. Thanks @GFernandesS!
