### ISSUE TITLE
If the argument of mask image is empty in createImageEdit(), the API will result in error

### ISSUE THREAD

**Issue by simongcc** [openai/openai-node#120]
### Describe the bug

according to the `api.ts`
the function createImageEdit is defined as
```
createImageEdit: async (image: File, prompt: string, mask?: File, n?: number, size?: string, responseFormat?: string, user?: string, options: AxiosRequestConfig = {}): 
```

It is documented as
```
* @param {File} [mask] An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where &#x60;image&#x60; should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as &#x60;image&#x60;.
```

Found problem,
1. In the current document, it is referred to the version 3.1.0. 
2. In the document, it is described to be optional.

In 3.2.1, if it is being left out, error will be prompted.

### To Reproduce

1. call createImageEdit
2. leave the mask argument blank with empty string ''
3. submit to run and will see the error.

### Code snippets

```JavaScript
const completion = await openai.createImageEdit(
                    readStream, // File stream for the original image
                    "A cute baby sea otter wearing a beret",
                    '', // leave back for testing, if using a mask, will be fine
                    2,
                    "256x256"
                  );

The test is conducted with original and mask image.
```

### OS

macOS 12.6.3

### Node version

v16.17.1

### Library version

openai 3.2.1

**Comment by MrJoyHolmes** [comment]
Why can't my code work properly even with a mask

**Comment by MrJoyHolmes** [comment]
Why can't my code work properly even with a mask, the order of my parameters is the same as yours, but the request failed with status code 400

**Comment by SimbaNinja917** [comment]
> Why can't my code work properly even with a mask, the order of my parameters is the same as yours, but the request failed with status code 400

https://github.com/openai/openai-node/issues/84#issuecomment-1482220469

**Comment by simongcc** [comment]
> Why can't my code work properly even with a mask, the order of my parameters is the same as yours, but the request failed with status code 400

Are you using 3.1.0 or 3.2.1? There is another problem in 3.2.1, the argument position is swapped and not same as 3.1.0 as documented.

**Comment by rattrayalex** [comment]
Sorry for the breaking swap in parameter order!

Our new [v4](https://github.com/openai/openai-node/discussions/182) of this library uses an object to specify these parameters, which you can use like so:

```ts
await openai.images.edit({
  image: fs.createReadStream("otter.png"),
  mask: fs.createReadStream("mask.png"),
  prompt: "A cute baby sea otter wearing a beret",
  n: 2,
  size: "1024x1024",
})
```

I hope this reduces any similar confusion, here and in the future.

Related: https://github.com/openai/openai-node/issues/95
