### ISSUE TITLE
CreateChatCompletion Request throws: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by leo-paz** [openai/openai-node#125]
### Describe the bug

I am making a simple request to the createChatCompletion endpoint using the open ai node sdk. My request is very simple but I am getting this error every time the request is sent: 

"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'    |     property 'socket' -> object with constructor 'TLSSocket'    --- property '_httpMessage' closes the circle    at JSON.stringify (<anonymous>)    at summarizationModel (/Users/leopaz/dev/outlit/Core/outlit/apps/functions/lib/openai.js:68:49)  at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async onSendPrompt (/Users/leopaz/dev/outlit/Core/outlit/apps/functions/lib/openai.js:97:25)"

### To Reproduce

```
const chatCompletionRequest: CreateChatCompletionRequest = {
            model: 'gpt-4',
            messages: [
                {
                    role: 'user',
                    // content: JSON.stringify(prompt),
                    content: 'hi',
                }
            ],
            max_tokens: 100,
            temperature: 0.7,
            stream: false,
        };

        functions.logger.log("ABOUT TO SEND CHAT COMPLETION", prompt);

        const chatCompletion = await openai.createChatCompletion(chatCompletionRequest);
```

### Code snippets

```JavaScript
const chatCompletionRequest: CreateChatCompletionRequest = {
            model: 'gpt-4',
            messages: [
                {
                    role: 'user',
                    // content: JSON.stringify(prompt),
                    content: 'hi',
                }
            ],
            max_tokens: 100,
            temperature: 0.7,
            stream: false,
        };

        functions.logger.log("ABOUT TO SEND CHAT COMPLETION", prompt);

        const chatCompletion = await openai.createChatCompletion(chatCompletionRequest);  
```

### OS

macOS

### Node version

16.18.0

### Library version

3.2.1

**Comment by leo-paz** [comment]
Fixed with:
```
await (await openai.createChatCompletion(chatCompletionRequest)).data
```

**Comment by xyp316721485** [comment]
把stream设置成true返回的数据还是偶尔会有循环引用
