### ISSUE TITLE
A complete node repository documentation is required

### ISSUE THREAD

**Issue by shxlsp** [openai/openai-node#126]
### Describe the feature or improvement you're requesting

The current README of this repository does not fully illustrate all its usages, and the official documentation only provides API reference. I need a user manual for this Node.js project repository. When I try to call the v3+ version, an error occurs, indicating that my access path is incorrect. I cannot find a solution through the README, but I did find an answer in the issues section. However, I would prefer to directly locate the corresponding API call through documentation.

PLEASE!!!!!!

目前这个仓库的readme不能体现所有的用法，官方提供的文档只是接口文档。我需要一份这个nodejs项目仓库的使用说明文档。我现在调用v3+版本的时候，会报错，提示我的访问路径不对。我没办法通过readme来找到解决方法，不过从issue中找到了回答。然而我期望通过文档能直接找到对应的api调用。

**Comment by rattrayalex** [comment]
Our upcoming v4 has a more thorough README: https://github.com/openai/openai-node/tree/v4#readme
