### ISSUE TITLE
createImageEdit is not working

### ISSUE THREAD

**Issue by ArsHinMQ** [openai/openai-node#129]
### Describe the bug

So I'm new to openai, I'm using version 3.2.1,  aside the [wrong argument ordering in docs](https://github.com/openai/openai-node/issues/95), the method ```openai.createImageEdit``` is not working
```
  const openaiRes = await openai.createImageEdit(image, prompt, image, n, size)
```
error:
```
TypeError: j.getHeaders is not a function
```
any workaround for this issue? I couldn't find any solution
also I'm using Supabase and Deno, in case it is related

### To Reproduce

1. call createImageEdit
2. raises the error

### Code snippets

```JavaScript
const configuration = new Configuration({
   apiKey: Deno.env.get('OPENAI_API_KEY')
})
const openai = new OpenAIApi(configuration)
const openaiRes = await openai.createImageEdit(image, prompt, image, n, size)
```

### OS

Linux - Debian

### Node version

None - Deno

### Library version

openai 3.2.1

**Comment by dawadam** [comment]
@ArsHinMQ what are properties detail ?
What is "image" ?

**Comment by dawadam** [comment]
When I try to use example documentation code, no error appears:

```
const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);
const response = await openai.createImageEdit(
  fs.createReadStream("otter.png"),
  fs.createReadStream("mask.png"),
  "A cute baby sea otter wearing a beret",
  2,
  "1024x1024"
);
```

But when I change the import to have "typescript" documentation, like this:

```
import { Configuration, OpenAIApi } from "openai";
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);
const response = await openai.createImageEdit(
  fs.createReadStream("otter.png"),
  fs.createReadStream("mask.png"),
  "A cute baby sea otter wearing a beret",
  2,
  "1024x1024"
);
```
An error appears on the line `fs.createReadStream("otter.png"),`.

Error is :
`Argument of type 'ReadStream' is not assignable to parameter of type 'File'`

This is because the method whant a "File" object:

`OpenAIApi.createImageEdit(image: File, prompt: string, mask?: File, n?: number, size?: string, responseFormat?: string, user?: string, options?: AxiosRequestConfig<any>): Promise<...>`

This is the difference between api documentation and library.

**Comment by ArsHinMQ** [comment]
> @ArsHinMQ what are properties detail ? What is "image" ?

image is of type ```File```, it's guaranteed and checked

**Comment by ArsHinMQ** [comment]
> When I try to use example documentation code, no error appears:
> 
> ```
> const { Configuration, OpenAIApi } = require("openai");
> const configuration = new Configuration({
>   apiKey: process.env.OPENAI_API_KEY,
> });
> const openai = new OpenAIApi(configuration);
> const response = await openai.createImageEdit(
>   fs.createReadStream("otter.png"),
>   fs.createReadStream("mask.png"),
>   "A cute baby sea otter wearing a beret",
>   2,
>   "1024x1024"
> );
> ```
> 
> But when I change the import to have "typescript" documentation, like this:
> 
> ```
> import { Configuration, OpenAIApi } from "openai";
> const configuration = new Configuration({
>   apiKey: process.env.OPENAI_API_KEY,
> });
> const openai = new OpenAIApi(configuration);
> const response = await openai.createImageEdit(
>   fs.createReadStream("otter.png"),
>   fs.createReadStream("mask.png"),
>   "A cute baby sea otter wearing a beret",
>   2,
>   "1024x1024"
> );
> ```
> 
> An error appears on the line `fs.createReadStream("otter.png"),`.
> 
> Error is : `Argument of type 'ReadStream' is not assignable to parameter of type 'File'`
> 
> This is because the method whant a "File" object:
> 
> `OpenAIApi.createImageEdit(image: File, prompt: string, mask?: File, n?: number, size?: string, responseFormat?: string, user?: string, options?: AxiosRequestConfig<any>): Promise<...>`
> 
> This is the difference between api documentation and library.

OK I think this is what happening: that in fact, the method ```openai.createImageEdit``` needs to accept two ```ReadStream``` as ```image``` and ```mask```, but the parameters' type is ```File```, which is not correct an causes error; as it works in JS but not in TS.

**Comment by mdibaiee** [comment]
My understanding is that this library is assuming that `FormData` has a method called `getHeaders`, but that is [not part of the standard specification of `FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData).

Only some non-standard implementations of `FormData` have this method, such as the [`form-data`](https://github.com/form-data/form-data) package's implementation.

This is confusing for users. OpenAI should either not rely on non-standard methods of `FormData`, or if it does, it should default to using an implementation of `FormData` that actually supports those methods.

**Comment by mdibaiee** [comment]
potentially related issue: https://github.com/openai/openai-node/issues/75

**Comment by rattrayalex** [comment]
Our upcoming [v4](https://github.com/openai/openai-node/discussions/182) fixes this; please give it a try!
