### ISSUE TITLE
Error 404  while using createChatCompletion

### ISSUE THREAD

**Issue by sandeepscet** [openai/openai-node#132]
### Describe the bug

Error
```
{
    "error": {
        "message": "Invalid URL (POST /v1/chat/completions)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

### To Reproduce

Use the Below Snippet, I Facing an issue while calling API from the browser.

### Code snippets

```JavaScript
const configuration = new Configuration({
    apiKey,
  })
  const openai = new OpenAIApi(configuration)

const completion = await openai.createChatCompletion({
      model: engine,
      messages: [{ role: 'user', content: prompt }],
    })
```

### OS

Window 10

### Node version

v18.14.2

### Library version

^3.2.1

**Comment by kevinohara80** [comment]
Same issue here.

**Comment by based64-eth** [comment]
Is this library not maintained anymore?

**Comment by sandeepscet** [comment]
@based64-eth  it seems so.
This is the most crucial method for chatbot API and it's not getting attention.

**Comment by melvinmt** [comment]
I was also experiencing the 404 error until I realized I was using the wrong model. You need to use a chat compatible model, like `gpt-3.5-turbo`.

This worked for me:
```
const response = await openai.createChatCompletion({
        model: "gpt-3.5-turbo",
        messages: [{ role: 'user', content: prompt }],
        temperature: 0,
        max_tokens: 500,
      });
```
