### ISSUE TITLE
{"message":"invalid csrf token"}

### ISSUE THREAD

**Issue by bianbiandashen** [openai/openai-node#135]
### Describe the bug

请求网址: https://ai.cone.cainiao-inc.com/api/retrieveFineTune
请求方法: POST
状态代码: 403 
远程地址: 59.82.112.179:443
引荐来源网址政策: strict-origin-when-cross-origin

{"message":"invalid csrf token"}

### To Reproduce

请求网址: https://ai.cone.cainiao-inc.com/api/retrieveFineTune
请求方法: POST
状态代码: 403 
远程地址: 59.82.112.179:443
引荐来源网址政策: strict-origin-when-cross-origin

{"message":"invalid csrf token"}

### OS

macos

### Node version

16.14

### Library version

    "openai": "^3.2.1",

**Comment by rattrayalex** [comment]
This doesn't appear to be making requests to OpenAI. This library is not typically intended for use in the browser.
