### ISSUE TITLE
Make BASE_PATH user changeable to enable local models

### ISSUE THREAD

**Issue by jmtatsch** [openai/openai-node#139]
### Describe the feature or improvement you're requesting

I would like to use [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) which offers a drop-in replacement for the OpenAI API to run my local models with the AgentGPT package further downstream.
To achieve this I would need a way to change BASE_PATH to my local api.

**Comment by jmtatsch** [comment]
https://github.com/reworkd/AgentGPT/issues/61

**Comment by jmtatsch** [comment]
Should also be interesting for people that want to use the azure endpoint.

**Comment by rattrayalex** [comment]
The [upcoming v4 release](https://github.com/openai/openai-node/discussions/182) of this library can be used with a custom `baseURL` config option; an example showing use with Azure is here: https://github.com/openai/openai-node/blob/v4/examples/azure.ts
