### ISSUE TITLE
Deleting Fine-tune model results in a 404

### ISSUE THREAD

**Issue by ozzyonfire** [openai/openai-node#14]
Using the call

```ts
const response = await openai.listFineTunes();
```
To get the list of my fine tunes. Then from that list, I'm using the `fine_tuned_model` field and passing that to:
```ts
await openai.deleteModel(model as string);
```
I receive a 404 error back that says;
```js
{
  error: {
    message: 'That model does not exist',
    type: 'invalid_request_error',
    param: 'model',
    code: null
  }
}
```
The url looks like this:
```
https://api.openai.com/v1/models/curie%3Aft-personal-2022-05-02-16-11-13
```
Following the steps in the documentation here: https://beta.openai.com/docs/api-reference/fine-tunes/delete-model

Thanks!

**Comment by ozzyonfire** [comment]
Okay so it actually does seem like it's working. However, when I list the fine-tunes, I get them all back (even the deleted ones). How are we supposed to determine whether a fine-tune was deleted or not?

The only thing I can find is the result or training file status. But if we delete the result file, it doesn't necessarily mean the fine tune is also deleted (or vice-versa). 

The way I discovered this is by going to the Open AI Playground and selecting my model there; I noticed there was only a subset of models showing in the list. 

So there must be a way to determine is a fine-tuned-model is deleted or not. Retrieving the fine-tune by it's ID doesn't seem to give any extra (status) information either.

**Comment by ibehnam** [comment]
Thanks for clarification, but I think this causes major confusion. It'd be better if we could delete a job along with its model and file (would result in half as many API calls too).

**Comment by schnerd** [comment]
I agree with you! Will relay this feedback to the team.

**Comment by ibehnam** [comment]
Thanks!
