### ISSUE TITLE
Check quota

### ISSUE THREAD

**Issue by linonetwo** [openai/openai-node#141]
### Describe the feature or improvement you're requesting

Is there an api to get result the same as we can see in the https://platform.openai.com/account/usage ?

This can be used to 

1. inform user quota in the UI
2. check connectivity issue

**Comment by rattrayalex** [comment]
Closing this as it's an API feature request rather than a client library feature request. If you're still interested in this functionality, please post it in [community.openai.com](https://community.openai.com)
