### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by ejkkan** [openai/openai-node#144]
### Describe the feature or improvement you're requesting

I would like to create a plugin to include data from a third part api from my node server using this lib.
I'm not able to join discord for information, neither getting answer from openai support regarding this matter.

Is this possible to do? If not, is it something you're looking into?

**Comment by rattrayalex** [comment]
Please give the function calling capabilities a try, if you haven't yet: https://openai.com/blog/function-calling-and-other-api-updates
