### ISSUE TITLE
Escape symbols for code snippets

### ISSUE THREAD

**Issue by Qlipoth** [openai/openai-node#147]
### Describe the feature or improvement you're requesting

How can I ensure that a response containing JavaScript code is always escaped? I am receiving a response from Open in the form of a text stream which contains both strings and pieces of JavaScript code. The problem is that sometimes the JavaScript code is not properly escaped with triple tilde characters. Is there any special option for that?

**Comment by rattrayalex** [comment]
You might try the new function calling feature: https://openai.com/blog/function-calling-and-other-api-updates
