### ISSUE TITLE
Enhancing Error Messages for Gated Models

### ISSUE THREAD

**Issue by joelalcedo** [openai/openai-node#161]
### Describe the feature or improvement you're requesting

When a user does not have access to alpha models or other gated models, provide a more expressive error message. For example, I do not have access to gpt-4-32k. When invoking chat completion, I get this error:

` Error in OpenAI API call: {
error: {
message: 'The model: gpt-4-32k does not exist',
type: 'invalid_request_error',
param: null,
code: 'model_not_found'
}
`

Alternative suggestion: a bool that checks if the model is valid, and another bool that checks if the user has access. This allows you throw a new error if the model is valid and the user does not have access, e.g.:

` Error in OpenAI API call: {
error: {
message: 'The model: gpt-4-32k is not enabled on your account',
type: 'invalid_request_error',
param: null,
code: 'model_not_found'
}
`

**Comment by rattrayalex** [comment]
Closing this as it's an API feature request rather than a client library feature request. If you're still interested in this functionality, please post it in [community.openai.com](https://community.openai.com)
