### ISSUE TITLE
getting 400 without error message

### ISSUE THREAD

**Issue by gbbest15** [openai/openai-node#162]
### Describe the bug

i am getting 400 without error message.. 

### To Reproduce

1. fetch the latest update.
2. use the code  snippets provided

### Code snippets

```JavaScript
export class ChatGPTServiceImplemnt implements ChatGPTService {
  async sendMessage(message:string): Promise<string|undefined> {
    try {
      const respons = await openai.createChatCompletion({
        model: "gpt-3.5-turbo",
        messages: [{ role: "user", content: message }],
        temperature: 0,
        top_p: 1.0,
        n: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
        stop: ["#", ";"],
      });
      return respons.data.choices[0].message?.content;
    } catch (error) {
      console.log(`this is the error from this ${error}`);
      throw error;
    }
  }
}
```

### OS

macOs

### Node version

v18.12.1

### Library version

3.2.1

**Comment by zkny** [comment]
I have the same issue

**Comment by gbbest15** [comment]
now i am getting this error `Request failed with status code 401`

**Comment by felipetodev** [comment]
same with https://api.openai.com/v1/embeddings
`message: Request failed with status code 400`

**Comment by gbbest15** [comment]
> same with https://api.openai.com/v1/embeddings `message: Request failed with status code 400`

can you push your code ?

**Comment by Jalapina** [comment]
im getting this error too

**Comment by rattrayalex** [comment]
Our new [v4](https://github.com/openai/openai-node/discussions/182) should include more helpful error messages. Please open a new issue if you run into continued problems with it.
