### ISSUE TITLE
Occasionally getting 429 Too many requests error

### ISSUE THREAD

**Issue by adamk22** [openai/openai-node#165]
### Describe the bug

I have an app that makes 8 text completion requests to OpenAI using the GPT3.5 turbo in the back-end. The requests are chained together and all together I'm using around 5000 tokens. I have a pay as you go account (older than 48 hours) which according to the documentation about rate limits means that I can make 3500 requests per minute or do 90000 tokens per minute. Now considering the limitations, I believe I don't really hit any rate limits here but somehow I get a 429 Too many requests error back on some occasions. Currently the app doesn't have any active users than me.

### To Reproduce

It happens randomly, so it's hard to say how to reproduce this issue other than chaining multiple createChatCompletions back to back.

### Code snippets

```JavaScript
A request looks like this:

function openAIRequest(prompt: string) {
   const response = await OpenAI.createChatCompletion({
			model: 'gpt-3.5-turbo',
			temperature: 0.8,
			max_tokens: 2000,
			messages: [
				{
					role: "user",
					content: prompt
				}
			]
		});

   return response;
} 
```

And it's used like so in the backend:

```
async function makeRequest() {
   const response1 = await openAIRequest1(prompt)
   const response2 = await openAIRequest2(prompt)
   ...etc
}
```
```


### OS

macOs

### Node version

Node v16.14.2

### Library version

"openai": "^3.2.1",

**Comment by horbel** [comment]
Same here

**Comment by adamk22** [comment]
I managed to fix it using a retry backoff strategy someone mentioned in another issue. You can either use a package: https://www.npmjs.com/package/exponential-backoff or write your own. This doesn't fix the fact that it still gives back a 429 error while it shouldn't, but its a fine workaround for now.

**Comment by jvdutrag** [comment]
Same issue.

**Comment by mepc36** [comment]
Same issue. Tried exponential backoff - it helped a little, but my traffic usage meant that it helped not that much. My next solution is suboptimal, but my last choice: to use POSTman to translate cURL requests in [the OpenAI API docs](https://platform.openai.com/docs/api-reference/completions/create) into handrolled axios requests.

**Comment by agustinacassi** [comment]
Same issue here.

**Comment by dupiesdupreez** [comment]
I can replicate the issue with "transcribe" of a mp3 file of over 50seconds long. Happens constantly....

**Comment by Elben9** [comment]
same issue

**Comment by weimingdmx** [comment]
same issue

**Comment by chdzma** [comment]
any fix?

**Comment by rattrayalex** [comment]
This library's upcoming [v4](https://github.com/openai/openai-node/discussions/182) automatically retries 429 requests with exponential backoff; please give it a try.

If you encounter a 429 when you were clearly not close to the limit, please write in to support or https://community.openai.com with a request ID.

If you encounter 429s associated with frequent and/or large requests, consider making less frequent or smaller requests.
