### ISSUE TITLE
localVarFormParams.getHeaders is not a function

### ISSUE THREAD

**Issue by nawabsahab16** [openai/openai-node#166]
### Describe the bug

When I am using OpenAI node SDK to createTranscription,

I am sending it the file like this,

  const mediaBlob = await fetch(url)
    .then(response => response.blob());

const audio = new File(
    [mediaBlob],
    'demo.mp4',
    { type: 'video/mp4' },
  );

const resp = await openai.createTranscription(audio, 'whisper-1'); // even audio.text(), stream() etc doesn't work

It's throwing me localVarFormParams.getHeaders is not a function

### To Reproduce

1. Try to send an audio file for transcription using openai.createTranscription
2. Try to send a file
3. Error thrown - localVarFormParams.getHeaders is not a function

### Code snippets

```JavaScript
no response
```

### OS

macOS

### Node version

Node v16.16.2

### Library version

openai v3.2.1

**Comment by robriks** [comment]
Have you found a solution? Calling the openai instance (after configured) with any method returns this error to me as well.
