### ISSUE TITLE
ERR_FR_MAX_BODY_LENGTH_EXCEEDED when calling createTranscription

### ISSUE THREAD

**Issue by mduraidi** [openai/openai-node#167]
### Describe the bug

ERR_FR_MAX_BODY_LENGTH_EXCEEDED when calling createTranscription

### To Reproduce

1. use large file (within the limit of 25 MB), in my case the file size is: 19.4 MB

### Code snippets

```JavaScript
async function generateJson() {
const resp = await openai.createTranscription(
  fs.createReadStream("large_file.mp3"), // less than 25 MB
  "whisper-1",
  '',
  'vtt',
  0,
  'fr'
);
```

### OS

Windows 7

### Node version

Node v14.17.6

### Library version

openai v3.1.0

**Comment by ffrenchm** [comment]
The SDK uses Axios under the hood, and Axios has a lower default max body length than the 25MB allowed by Whisper. I solved this error by setting max body length to 25MB in the axios config like so:

const maxBodyLength = 25 * 1024 * 1024

const { data } = await openai().createTranscription(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    createReadStream(filePath) as any,
    "whisper-1",
    prompt,
    "verbose_json",
    undefined,
    languageCodeISO2,
    {
      maxBodyLength,
    }
  ) as AxiosResponse<any, unknown>

**Comment by dupiesdupreez** [comment]
@ffrenchm Didn't work for me..

**Comment by DigitalSolomon** [comment]
didn't work for me either @dupiesdupreez ... after wasting too much time, I ended up just installing [whisper.cpp](https://github.com/ggerganov/whisper.cpp) locally and now I'm running speech-to-text quickly and easily off my laptop.

**Comment by es-lynn** [comment]
Have opened a PR to set the default maxBodyLength to 25MB.

In the mean time you can manually increase the maxBodyLength:

```
const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
    baseOptions: {
        maxBodyLength: 26214400 // 25 MB
   }
});

const openai = new OpenAIApi(configuration);
```

**Comment by rattrayalex** [comment]
Thank you @es-lynn ! However, we're soon moving away from axios to use `node-fetch` (or native `fetch` in some environments), which should not have this issue:

[v4.0.0 beta](https://github.com/openai/openai-node/discussions/182)

Please give it a try and let us know if you run into any issues, especially with uploading large files for transcriptions!
