### ISSUE TITLE
Docs: match the quickstart and api-reference

### ISSUE THREAD

**Issue by dereklowlind** [openai/openai-node#169]
### Describe the bug

Hello, awesome library! I noticed that on the /speech-to-text/quickstart docs there is only curl and python as options where on the /api-reference/audio docs the node option exists. The python code in the two docs looks identical. I wasn't sure what to file this under so feel free to change it from a bug to something else.

https://platform.openai.com/docs/guides/speech-to-text/quickstart?lang=python
https://platform.openai.com/docs/api-reference/audio/create?lang=node

### To Reproduce

1. The [quickstart](https://platform.openai.com/docs/guides/speech-to-text/quickstart?lang=python) does not have the node option
2. The [api-reference](https://platform.openai.com/docs/api-reference/audio/create?lang=node) does have node as an option

### OS

macOs

### Node version

node v18.7.0

### Library version

openai v3.2.1

**Comment by rattrayalex** [comment]
Thanks for the request! Please re-post it in [community.openai.com](https://community.openai.com) – we're trying to keep issues on this repo focused exclusively on SDK bugs and feature requests.
