### ISSUE TITLE
In this way, the content is not complete

### ISSUE THREAD

**Issue by didoee** [openai/openai-node#170]
### Describe the bug

![image](https://github.com/openai/openai-node/assets/112919246/5fe022f7-3c0c-4402-b8e3-730e03f8a80a)

### To Reproduce

    ![image](https://github.com/openai/openai-node/assets/112919246/5fe022f7-3c0c-4402-b8e3-730e03f8a80a)

### OS

win11

### Node version

16.20.0

### Library version

3.2.1

**Comment by rattrayalex** [comment]
Instead of `completion.data.choices[0].text`, you likely want `completion.data.choices[0].message.content`.
