### ISSUE TITLE
Upgrading from 3.2.1 to 3.3.0 introduces breaking changes.

### ISSUE THREAD

**Issue by killthebuddh4** [openai/openai-node#179]
### Describe the bug

I believe that changing the `content` field to being optional is a breaking change. I'm using TypeScript so it's only breaking my build, but this is going to cause a ton of projects to start failing at runtime if the API is indeed leaving it out now.

### To Reproduce

This is pretty straightforward, you can observe the problem directly in the type.

### Code snippets

```TypeScript

// Version 3.2.1

export interface ChatCompletionResponseMessage {
    /**
     * The role of the author of this message.
     * @type {string}
     * @memberof ChatCompletionResponseMessage
     */
    'role': ChatCompletionResponseMessageRoleEnum;
    /**
     * The contents of the message
     * @type {string}
     * @memberof ChatCompletionResponseMessage
     */
    'content': string;
}
```

```TypeScript

// Version 3.3.0

export interface ChatCompletionResponseMessage {
    /**
     * The role of the author of this message.
     * @type {string}
     * @memberof ChatCompletionResponseMessage
     */
    'role': ChatCompletionResponseMessageRoleEnum;
    /**
     * The contents of the message.
     * @type {string}
     * @memberof ChatCompletionResponseMessage
     */
    'content'?: string;
    /**
     *
     * @type {ChatCompletionRequestMessageFunctionCall}
     * @memberof ChatCompletionResponseMessage
     */
    'function_call'?: ChatCompletionRequestMessageFunctionCall;
}
```

### OS

N/A

### Node version

N/A

### Library version

openai v3.3.0

**Comment by NJordan72** [comment]
There are also instances, namely when an assistant returns a function call, where the API will error if passing that message back in with content missing.  Instead content needs to be null which is also not supported by the type definition.

**Comment by rattrayalex** [comment]
Thank you for the report; we've overhauled our types in the [upcoming v4](https://github.com/openai/openai-node/discussions/182) of this library – please give it a try!

Note that we may ship changes that break TypeScript types but not runtime behavior as minor versions in the future. We absolutely seek to avoid changing API behavior in breaking ways.
