### ISSUE TITLE
node type

### ISSUE THREAD

**Issue by lcs-bgonzalez** [openai/openai-node#180]
### Describe the bug

Error message `Cannot find name 'require'. Do you need to install type definitions for node? Try 'npm i --save-dev @types/node'.`  

### To Reproduce

-

### Code snippets

May be solved by having the "node" type in the `types` attribute of `tsconfig.json`.

```JavaScript
{
  "compilerOptions": {
    "declaration": true,
    "target": "es6",
    "module": "commonjs",
    "noImplicitAny": true,
    "outDir": "dist",
    "rootDir": ".",
    "types": [ "node" ],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

### OS

Windows 10

### Node version

Node v18.12.1

### Library version

openai 3.3.0

**Comment by rattrayalex** [comment]
Our [upcoming v4](https://github.com/openai/openai-node/discussions/182) has better support for different module configurations and environments. Please give it a try and share your feedback in the above thread!
