### ISSUE TITLE
"function_call" parameter is not available

### ISSUE THREAD

**Issue by tylr-r** [openai/openai-node#184]
### Describe the bug

"function_call" parameter is not available via node package even though it is in the documentation. "functions" parameter seems to work though.

### To Reproduce

Try to add "function_call" parameter to createChatCompletion request.

### Code snippets

```JavaScript
openai.createChatCompletion({
      model: 'gpt-3.5-turbo-0613',
      messages: [],
      function_call: true,
      functions: ai_functions,
    });
```

### OS

macOS

### Node version

Node v16.19.1

### Library version

openai v3.2.1

**Comment by miguelvalente** [comment]
@tylr-r Why did you close the issue? Were you able to use the function_call argument?
