### ISSUE TITLE
Function Parameter being array does not work

### ISSUE THREAD

**Issue by SinanAkkoyun** [openai/openai-node#185]
### Describe the bug

I can not use type: 'array', items: 'string' for example to supply arrays as parameters.

Is that a problem with the API itself? It conforms with JSON schema as far as I know

### To Reproduce

`{ name: 'channelIds', type: 'array', description: 'An array of channel IDs', items: { "type": "string" }, required: true }`
Fetch a function call chat API call

### OS

Linux

### Node version

v18

### Library version

latest

**Comment by rattrayalex** [comment]
This should be fixed in our [upcoming v4](https://github.com/openai/openai-node/discussions/182); please give it a try and reopen if the problem persists.
