### ISSUE TITLE
prompt don't work  in imageEdit model 

### ISSUE THREAD

**Issue by mernsolution** [openai/openai-node#186]
### Describe the bug

I wanted to  Build edit image  app then i send   prompt value in backend then show error prompt value is null , but i debug and see my value is arrive in Backend but in a model don't work. After i write my prompt value in mode like [prompt : " add dragon and blue Background ] after agin show error prompt value is null

### To Reproduce

i fetch this error 

Error editing image: RequiredError: Required parameter prompt was null or undefined when calling createImageEdit.
    at exports.assertParamExists (C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\common.js:39:15)
    at Object.<anonymous> (C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:387:22)
    at Generator.next (<anonymous>)
    at C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:17:12)
    at Object.createImageEdit (C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:383:96)
    at Object.<anonymous> (C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:1148:75)
    at Generator.next (<anonymous>)
    at C:\Users\USER\Desktop\Image-genarate\server\node_modules\openai\dist\api.js:21:71 {
  field: 'prompt'
}

### Code snippets

```JavaScript
My prompt is define but get error prompt is null 
const { Configuration, OpenAIApi } = require("openai");
const fs = require('fs');
const path = require('path');
const multer = require('multer');

const configuration = new Configuration({
  apiKey: "sk-HU05dPhCJTppTrhNSVHfT3BlbkFJFXHCEWIoYBE7GN9fmi" 
});

const openai = new OpenAIApi(configuration);

// Configure multer for file upload
const storage = multer.diskStorage({
  destination: path.join(__dirname, 'uploads'),
  filename: (req, file, cb) => {
    cb(null, file.originalname);
  },
});

const upload = multer({ storage }).fields([{ name: 'file1' }, { name: 'file2' }]);

exports.editImage = async (req, res) => {
  try {
    await upload(req, res, async (error) => {
      if (error) {
        console.error('Error uploading files:', error);
        return res.status(400).json({ error: 'File upload failed' });
      }
      const { size,  } = req.body;
      // Validate the prompt field
      // if (!prompts) {
      //   return res.status(400).json({ error: 'Prompt field is required' });
      // }

      const file1 = req.files['file1'][0];
      const file2 = req.files['file2'][0];

      const file1Path = path.join(__dirname, 'uploads', file1.filename);
      const file2Path = path.join(__dirname, 'uploads', file2.filename);

      let imageUrl;
      try {
        const response = await openai.createImageEdit({
          image:fs.createReadStream(file1Path),
          mask:fs.createReadStream(file2Path),
          prompt:"add dragon and blue background",
          n:1,
          size: size
        });

        imageUrl = response.data.output.url;
      } catch (error) {
        console.error('Error editing image:', error);
        return res.status(500).json({ error: 'Image editing failed' });
      } finally {
        // Delete the uploaded files
        fs.unlinkSync(file1Path);
        fs.unlinkSync(file2Path);
      }

      res.json({ imageUrl });
    });
  } catch (error) {
    console.error('Error handling file upload:', error);
    res.status(500).json({ error: 'File upload failed' });
  }
};
```

### OS

windows 10

### Node version

Node v18.12.0

### Library version

"openai": "^3.3.0"

**Comment by rattrayalex** [comment]
@mernsolution can you try with the upcoming v4 of the library? You'll need to rewrite your integration code, but it should support this: https://github.com/openai/openai-node/discussions/182

**Comment by xiaohanp** [comment]
I think the problem is caused by using payload, which is not allowed in createImageEdit. Also make sure you have the right order of params + mask is not really optional in my case...
The pramas should be something like 

```
fs.createReadStream(file1Path),
"add dragon and blue background",
fs.createReadStream(file2Path),
1,
"256x256",
```


ref: 
https://community.openai.com/t/create-image-edit-in-node-js-library-watch-out-for-the-order-of-positional-arguments/292812
https://community.openai.com/t/image-editing-api-without-mask/23307/10
