### ISSUE TITLE
Functions not working with streaming

### ISSUE THREAD

**Issue by mark-ramsey-ri** [openai/openai-node#188]
### Describe the bug

I have streaming working well with this library.

I am trying to add a call to a function, but the response does not include the required arguments.

The model recognizes that it wants to use the function, and the part.choices[0].finish_reason contains the value of "function_call"

But the function name nor the argument is included in the response.  Here is what is in the part.choices:
choices: [ { index: 0, delta: {}, finish_reason: 'function_call' } ]

I was expecting to see the function name and the args in delta.

### To Reproduce

1. Create a function
2. Define the function as part of the chat.completions.create command
3. Set stream: true on the command
4. Loop through the chunks
5. When the function is requested by the model, the name and args are not included in the chunk.

### OS

Linux

### Node version

Node v18.12.1

### Library version

openai-node 4.0.0-beta.1

**Comment by rattrayalex** [comment]
Thanks for the report, we'll take a look at this soon. Did you notice whether the name & arguments are included in a previous or ensuing chunk?

**Comment by mark-ramsey-ri** [comment]
I did not see if the name and arguments was included in a later chunk as the 'function_call' is a finish reason, so my assumption was it was the last chunk.


-------- Original message --------
From: Alex Rattray ***@***.***>
Date: 7/1/23 3:36 PM (GMT-05:00)
To: openai/openai-node ***@***.***>
Cc: Mark Ramsey ***@***.***>, Author ***@***.***>
Subject: Re: [openai/openai-node] Functions not working with streaming (Issue #188)


Thanks for the report, we'll take a look at this soon. Did you notice whether the name & arguments are included in a previous or ensuing chunk?

**Comment by mark-ramsey-ri** [comment]
As a work around, if the streaming returns the finish_reason = 'function_call' I then do another call to the model with stream: false and it returns the finish_reason = 'function_call" and includes the function name and arguments.  So it works with stream off.

**Comment by schnerd** [comment]
@mark-ramsey-ri Any chance you can share code that consistently reproduces this issue?

**Comment by mark-ramsey-ri** [comment]
// API call to return the chat_messages
            const resp_chat = await openai.chat.completions.create({
                model: chat_model,
                messages: chat_messages,
                temperature: model_temp,
                max_tokens: resp_tokens,
                stream: true,
                functions: defined_functions,
            });

            // Loop through response stream and publish to channel
            for await (const part of resp_chat) {
                if (part.choices[0].finish_reason === null) {
                    const content = part.choices[0].delta.content;

                    // Publish the response to the channel if content is not null
                    if (content !== undefined && content !== null) {
                        console.log("Finish_reason is null, publishing response: ", content);
                        channel.publish({
                            data: {
                                event: 'response',
                                token: content,
                                interactionId
                            }
                        });
                    }
                } else if (part.choices[0].finish_reason === "stop") {
                    break;
                } else if (part.choices[0].finish_reason === "length") {
                    channel.publish({
                        data: {
                            event: 'response',
                            token: "\n\n*** Response truncated due to exceeding total token length. ***\n",
                            interactionId
                        }
                    });
                    break;
                } else if (part.choices[0].finish_reason === "function_call") {
                    console.log("Function call detected", part.choices[0]);
                    const functionToUse = part.choices[0].delta.function_call.name;
                    let dataToReturn = {};

                    if (functionToUse === "ask_cdp") {
                        const query = part.choices[0].delta.function_call.arguments;
                        dataToReturn = ask_cdp(query);
                    }

**Comment by rattrayalex** [comment]
Thanks @mark-ramsey-ri !

The function name/arguments may stream in prior to the `function_call` finish reason; you need to accumulate them like so:

```ts
let args = '';
for await (const part of stream) {
  const argPart = part.choices[0]?.delta?.function_call?.arguments;
  if (argPart) {
    args += argPart;
  }
}

console.log(args);
```
(not a complete example, and not written to integrate with your sample code above). 

We plan to add a helper method to make dealing with this easier soon; we'll seek your feedback as soon as we have a draft!

**Comment by mark-ramsey-ri** [comment]
I updated my code to capture the parts when the finish_reason is null to accumulate the function_name and args.

The first message is returned with the function_name, and then there are a number of chunks to obtain the args, but as you suggest, the args are passed in chunks and then the function_call finish_reason is returned.

**Comment by rattrayalex** [comment]
Great! We hope to provide utilities and examples for this, but in the meantime, would you mind sharing your updated code here to benefit others looking for this information too?

**Comment by mark-ramsey-ri** [comment]
Two key changes to my code:  When the chunk has null as finish_reason, needed to add the code to accumulate the function name and args:

                if (part.choices[0].finish_reason === null) {

                    const content = part.choices[0].delta.content;
                    const argPart = part.choices[0]?.delta?.function_call?.arguments;
                    const namePart = part.choices[0]?.delta?.function_call?.name;
                    if (argPart) {
                        funcArgs += argPart;
                    }
                    if (namePart) {
                        funcName += namePart;
                    }

Then when the chunk has a finish_reason of 'function_call', using what was accumulated to make the actual call to the function:

                } else if (part.choices[0].finish_reason === "function_call") {

                    channel.publish({
                        data: {
                            event: "status",
                            message: "Calling function to prepare answer...",
                        },
                    });

                    console.log("Function to use: ", funcName);
                    console.log("Function args: ", funcArgs);

                    let dataToReturn = "";
                    if (funcName === "ask_cdp") {
                        dataToReturn = ask_cdp(funcArgs);
                    } else if (funcName === "ask_nabu") {
                        dataToReturn = ask_nabu(funcArgs);
                    } else
                        dataToReturn = "Specified function not found.";

**Comment by mosnicholas** [comment]
@rattrayalex curious on the status of the updates? :) would love to build in / support streaming on our NextJS app for function calling.

**Comment by rattrayalex** [comment]
We're targeting a first release sometime next week, probably late next week. 

In your case, you might use it like so:
```ts
const stream = await client.chat.completions.create(…)
  .accumulate();

for await (const text of stream.textDeltas()) {
  channel.publish({
    data: {
      event: 'response',
      token: text,
      interactionId
    }
  });
}
const result: ChatCompletion = await stream.getFinalAcc();
const { finish_reason, message: { function_call } } = result.choices[0]
if (finish_reason === 'function_call') {
  if (function_call.name === "ask_cdp") {
    dataToReturn = ask_cdp(function_call.arguments);
  }
  // … check other functions …
  // send function call results to frontend
} 
// … handle other finish reasons …
```
How does this look to you? Are the names intuitive?

**Comment by mosnicholas** [comment]
@rattrayalex great, i'll give it a go.

Is the sdk reliable enough to be used in production? :) could try and set it up!

**Comment by rattrayalex** [comment]
It is! (Though it doesn't yet have the features I described just above)

**Comment by nicoelzer** [comment]
Hey @rattrayalex, facing the same issue – do you already have an ETA for the release, will it happen this week?

**Comment by rattrayalex** [comment]
Sorry @nicoelzer , not this week – hopefully next.

**Comment by eliasm307** [comment]
> We're targeting a first release sometime next week, probably late next week.
> 
> In your case, you might use it like so:
> 
> ```ts
> const stream = await client.chat.completions.create(…)
>   .accumulate();
> 
> for await (const text of stream.textDeltas()) {
>   channel.publish({
>     data: {
>       event: 'response',
>       token: text,
>       interactionId
>     }
>   });
> }
> const result: ChatCompletion = await stream.getFinalAcc();
> const { finish_reason, message: { function_call } } = result.choices[0]
> if (finish_reason === 'function_call') {
>   if (function_call.name === "ask_cdp") {
>     dataToReturn = ask_cdp(function_call.arguments);
>   }
>   // … check other functions …
>   // send function call results to frontend
> } 
> // … handle other finish reasons …
> ```
> 
> How does this look to you? Are the names intuitive?

If this is still open for feedback I dont think the names are intuitive.

> const text of stream.textDeltas()

This could use the `token` terminology because thats what its actually streaming, calling it something else makes it harder to understand imo, so could be `const token of stream.tokens()`, the example also hints to this as the `text` gets assigned to a property called `token`.

> const result: ChatCompletion = await stream.getFinalAcc();

`getFinalAcc` sounds odd, I assume its getting the resulting completion after stitching together the deltas? If it is what do you think about `await stream.result()` or `await stream.completion()` since you call the streamed chunks "deltas" then it means a "completion" is the full result? Could also do `await stream.fullResult()` or `await stream.fullCompletion()` for clarity, another alternative adjective is "overall" (and "complete" but it might sound odd as "completeCompletion") , but personally I think the short versions are readable enough, atleast to me and it looks right when you have the output ie 
`const result: ChatCompletion = await stream.result();`
or
`const result: ChatCompletion = await stream.completion();`

I also think its odd this method has `get` but `stream.textDeltas()` doesnt. I dont know if there are other similar methods but the naming convention should be consistent, either they all have a `get` prefix or none do imo

**Comment by rattrayalex** [comment]
Thank you very much for the feedback @eliasm307 ! 

`tokens()` would be a bit misleading since there may be more than one token in each chunk, but it's still worth considering. 

What do you think about `await stream.finalResult()`?

**Comment by eliasm307** [comment]
> What do you think about await stream.finalResult()?

I think it works, however I was trying to avoid `final` as it could be confusing as it sounds like the final `delta` result from the stream not the sum of the deltas

**Comment by eliasm307** [comment]
Another alternative could be `chunks` since that's what you called them

**Comment by mosnicholas** [comment]
any progress here @rattrayalex ? updated timeline?

**Comment by rattrayalex** [comment]
We're shooting to get it out tomorrow! 🤞 You can see an updated version of what we're thinking [here](https://github.com/openai/openai-node/discussions/182#discussioncomment-6646741).

**Comment by rattrayalex** [comment]
Thoughts on the names `.contentDeltas()` vs `.contentStream()` vs `.contentChunks()` for the thing that gets you a series of response tokens?

Thoughts on `.finishedChatCompletion()`, `.finishedMessage()`, and `.finishedContent()`? (complements not substitutes)

**Comment by eliasm307** [comment]
Hi, From the options I think contentStream is the most intuitive, and the name is the one that sounds the most like it's just text. for the others I think its less clear what a delta or a chunk is eg are they objects? I know the term delta has been used in other places of the API to mean object things

I'm not sure what the second paragraph is asking

**Comment by rattrayalex** [comment]
Thank you!

**Comment by mosnicholas** [comment]
@rattrayalex any progress / updated timeline here? :)

**Comment by rattrayalex** [comment]
Hi @mosnicholas , we decided to delay work on this until after the release of `4.0.0`; we hope to have a new `4.1.0-beta` with streaming & function calling helpers sometime next week. We have some further ideas here: https://github.com/openai/openai-node/discussions/182#discussioncomment-6705446 (comments, feedback, and ideas are welcome).

**Comment by mosnicholas** [comment]
Thank you @rattrayalex.

Am I to understand that 4.0.0 Beta is ready to be used? Or should I hold off until it goes out of Beta (will that be any time soon)?

**Comment by rattrayalex** [comment]
4.0.0 has been released!
