### ISSUE TITLE
Integrate ESLint and Prettier in TypeScript Library Project

### ISSUE THREAD

**Issue by ImBIOS** [openai/openai-node#190]
### Describe the feature or improvement you're requesting

As a part of our continuous effort to improve code quality and consistency, we should integrate ESLint and Prettier into our TypeScript library project.

ESLint is a popular JavaScript linter, and when used with TypeScript, it can significantly help us catch common mistakes in the code before they make it to production. Furthermore, ESLint can be customized to follow our own coding standards or to comply with popular style guides.

Prettier, on the other hand, is an opinionated code formatter. Integrating it into our project can help maintain consistent formatting across our codebase, leading to better readability and maintainability.

Combining the two could enhance our workflow and code quality, preventing bugs and making our code easier to understand.

To implement this feature, we'll need to:

1. Install and configure ESLint with TypeScript support.
2. Set up rules based on our coding standards or a popular style guide.
3. Install and configure Prettier.
4. Ensure that Prettier and ESLint play well together using `eslint-config-prettier` or a similar tool.
5. Add scripts in the package.json file to allow easy linting and code formatting.
6. (Optional) Set up pre-commit hooks using a tool like `husky` to enforce the linting and formatting rules before committing.

Please consider this proposal and let me know if there are any concerns or questions.

### Additional context

Having these tools integrated into our project not only improves our code quality but also offers a more consistent developer experience. This way, we can prevent many potential issues before they happen and maintain a more consistent, readable, and clean codebase. Additionally, this can be an excellent learning opportunity for new developers, allowing them to become familiar with best practices in TypeScript development.

**Comment by RobertCraigie** [comment]
Hey! We have an [upcoming version v4.0.0](https://github.com/openai/openai-node/discussions/182) that makes use of ESLint & Prettier.
