### ISSUE TITLE
stream claims it was aborted even though it was not

### ISSUE THREAD

**Issue by DerKorb** [openai/openai-node#194]
### Describe the bug

When using 4.0 beta.4, when I do a stream chat completion, after the for await loop the AbortController behaves as if it was aborted, even though I am quite certain it was not.
This is signal.reason:
aborted DOMException [AbortError]: This operation was aborted
     at new DOMException (node:internal/per_context/domexception:53:5)
     at AbortController.abort (node:internal/abort_controller:342:18)
     at Stream.[Symbol.asyncIterator] (/app/node_modules/openai/src/streaming.ts:69:12)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
     at streamChatCompletion (/app/src/streamChatCompletion.ts:39:36)

Is it possible that finishing the stream is handled as if it was aborted?

### To Reproduce

Stream a chat completion, check the result of the corresponding abortcontroller.signal

### OS

Manjaro

### Node version

node 18

### Library version

v4 beta.4

**Comment by RobertCraigie** [comment]
@DerKorb it's my understanding that the response has to be aborted to avoid hanging. For example, if you remove [this line](https://github.com/openai/openai-node/blob/be1e275cab731baf7c63cd7356e3563fde2aaaf8/src/streaming.ts#L73) & then run the `examples/demo.ts` script it will hang indefinitely.

I may be incorrect though & there could be a way to avoid hanging without explicitly aborting.

I'm curious what your use case is for checking if the stream was aborted or not?

**Comment by DerKorb** [comment]
I solved this now by checking whether the finish_resean is null.
I have a multi agent setup where agents communicate with each other. I implemented an abort button to stop generation, but then the aborted response would still trigger the next generation from the next agent.

**Comment by DerKorb** [comment]
I find it odd, that a successfully completed stream counts as aborted.

**Comment by rattrayalex** [comment]
Thank you @DerKorb ! We have a fix that will be released in the next version of the beta.

**Comment by rattrayalex** [comment]
This should be fixed in `v4.0.0-beta.5`, please give it a try!
