### ISSUE TITLE
`ChatCompletionRequestMessage` doesn't allow `null` content

### ISSUE THREAD

**Issue by mattrossman** [openai/openai-node#195]
### Describe the bug

The docs indicate that `null` is an expected value for message "content":

<img width="645" alt="CleanShot 2023-07-13 at 15 21 24@2x" src="https://github.com/openai/openai-node/assets/22670878/05846811-3625-492e-b135-8d835787941b">

However, the type definition for `OpenAPI.ChatCompletionRequestMessage` only allows string or undefined.

When passing message that utilize "function_call" to `createChatCompletion()`, I have to specify the message content as `null`. If I simply omit the "content" field or set it to `undefined`, I get a 400 "Bad Request" error. 

<img width="259" alt="CleanShot 2023-07-13 at 15 30 27@2x" src="https://github.com/openai/openai-node/assets/22670878/a2bb5ee3-bb70-475b-8e43-26d489c9d637">

To avoid this 400 error I specify the content as `null`, producing a type error:

<img width="1003" alt="CleanShot 2023-07-13 at 15 33 14@2x" src="https://github.com/openai/openai-node/assets/22670878/52f7e181-2dcb-4125-8784-965c668f4d99">

Similarly, the type for `OpenAI.ChatCompletionResponseMessage` doesn't reflect the fact that a response's "content" can contain a `null` value.

### To Reproduce

Specify a message such as:

```ts
{
  role: "assistant",
  content: null,
  function_call: {
    name: "...",
    arguments: "..."
  }
}
```

TypeScript Playground reproduction:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wPJgKYDsCCAknAGZQQhwDkEOuywVcA9M3DAJ46oBccAzADohABgBQYgMYRcqeCGypUyAOaK+WPEUEBhABbIYOimAA22GMBkAlbAEcAropgBZRcrUBtALpwAvHA+EgpKqoqCYA6oegAUAN5icHDk5nwARGiowHLIuDBpADSJcNJ5eDB8uA6mpkVJJA64kpYyAPqSyDV8CUlJ9ArpIBytDU0tuIXFSchQKg4KebxwaYKracUAvmIbAJRAA

### OS

macOS

### Node version

Node v18.16.0

### Library version

openai v3.3.0

**Comment by rattrayalex** [comment]
I believe this bug is fixed in our [upcoming v4 beta](https://github.com/openai/openai-node/discussions/182#discussioncomment-6443234); can you give that a try instead?
