### ISSUE TITLE
Passing "gpt-4" as model returns 404 not found

### ISSUE THREAD

**Issue by jacksonStone** [openai/openai-node#198]
### Describe the bug

I have some code that previously passed in the "gpt-3.5-turbo" model string. This code worked fine. Now with the general release of GPT 4 API, I wanted to test it by updating this string in place. It returns 404 no found when passing "gpt-4". 

I am using the latest release of this library and am totally confounded.

Other details that may be relevant - though I have a paid account, my usage has been rounded down to no charge the past 2 months, so perhaps I do not qualify as a paid account yet? In either case, the error is not a good one. It does not communicate the actual failure reason.

### To Reproduce

Any call the chatCompletions with GPT-4 as the model

### Code snippets

`const { Configuration, OpenAIApi } =  require("openai");
(async function(){
    const configuration = new Configuration({
        apiKey: process.env.OPENAI_API_KEY,
        });
        const openai = new OpenAIApi(configuration);
        const chatResponse = await openai.createChatCompletion({
        model: "gpt-4",
        messages: [{role: "user", content: "how are you?"}],
        });
        console.log(chatResponse)
})()
`

### OS

macOS

### Node version

Node v16

### Library version

v3.0.1

**Comment by rattrayalex** [comment]
Sorry about this. I agree this error message is not the best. 

[Per the documentation](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4): 

> [On July 6, 2023](http://openai.com/blog/gpt-4-api-general-availability), we gave all API users who have a history of successful payments access to the [GPT-4 API](https://platform.openai.com/docs/models/gpt-4) (8k). We plan to open up access to new developers by the end of July 2023, and then start raising rate-limits after that depending on compute availability.

As stated here, we hope you'll have access within a week or two.
