### ISSUE TITLE
Issue with v4 in ReactNative iOS

### ISSUE THREAD

**Issue by vanjaoljaca** [openai/openai-node#199]
### Describe the bug

Using v4 on ReactNative I am getting 404 from CloudFlare on ReactNative iOS. Same code works in standard node. Haven't checked with v3 yet. Other external requests work fine.

Same code in both environments, code copied from sample.

Log outputs compared:

```
# In ReactNative metro EAS
 LOG  OpenAI:DEBUG:request https://api.openai.com/v1/completions/ 
{"body": {"model": "text-davinci-003", "prompt": "Say this is a test"}, 
"method": "post", 
"path": "/completions", 
"stream": false
} 
{"Accept": "application/json", "Authorization": "Bearer KEY", "Content-Length": "67", "Content-Type": "application/json", "User-Agent": "OpenAI/JS 4.0.0-beta.4", "X-Stainless-Arch": "unknown", "X-Stainless-Lang": "js", "X-Stainless-OS": "Unknown", "X-Stainless-Package-Version": "4.0.0-beta.4", "X-Stainless-Runtime": "unknown", "X-Stainless-Runtime-Version": "unknown"}

 LOG  OpenAI:DEBUG:response 404 https://api.openai.com/v1/completions/ 
{"alt-svc": "h3=\":443\"; ma=86400", "cf-cache-status": "DYNAMIC", "cf-ray": "7e76b784bf5abc79-HNL", "content-encoding": "br", "content-type": "application/json; charset=utf-8", "date": "Sun, 16 Jul 2023 02:11:51 GMT", "server": "cloudflare", "strict-transport-security": "max-age=15724800; includeSubDomains", "vary": "Origin", "x-request-id": "ab048a808995968bd0ffc3d382a343b6"} undefined

# In node
OpenAI:DEBUG:request https://api.openai.com/v1/completions {
  method: 'post',
  path: '/completions',
  body: { prompt: 'Say this is a test', model: 'text-davinci-003' },
  stream: false
} {
  'Content-Length': '67',
  Accept: 'application/json',
  'Content-Type': 'application/json',
  'User-Agent': 'OpenAI/JS 4.0.0-beta.4',
  'X-Stainless-Lang': 'js',
  'X-Stainless-Package-Version': '4.0.0-beta.4',
  'X-Stainless-OS': 'MacOS',
  'X-Stainless-Arch': 'arm64',
  'X-Stainless-Runtime': 'node',
  'X-Stainless-Runtime-Version': 'v20.4.0',
  Authorization: 'Bearer KEY'
}
OpenAI:DEBUG:response 200 https://api.openai.com/v1/completions {
  'access-control-allow-origin': '*',
  'alt-svc': 'h3=":443"; ma=86400',
  'cache-control': 'no-cache, must-revalidate',
  'cf-cache-status': 'DYNAMIC',
  'cf-ray': '7e76be379a1df4c4-HNL',
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 16 Jul 2023 02:16:26 GMT',
  'openai-model': 'text-davinci-003',
  'openai-organization': 'user-7xl7qvwhwytyzbntikxlr1rt',
  'openai-processing-ms': '436',
  'openai-version': '2020-10-01',
  server: 'cloudflare',
  'strict-transport-security': 'max-age=15724800; includeSubDomains',
  'transfer-encoding': 'chunked',
  'x-ratelimit-limit-requests': '3000',
  'x-ratelimit-limit-tokens': '250000',
  'x-ratelimit-remaining-requests': '2999',
  'x-ratelimit-remaining-tokens': '249983',
  'x-ratelimit-reset-requests': '20ms',
  'x-ratelimit-reset-tokens': '3ms',
  'x-request-id': '87ae3b32149c02bc73d209309d8ef16e'
} {
  id: 'cmpl-7clb7ooA2bLuTFrycZc1JaLKLr6jE',
  object: 'text_completion',
  created: 1689473785,
  model: 'text-davinci-003',
  choices: [
    {
      text: '\n\nThis is indeed a test.',
      index: 0,
      logprobs: null,
      finish_reason: 'stop'
    }
  ],
  usage: { prompt_tokens: 5, completion_tokens: 8, total_tokens: 13 }
}
```

### To Reproduce

```
async function debug() {

    try {
        const client = new OpenAI({
            apiKey: process.env['OPENAI_API_KEY']
        })
        console.log(client.baseURL)
        // Non-streaming:
        const result = await client.completions.create({
            prompt: 'Say this is a test',
            model: 'text-davinci-003',
        },
        );
        console.log(result.choices[0]!.text);
    }
    catch (e) {
        console.log(e.stack)
    }
}
```

### OS

macOS

### Node version

Node v16.x

### Library version

v4b4

**Comment by vanjaoljaca** [comment]
I tried to use the bad request via localhost cli and it worked fine, so it's not the headers

```
http POST https://api.openai.com/v1/completions \
  Accept:application/json \
  Content-Type:application/json \
  User-Agent:"OpenAI/JS 4.0.0-beta.4" \
  X-Stainless-Lang:js \
  X-Stainless-Package-Version:4.0.0-beta.4 \
  X-Stainless-OS:Unknown \
  X-Stainless-Arch:unknown \
  X-Stainless-Runtime:unknown \
  X-Stainless-Runtime-Version:unknown \
  Authorization:"Bearer KEY" \
  model="text-davinci-003" prompt="Say this is a test"

HTTP/1.1 200 OK
...
```

**Comment by vanjaoljaca** [comment]
Maybe related https://github.com/openai/openai-python/issues/263
Less likely to be related https://community.openai.com/t/gpt-4-problem-invalid-url-post-v1-completions/128857/12

**Comment by rattrayalex** [comment]
Interesting. Thank you for the report @vanjaoljaca . Are you using the same API Key in all environments? What kind of iOS device is being used, and where is it located?

**Comment by schnerd** [comment]
I looked up the request ID in the response headers you shared, looks like the error happened because of a trailing slash on completions e.g. `POST /v1/completions/` instead of `POST /v1/completions`

I tried the exact "Code to reproduce" and it worked for me in Node. So maybe it has to do with the settings you are using to instantiate the client in the react-native code?

Also, maybe you already know this but you should not be putting your OpenAI API key into the client code for an app that is distributed to anyone else, as it's not secure. Learn more: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Comment by jedwards1211** [comment]
Here's the issue: https://github.com/facebook/react-native/issues/24428

**Comment by rattrayalex** [comment]
@vanjaoljaca it looks like React Native has a buggy `URL.toString()` implementation, which causes this bug. 

React Native [says they may not fix this, and recommends](https://github.com/facebook/react-native/issues/24428#issuecomment-634730129) using this polyfill: https://github.com/charpeni/react-native-url-polyfill

We also tested this with https://github.com/acostalima/react-native-polyfill-globals which worked.

Does this help?

**Comment by vanjaoljaca** [comment]
Thanks everyone for the quick responses. I fixed my issue by moving the OAI calls out of RN & into a service. I don't mind leaking the keys because its only for testing, but long term it makes sense in a service.

Is it likely that eventually OAI will support some sort of single use key vending for clients, or should we plan to be only calling OAI apis from our services long term?

**Comment by rattrayalex** [comment]
@vanjaoljaca great to hear!

In general, you should plan to call OpenAI APIs only from your backend.

In particular, we don't plan to add built-in support for React Native.

**Comment by SE-Umee** [comment]
`const response = await fetch(
        'https://api.openai.com/v1/chat/completions',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${OPENAI_API_KEY}`,
          },
          body: JSON.stringify({
            model: 'gpt-4',
            messages: [
              {role: 'system', content: 'You are a helpful assistant.'},
              {role: 'user', content: userMessage},
            ],
          }),
        },
      );`
      
      I'm tried to use the above function but I get  **Error: [Error: HTTP error! status: 404]**
      
      how to fix it please

**Comment by RobertCraigie** [comment]
please ask for support with your code on the community forum.

**Comment by vanjaoljaca** [comment]
@SE-Umee you can't call from react-native. you have to host in a webservice and call via your webservice.

**Comment by depombo** [comment]
@SE-Umee I ended up building an openai react native client that supports file upload and chat completion streaming without polyfills by using [react-native-sse](https://github.com/binaryminds/react-native-sse#readme) and the [expo file system](https://docs.expo.dev/versions/latest/sdk/filesystem/). The library uses the official node sdk everywhere else along with the same types and API

https://github.com/backmesh/openai-react-native
