### ISSUE TITLE
Use createCompletion() with fine-tune models

### ISSUE THREAD

**Issue by npaez** [openai/openai-node#2]
Currently `createCompletion()` function requires an engine id as first parameter. When I pass the model id instead i get 404 error which makes sense if is waiting an engine.
Is it posible to use a fine tune model?

**Comment by Tohaker** [comment]
How did you solve this, I'm having the same issue

**Comment by npaez** [comment]
I read the source code and there's a function for this feature: `createCompletionFromModel()`.
