### ISSUE TITLE
Missing Async in most functions

### ISSUE THREAD

**Issue by levidehaan** [openai/openai-node#20]
All of your examples use await, however you did not set any of your functions as async (at least in version 3.0.0).

so instead of :
const val = await blahblah()

you have to do :
const val = blahblah();
val.then((data)=>{
console.log(data);
});

is this intentional?

**Comment by schnerd** [comment]
> you did not set any of your functions as async

In javascript, you can await functions that are not explicitly marked as `async`, they just need to return a promise.

The methods exposed by this package do support `await`. If you have found a case where it doesn't work, please open a separate issue with detailed instructions on how to replicate.
