### ISSUE TITLE
Function Calling Response Returns "{" for arguments

### ISSUE THREAD

**Issue by CyberPunkMetalHead** [openai/openai-node#200]
### Describe the bug

It appears that the function calling response is quite unreliable, as it does not return a complete arguments object.
Here is an example of the JSON Schema for a function that I'm trying to get it to call.

```typescript
export const getCoinPrice: ChatCompletionFunctions = {
  name: "get_coin_price",
  description: "Get the current price for any cryptocurrency",
  parameters: {
    type: "object",
    properties: {
      coin_symbol: {
        type: "string",
        description: "The symbol of the asset to get the price for. Eg: BTC",
      },
    },
    required: ["coin_symbol"],
  },
};

```

This is then passed to the chat request like so:

```typescript
 const chatRequest: CreateChatCompletionRequest = {
      model: "gpt-3.5-turbo-0613",
      temperature: 0.5,
      n: 1,
      stop: "\n",
      messages: messages,
      function_call: "auto",
      functions: functions,
    };

    const response = await this.openai.createChatCompletion(chatRequest);
```

The Contents of the message response will look like so:
```typescript
{"role":"user","content":"what is the current price of bitcoin"},{"role":"assistant","content":"","function_call":{"name":"get_coin_price","arguments":"{"}
```

Arguments should be of type object but I couldn't get it to return anything else than "{"

### To Reproduce

1. Add Function Calling to your chat request
2. Create a short JSON schema for your function and print the response including the function_call

### OS

Windows 11

### Node version

Node v18.6.0

### Library version

openai v3.3.0

**Comment by rattrayalex** [comment]
Thanks for the report; unfortunately, this is expected to occur some percentage of the time. Per [the documentation](https://platform.openai.com/docs/guides/gpt/function-calling#:~:text=note%3A%20the%20model%20may%20generate%20invalid%20JSON%20or%20hallucinate%20parameters):

> note: the model may generate invalid JSON or hallucinate parameters

If the arguments provided are invalid JSON or don't conform to your schema, you may need to re-request.

**Comment by CyberPunkMetalHead** [comment]
Thanks @rattrayalex. It's been happening consistently with every call for the last two days. Is this also expected?

**Comment by athyuttamre** [comment]
This is happening because you are passing `"stop": "\n"`. The model generates a new line character after the first curly brace and thus stops sampling afterwards. Try removing that stop token or setting it to a different value.

```
curl --request POST \
  --url https://api.openai.com/v1/chat/completions \
  --header 'Authorization: Bearer YOUR_API_KEY' \
  --header 'Content-Type: application/json' \
  --data '{
	"model": "gpt-3.5-turbo-0613",
	"messages": [
		{
			"role": "user",
			"content": "what is the current price of bitcoin"
		}
	],
	"functions": [
		{
			"name": "get_coin_price",
			"description": "Get the current price for any cryptocurrency",
			"parameters": {
				"type": "object",
				"properties": {
					"coin_symbol": {
						"type": "string",
						"description": "The symbol of the asset to get the price for. Eg: BTC"
					}
				},
				"required": [
					"coin_symbol"
				]
			}
		}
	],
	"function_call": "auto",
	"temperature": 0.5,
	"n": 1
}'
```

```
{
	"id": "chatcmpl-7dGZ00dZLfE9JLO5qKXgvRMfqWm46",
	"object": "chat.completion",
	"created": 1689592818,
	"model": "gpt-3.5-turbo-0613",
	"choices": [
		{
			"index": 0,
			"message": {
				"role": "assistant",
				"content": null,
				"function_call": {
					"name": "get_coin_price",
					"arguments": "{\n  \"coin_symbol\": \"BTC\"\n}"
				}
			},
			"finish_reason": "function_call"
		}
	],
	"usage": {
		"prompt_tokens": 72,
		"completion_tokens": 17,
		"total_tokens": 89
	}
}
```
