### ISSUE TITLE
Library is not compatible with nextjs

### ISSUE THREAD

**Issue by jeremielenoir** [openai/openai-node#203]
### Describe the bug

I found several issue when i try to build a nextjs application using openai-node : 
- Typescript compiler option isolatedModules is set to true => Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.ts(1269)
- use of "#" to define a private property not working

### To Reproduce

create a sample application with : npx create-next-app@latest
install openai-node
write a simple chatCompletion in a page component
Launch "npm run build"

You will see errors on "checking validity of types" step.

### OS

macOs

### Node version

16.8.x and more

### Library version

4.00 and more

**Comment by RobertCraigie** [comment]
Hey @jeremielenoir, I can't reproduce the issue you're seeing.

My steps to reproduce:
- `npx create-next-app@latest`, using all default options
- `npm install --save openai@v4.0.0-beta.6`
- Create these files

```ts
// pages/bar.tsx
import { OpenAI } from 'openai';
import { useState } from 'react';

const client = new OpenAI();

export default function Home() {
  const [text, setText] = useState('Foo');

  client.completions
    .create({ model: 'text-ada-001', prompt: 'foo' })
    .then((completion) => setText(completion.choices[0].text ?? ''));

  return <div>${text}</div>;
}
```
```ts
// pages/api/hello.ts
import type { NextApiRequest, NextApiResponse } from 'next';
import { OpenAI } from 'openai';

type Data = {
  name: string;
};

export default async function handler(req: NextApiRequest, res: NextApiResponse<Data>) {
  const client = new OpenAI();
  await client.chat.completions.create({ model: 'gpt-4', messages: [] });

  res.status(200).json({ name: 'John Doe' });
}
```

Then run `npm run build`, this passes for me:
```
> next build

- info Linting and checking validity of types
- info Creating an optimized production build
- info Compiled successfully
- info Collecting page data
- info Generating static pages (4/4)
- info Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ○ /                                      4.94 kB        79.8 kB
├   └ css/be3bca439d8cf5c9.css             1.74 kB
├   /_app                                  0 B            74.9 kB
├ ○ /404                                   182 B            75 kB
├ λ /api/hello                             0 B            74.9 kB
└ ○ /bar                                   15.1 kB          90 kB
+ First Load JS shared by all              75.6 kB
  ├ chunks/framework-7a7e500878b44665.js   45.2 kB
  ├ chunks/main-92011a1a7f336a6f.js        28.5 kB
  ├ chunks/pages/_app-5fbdfbcdfb555d2f.js  296 B
  ├ chunks/webpack-ee7e63bc15b31913.js     815 B
  └ css/876d048b5dab7c28.css               706 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

Is there anything I'm missing?

**Comment by jeremielenoir** [comment]
Hello @RobertCraigie, i apologize for taking your time. Theses issues was present because my ts config was wrong with moduleResolution parameter. I follow your steps, and it worked !!!!!
Thanks a lot.

**Comment by RobertCraigie** [comment]
No worries! Glad I could help :)

**Comment by rattrayalex** [comment]
What was the moduleResolution parameter you were using?

**Comment by Dzheky** [comment]
Also interested how you fixed this, getting the same issue

**Comment by Dzheky** [comment]
OS
macOs

Node version
16.8.x and more

Library version
4.00 and more

Here is the error I am getting:
```
./node_modules/openai/src/index.ts:204:3
Type error: Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.

  202 |   export import fileFromPath = Uploads.fileFromPath;
  203 | 
> 204 |   export import RequestOptions = Core.RequestOptions;
      |   ^
  205 | 
  206 |   export import Page = Pagination.Page;
  207 |   export import PageResponse = Pagination.PageResponse;
```

And here is my tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "baseUrl": "./",
    "lib": [
      "dom",
      "es2020",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "@/*": [
        "./*"
      ]
    },
    "plugins": [
      {
        "name": "next"
      }
    ],
    "isolatedModules": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by jeremielenoir** [comment]
"./node_modules/openai/src/index.ts" is the reason, your builder try to compile openai typescript with your own configuration, you need to import openai as a module, not directly by typescript filesource.

**Comment by Dzheky** [comment]
Thank you, my IDE auto imported types with '/src/' and after removing them it worked.

**Comment by alexandr2110pro** [comment]
Hey 
```
OSX
node v20.11.1

"openai": "^4.40.2",
"next": "14.1.4",
"@nx/next": "18.2.4",
"typescript": "~5.4.4",
```


```ts
import { OpenAI } from 'openai';
```
```
> nx run tyde-web-app:build

> next build

   ▲ Next.js 14.1.4

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
Failed to compile.

../../../node_modules/.pnpm/openai@4.40.2/node_modules/openai/src/index.ts:222:3
Type error: Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.

  220 |
  221 | export namespace OpenAI {
> 222 |   export import RequestOptions = Core.RequestOptions;
      |   ^
  223 |
  224 |   export import Page = Pagination.Page;
  225 |   export import PageResponse = Pagination.PageResponse;
Warning: command "next build" exited with non-zero status code
```

**Comment by imtiger** [comment]
> Hey
> 
> ```
> OSX
> node v20.11.1
> 
> "openai": "^4.40.2",
> "next": "14.1.4",
> "@nx/next": "18.2.4",
> "typescript": "~5.4.4",
> ```
> 
> ```ts
> import { OpenAI } from 'openai';
> ```
> 
> ```
> > nx run tyde-web-app:build
> 
> > next build
> 
>    ▲ Next.js 14.1.4
> 
>    Creating an optimized production build ...
>  ✓ Compiled successfully
>    Skipping linting
>    Checking validity of types ...
> Failed to compile.
> 
> ../../../node_modules/.pnpm/openai@4.40.2/node_modules/openai/src/index.ts:222:3
> Type error: Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.
> 
>   220 |
>   221 | export namespace OpenAI {
> > 222 |   export import RequestOptions = Core.RequestOptions;
>       |   ^
>   223 |
>   224 |   export import Page = Pagination.Page;
>   225 |   export import PageResponse = Pagination.PageResponse;
> Warning: command "next build" exited with non-zero status code
> ```

have you solved this problem? I also have same error.

**Comment by imtiger** [comment]
> > Hey
> > ```
> > OSX
> > node v20.11.1
> > 
> > "openai": "^4.40.2",
> > "next": "14.1.4",
> > "@nx/next": "18.2.4",
> > "typescript": "~5.4.4",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > import { OpenAI } from 'openai';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > > nx run tyde-web-app:build
> > 
> > > next build
> > 
> >    ▲ Next.js 14.1.4
> > 
> >    Creating an optimized production build ...
> >  ✓ Compiled successfully
> >    Skipping linting
> >    Checking validity of types ...
> > Failed to compile.
> > 
> > ../../../node_modules/.pnpm/openai@4.40.2/node_modules/openai/src/index.ts:222:3
> > Type error: Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.
> > 
> >   220 |
> >   221 | export namespace OpenAI {
> > > 222 |   export import RequestOptions = Core.RequestOptions;
> >       |   ^
> >   223 |
> >   224 |   export import Page = Pagination.Page;
> >   225 |   export import PageResponse = Pagination.PageResponse;
> > Warning: command "next build" exited with non-zero status code
> > ```
> 
> have you solved this problem? I also have same error.

I have solved this problem ,because  the below import 
`import { ChatCompletionMessageParam } from "openai/src/resources/chat/completions";
`
webstorm auto import from the openai/src dir .

I changed to import ChatCompletionMessageParam = Chat.ChatCompletionMessageParam;
it works .

**Comment by rattrayalex** [comment]
You might try adjusting the `moduleResolution` property in your `tsconfig.json`?

**Comment by djam90** [comment]
It was the importing from "src" due to Webstorm auto import that was the issue for me too. Fixed by changing:

```
import { ToFileInput } from 'openai/src/uploads';
```

to

```
import { ToFileInput } from 'openai/uploads';
```

Hope this helps someone

**Comment by sergey-frey** [comment]
Also, you can import `ChatCompletionMessageParam` from:
```ts
import { ChatCompletionMessageParam } from "openai/resources/chat/completions"; 
```
