### ISSUE TITLE
Possibility to use action :  "variant" and variant_purpose :  "comparison_implicit"

### ISSUE THREAD

**Issue by Jeromearsene** [openai/openai-node#204]
### Describe the feature or improvement you're requesting

I try to regenerate response, like in official Chat.
If I use regenerate in Chat, I can see this in request:

```json
{
    "action": "variant",
    "messages": [
        {
            "id": "a4c9ab9a-99a0-4ea7-aa69-5e80c0b50120",
            "author": {
                "role": "user",
                "metadata": {}
            },
            "create_time": 1689775584.464652,
            "content": {
                "content_type": "text",
                "parts": [
                    "Ceci est un test"
                ]
            },
            "status": "finished_successfully",
            "weight": 1,
            "metadata": {
                "timestamp_": "absolute"
            },
            "recipient": "all"
        }
    ],
    "conversation_id": "72704a41-7444-4b66-b592-ec2eaa225570",
    "parent_message_id": "66b4468a-4f56-4f8b-aa7e-78446b6540fc",
    "model": "text-davinci-002-render-sha",
    "timezone_offset_min": -120,
    "variant_purpose": "comparison_implicit",
    "history_and_training_disabled": false,
    "arkose_token": null
}
```

2 fields are interesting:
- variant_purpose
- action

It is currently not possible to use them in lib. I try to ask to ChatGTP himself. He suggest me this:

```javascript
{
...,
  action: {
      action_type: 'variant',
      variant_purpose: 'comparison_implicit',
    },
}
```

But if I precise my current openai version, he respond me this:

> I apologize for any confusion. You are correct that in version 4.0.0-beta.6 of the OpenAI SDK, the "action" parameter is not available in the `chat.completions.create` function. I apologize for the misinformation.
> 
> Currently, the "action" and "variant_purpose" parameters are not directly supported in the `chat.completions.create` function. These parameters are specific to the GPT-3 chat interface on the OpenAI website.
> 
> If you want to control the generation of the response with similar parameters, you can use the available parameters in the SDK such as "temperature" and "max_tokens" to adjust the randomness and length of the generated response.
> 
> You can also modify the content of the prompt to influence the generation of the response by adding specific instructions or constraints. Experiment with different prompts to achieve the desired results.
> 
> I encourage you to refer to the official OpenAI SDK documentation for up-to-date information on the available options: https://github.com/openai/openai-node

This feature can be very useful to use. Actually, I renew manually the request.

### Additional context

**openai** version: `4.0.0-beta.6`

**Comment by rattrayalex** [comment]
Thank you for the suggestion! We'll pass this request on to our API team. It may help if you can share more about why these features would be useful to you.

**Comment by rattrayalex** [comment]
Closing this as it's an API feature request rather than a client library feature request. If you're still interested in this functionality, please post it in [community.openai.com](https://community.openai.com)
