### ISSUE TITLE
Open AI API 401 error code: incorrect api key

### ISSUE THREAD

**Issue by Mindsurfer7** [openai/openai-node#206]
### bug is only in browsers.

Here is my code with correct request structure. If i post it by Postman App then 200 code and response from GPT, if i post from localhost:3000, then the error(

cache of the browser i did clean and also tried in other browser, the same(

![image](https://github.com/openai/openai-node/assets/99701217/b79f401c-1430-48ee-a7d0-00bff06086e9)

### To Reproduce

firstly from redux state thubk function takes the text with structure {role: string, content: string} and pushes in array with the 1st element of system message. then axios post

### OS

Windows  10

### Node version

17 4 0

### Library version

-

**Comment by rattrayalex** [comment]
Based on your screenshot, this doesn't look like a bug with this library. For further help, try asking in community.openapi.com 

Note also that OpenAI does not recommend using your API Key in a browser: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety
