### ISSUE TITLE
Request failed with status code 404 using gpt-4-32k

### ISSUE THREAD

**Issue by ArkasDev** [openai/openai-node#207]
### Describe the bug

I would like to use the gpt-4-32k model to create a chat completion, but I always receive the following error message. 

> Request failed with status code 404

Is this model not supported? I read in the api documentation that it should work, right?

### To Reproduce

1. createChatCompletion using the gpt-4-32k model

### Code snippets

```
this.openai.createChatCompletion({
  model: 'gpt-4-32k',
  ..
});
```

### OS

macOS

### Node version

nodejs16.x

### Library version

3.3.3

**Comment by rattrayalex** [comment]
gpt-4-32k is not yet generally available.
