### ISSUE TITLE
Status 400 - Axios Bug

### ISSUE THREAD

**Issue by OldManMeta** [openai/openai-node#209]
### Describe the bug

Trying to run a simple test completion using the documentation, and the solution fails with an Axios bug.

I have replicated my settings using Postman and can verify that data is returned as expected.

The error in code shows me no obvious details of what is causing the error in your library.

### To Reproduce

Create a new Node project and use the details as shown here:
https://platform.openai.com/docs/api-reference/chat/create?lang=node.js

Run it and you will have a 400 response returned.

### Code snippets

```JavaScript
const result = await openai.createChatCompletion({
            model: "gpt-3.5-turbo",
            messages: [
                {role: "system", content: "You are a helpful assistant"}, 
                {role: "user", content: {promptValue}}
            ]
        }, { responseType: 'stream' });
```

### OS

Windows 11

### Node version

Node 18.12.1

### Library version

v3.3.0

**Comment by rattrayalex** [comment]
@OldManMeta please try our upcoming [v4](https://github.com/openai/openai-node/discussions/182) of this library, which replaces axios with fetch, and adds support for Streaming.

**Comment by OldManMeta** [comment]
@rattrayalex thanks for letting me know. I've just built my own library with Fetch and streaming in the last hour.

I can't have these types of issues in production, so while I appreciate you and the teams work on this, stability is needed above features and certainly a big message on the front page indicating this would be really appreciated.
