### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by OldManMeta** [openai/openai-node#212]
### Describe the bug

Please look at the response information in the official documentation.

https://platform.openai.com/docs/api-reference/chat/create?lang=node.js

The createChatCompletion response looks nothing like this at all.

```
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}

```

### To Reproduce

Go to the docs and read it.

https://platform.openai.com/docs/api-reference/chat/create?lang=node.js

### Code snippets

```JavaScript
N/A
```

### OS

Windows 11

### Node version

Node 18.12.1

### Library version

v3.3.0

**Comment by rattrayalex** [comment]
That looks like a correct response shape to me. Can you share the response shape from the API you are expecting?

**Comment by OldManMeta** [comment]
I was expecting that as well - but this is what I got:

```
data: {"id":"chatcmpl-7j8Vqwdr7kvXrokmonmw7U7Bay3vL","object":"chat.completion.chunk","created":1690991838,"model":"gpt-3.5-turbo-0613","choices":[{"index":0,"delta":{"content":" geographic"},"finish_reason":null}]}

data: {"id":"chatcmpl-7j8Vqwdr7kvXrokmonmw7U7Bay3vL","object":"chat.completion.chunk","created":1690991838,"model":"gpt-3.5-turbo-0613","choices":[{"index":0,"delta":{"content":"."},"finish_reason":null}]}
```


choices[0].delta.content

documentation shows choices[0].text

**Comment by rattrayalex** [comment]
Ah, yes. Streaming changes the shape of the response. This is documented in [the OpenAPI spec](https://github.com/openai/openai-openapi/blob/master/openapi.yaml) but it appears not to be in the docs; I'll raise that with the team. 

If you use the [v4](https://github.com/openai/openai-node/discussions/182) of this SDK, the TypeScript types will show you the accurate shapes for streaming and non-streaming scenarios.

**Comment by athyuttamre** [comment]
We're updating the API reference soon to describe the response shapes more accurately. Thanks for raising!

**Comment by OldManMeta** [comment]
Thanks all - I'm going to implement your V4 today, and keep my own as a backup. If there is anything specific you want to test, just shout out. Cheers
