### ISSUE TITLE
(v4-B7) Configuration is not a constructor

### ISSUE THREAD

**Issue by OldManMeta** [openai/openai-node#213]
### Describe the bug

v4 Beta 7 (v4-B7)

This is not a bug, but a breaking change that will cause upgrades to break.

(Would you prefer me to add these as Suggestions instead of bugs?)

Using existing configuration object returns:
TypeError: Configuration is not a constructor

### To Reproduce

Create a new Node.js app.

Create a configuration based initializer and run the call to OpenAI

### Code snippets

```JavaScript
const { Configuration, OpenAIApi } = require("openai");
require('dotenv').config();

const configuration = new Configuration({
    apiKey: process.env.OPEN_AI_KEY,
});

const openai = new OpenAIApi(configuration);

```
```


### OS

Windows 11

### Node version

Node 18.12.1

### Library version

v4.0.0-beta.7

**Comment by RobertCraigie** [comment]
This is an intentional breaking change, see the [migration guide](https://github.com/openai/openai-node/discussions/182#:~:text=4.0.0%2Dbeta.7-,Migration%20guide,-There%20are%20changes) in the [v4 discussion](https://github.com/openai/openai-node/discussions/182#discussion-5308937) for more details.

**Comment by OldManMeta** [comment]
@RobertCraigie thanks so much for the link to that page. I see now I should add issues there - will do ;-) Thanks

**Comment by ponponponponponponponponponponponponpon** [comment]
did you ever find the fix for this? i see it was intentional but even in the other thread, i couldn't find your issue relating to this specifically

**Comment by swervendy** [comment]
> This is an intentional breaking change, see the [migration guide](https://github.com/openai/openai-node/discussions/182#:~:text=4.0.0%2Dbeta.7-,Migration%20guide,-There%20are%20changes) in the [v4 discussion](https://github.com/openai/openai-node/discussions/182#discussion-5308937) for more details.

this work
