### ISSUE TITLE
(v4-B7) ChatCompletion object missing streaming properties

### ISSUE THREAD

**Issue by OldManMeta** [openai/openai-node#214]
### Describe the bug

This is only an issue when stream is set to true in params.

```
const stream: OpenAI.Chat.ChatCompletion = await openai.chat.completions.create(params);

Type 'Stream<ChatCompletionChunk> & { responseHeaders: Headers; }' is missing the following properties from type 'ChatCompletion': id, choices, created, model, objectts(2739)
const stream: OpenAI.Chat.Completions.ChatCompletion

```

### To Reproduce

Create a new TS Node Server
Implement the doc examples for V4 explicitly declaring types on all variables.

### OS

Windows 11

### Node version

Node 18.12.1

### Library version

v4.0.0-beta.7

**Comment by RobertCraigie** [comment]
This is intended behaviour, if you are streaming the response then you won't be able to immediately access the chat completion properties.

Here's how you should update your code:
```ts
import { ChatCompletionChunk } from 'openai/resources/chat';
import { Stream } from 'openai/streaming';

const stream: Stream<ChatCompletionChunk> = await openai.chat.completions.create(params);

for await (const chunk of stream) {
  chunk // ChatCompletionChunk
  chunk.choices[0]?.delta?.content // string | null | undefined
}
```
