### ISSUE TITLE
v4 SDK - missing "node_modules/openai/dist/index.mjs"?

### ISSUE THREAD

**Issue by CRREO** [openai/openai-node#216]
### Describe the bug

Trying to work out the new v4 beta SDK (love the new features!) - but constantly get an error during initialization for "missing node_modules/openai/dist/index.mjs"
I can't even see this file anywhere in the v4 SDK
Am I not doing things correctly? Any pointers very welcome. 

### To Reproduce

install new v4 SDK - from a zip file download

### OS

macOS

### Node version

Node 18.17.0

### Library version

openai SDK v4 beta

**Comment by rattrayalex** [comment]
Ah, it's not intended for use via zip download – can you `npm install --save openai@4.0.0-beta.8`? 

Is there a reason you want to download via zip?

If that's a requirement, you should be able to install it locally with `npm install; npm build; cd dist; npm link` or an equivalent.

**Comment by CRREO** [comment]
🙏 Thank you. This worked.
