### ISSUE TITLE
Package size in v4 is much larger than v3 (no tree shaking)

### ISSUE THREAD

**Issue by utajum** [openai/openai-node#218]
### Describe the bug

How to import only the completions functionality?

### To Reproduce

Import any function and observe file size

### OS

Linux

### Node version

16

### Library version

4.0.0-beta.11

**Comment by rattrayalex** [comment]
@utajum can you share before/after numbers of your final bundles, and your deployment situation? 

From the testing we've done with NextJS, upgrading from v3.3.0 to v4.0.0-beta-11 resulted in a >50% drop in package bundle size, from 46kb to 22kb.

The file size you see on npm includes things like `.d.ts` files and sourcemaps, which help with developer experience but should not hurt your deploys.
