### ISSUE TITLE
Moderation: missing new categories

### ISSUE THREAD

**Issue by devidw** [openai/openai-node#223]
### Describe the bug

Typing does not include the latest category additions as listed in the [docs](https://platform.openai.com/docs/guides/moderation/overview) such as:

```ts
    | "self-harm/intent"
    | "self-harm/instructions"
    | "harassment"
    | "harassment/threatening"
```

See https://github.com/openai/openai-node/blob/3ec43ee790a2eb6a0ccdd5f25faa23251b0f9b8e/src/resources/moderations.ts#L41-L76

### To Reproduce

```ts
import oai from "openai"

const someFlag: keyof oai.Moderation.Categories = "harassment" // type error
```

### OS

macOS

### Node version

Node v18.16.0

### Library version

openai 4.0.0

**Comment by RobertCraigie** [comment]
Thanks for the report! We'll have this updated shortly.

**Comment by RobertCraigie** [comment]
This has been updated in v4.0.1!
