### ISSUE TITLE
Temperature=2 randomly throws error

### ISSUE THREAD

**Issue by caesarisme** [openai/openai-node#224]
### Describe the bug

When I set temperature=2, it throws error for 90% of times

request body:

`data: '{"model":"gpt-3.5-turbo","n":1,"messages":[{"role":"system","content":"You are an ai assistant in car marketplace website. \\n\\nHere are some instructions:\\n\\n1. If user asks to contact with human or callback, you should ask for his name and phone number or email. And reply that someone will call him as soon as possible\\n\\nYou are an ai assistant"},{"role":"user","content":"123"}],"functions":[{"name":"showImage","description":"You should use this function to display image to user","parameters":{"type":"object","properties":{"url":{"type":"string","description":"Url of the image you want to show"}},"required":["url"]}}],"temperature":2,"max_tokens":295,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"stop":[]}'`

error message:
```
error: {
      message: 'The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID bb87b2d4944c548a8e12fada9d306040 in your email.)',
      type: 'server_error',
      param: null,
      code: null
    }
```

### To Reproduce

1. Call `.createChatCompletion` method with the parameters from issue description
2. See the error

### OS

linux

### Node version

Node v16.x

### Library version

openai v3.3.0

**Comment by rattrayalex** [comment]
Thanks for reporting @caesarisme ! This sounds like a possible bug with the backend API; please report it here: https://community.openai.com/c/api/bugs/30

This repo is intended for bugs with the Node SDK.
