### ISSUE TITLE
Does v4.0.0 support Node16?

### ISSUE THREAD

**Issue by Tzesar** [openai/openai-node#225]
### Describe the bug

Hello, nice library!
In the [README Requirements section](https://github.com/openai/openai-node/tree/v4.0.0#requirements) of v4.0.0 we can see that Node16 LTS is supported but the package.json file requires `"@types/node": "^18.11.18"` (link [here](https://github.com/openai/openai-node/blob/3ec43ee790a2eb6a0ccdd5f25faa23251b0f9b8e/package.json#L75)).

I haven't found problems running v4.0.0 in Node v16.20.1 so far but I'm wondering which one is correct, the requirements or the package.json file.

### To Reproduce

I haven't found problems running v4.0.0 in Node v16.20.1.

### OS

macOS

### Node version

Node v16.20.1

### Library version

openai 4.0.0

**Comment by rattrayalex** [comment]
Yes, Node 16 is supported! 

We'll look into correcting the `@types/node` – was that causing issues for you? If so, can you share what they were?
