### ISSUE TITLE
V4.0.1 TS Example Error

### ISSUE THREAD

**Issue by MarleneJiang** [openai/openai-node#229]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

不能将类型“ChatCompletion | Stream<ChatCompletionChunk>”分配给类型“ChatCompletion”。
  类型“Stream<ChatCompletionChunk>”缺少类型“ChatCompletion”中的以下属性: id, choices, created, model, object
![image](https://github.com/openai/openai-node/assets/49270362/bec0bff3-b3b0-4b42-b824-cb807944f2f1)

### To Reproduce

1. find readme example
2. use it with ts
3. find error in vsc

### Code snippets

```JavaScript
import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: 'my api key', // defaults to process.env["OPENAI_API_KEY"]
});

async function main() {
  const params: OpenAI.Chat.CompletionCreateParams = {
    messages: [{ role: 'user', content: 'Say this is a test' }],
    model: 'gpt-3.5-turbo',
  };
  const completion:OpenAI.Chat.Completions.ChatCompletion = await openai.chat.completions.create(params);
}

main();
```

### OS

win10

### Node version

node 18

### Library version

v4.0.1

**Comment by MarleneJiang** [comment]
This is a ts issue, but clearly using assertions here is not appropriate, is there a better way to solve it ？

**Comment by MarleneJiang** [comment]
Well, maybe i need slippers

**Comment by rattrayalex** [comment]
Thank you for reporting, we hope to improve this experience in the next release.
