### ISSUE TITLE
Missing status, headers in streaming response API

### ISSUE THREAD

**Issue by AaronFriel** [openai/openai-node#233]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

When using the streaming API, especially when debugging Azure OpenAI's support, it's helpful to be able to inspect the response status and headers. The Node 4 library forces users into a choice: streaming API with better performance, or the non-streaming API and a full response object.

This isn't ideal for debugging issues with the endpoints. 

### Additional context

See: https://github.com/openai/openai-node/discussions/182#discussioncomment-6695436

**Comment by rattrayalex** [comment]
I think you're looking for `.withResponse`, eg:

```ts
const { data: stream, response } = await openai.chat.completions.create({
  model: 'gpt-3.5-instant',
  messages: [{ role: 'user', content: 'Say this is a test' }],
  stream: true,
}).withResponse()

console.log(response.headers)

for await (const part of stream) {
  process.stdout.write(part.choices[0]?.delta?.content || '');
}
process.stdout.write('\n');
```

Does that work for you?

**Comment by RobertCraigie** [comment]
Yeah it is a little strange but we think it's pretty elegant, especially as there aren't many other great choices. Our thinking is that this is something you just need to see once in the README and then know how to use, https://github.com/openai/openai-node#accessing-raw-response-data-eg-headers.
