### ISSUE TITLE
Support for buffer data in audio.transcriptions.create

### ISSUE THREAD

**Issue by rgillan** [openai/openai-node#246]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Currently you must pass a fs.ReadStream to the audio.transcriptions.create call.  Rather than:

`  const transcription = await openai.audio.transcriptions.create({
    file: fs.createReadStream("audio.mp3"),
    model: "whisper-1",
  });`

it would be helpful to be able to pass the content as a buffer directly, such as:

`  const transcription = await openai.audio.transcriptions.create({
    content: [buffer],
    encoding: 'flac|mp3|mp4|mpeg|mpga|m4a|ogg|wav|webm',
    model: "whisper-1",
  });`

This would facilitate audio content transfer, not requiring it to exist as a file in the filesystem.

**Comment by rattrayalex** [comment]
This is documented in the [file uploads section of the README](https://github.com/openai/openai-node#file-uploads), in this case:

```ts
import OpenAI, { toFile } from 'openai';

const openai = new OpenAI();

await openai.audio.transcriptions.create({
  file: toFile(Buffer.from('my bytes'), 'audio.mp3'),
  model: 'whisper-1',
});
```

**Comment by rgillan** [comment]
Thank you, wasn't immediately clear from the documentation, cheers

**Comment by rattrayalex** [comment]
Which documentation were you looking at? Maybe we can improve it.

**Comment by rgillan** [comment]
So without digging into the codebase, the landing page/docs here don't cover off the various specific capabilities of the API/module (transcriptions etc.) and we floundered around initially.  Getting the info on specific syntax was more found through a migration document (https://github.com/openai/openai-node/discussions/217) so pulling this through to the documentation would be helpful, as it gives examples of the various calls.  Hope that helps and thanks, Rob

**Comment by rattrayalex** [comment]
Thanks Rob, that is helpful!
