### ISSUE TITLE
Missing types Stream

### ISSUE THREAD

**Issue by bodinsamuel** [openai/openai-node#250]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hey,

the library is not exposing the type `Stream` which is used when specifying the param `stream: true`.
It's mostly alright when using the response directly but when we want to pass the response around in a strongly typed codebase it's a bit cumbersome to write `Awaited<ReturnType<typeof openai.chat.completions.create>>`

I suppose it's more relevant for @ Stainless

### To Reproduce

```ts
export async function aiRewrite(text: string): 
  Promise<Awaited<ReturnType<typeof openai.chat.completions.create>>> {
  const res = await openai.chat.completions.create({ ... });
  return res;
}
```  

### Code snippets

I understood, after I made the fix, that the codebase is generated, but here is what a fix could look like

https://github.com/bodinsamuel/openai-node/compare/master...bodinsamuel-patch-1#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

### OS

macOs

### Node version

18.

### Library version

4.2.0

**Comment by RobertCraigie** [comment]
@bodinsamuel you should be able to import the stream type like so:
```ts
import { Stream } from 'openai/streaming';
```

**Comment by bodinsamuel** [comment]
Ah indeed, it's weird VSCode didn't autocompleted that. Maybe it was desync with the repo. 
Thanks for the fast answer 🙏🏻
