### ISSUE TITLE
Docs say to use stream.controller.abort() but controller is a private property

### ISSUE THREAD

**Issue by javiermrz** [openai/openai-node#251]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Docs say to use `stream.controller.abort()` but controller is a private property of Stream.

**Docs:**
 ```
If you need to cancel a stream, you can break from the loop or call stream.controller.abort().
```
**Library code:**
<img width="626" alt="image" src="https://github.com/openai/openai-node/assets/46677628/0b64b6ec-d118-40bb-847e-dd91debbc103">
<img width="691" alt="image" src="https://github.com/openai/openai-node/assets/46677628/33ee53bb-e919-4a7b-8bdc-13e259ce672b">

### To Reproduce

1. Install the node library.
2. Create a stream with the library. (`import { Stream } from 'openai/streaming';`)
3. Call `stream.controller.abort()`

You will see an IDE error telling you that controller is a private property. This is also reflected in both the interface and the implementation shown in the screenshots.

### OS

macOS

### Node version

v20.1.0

### Library version

openai v4.2.0

**Comment by RobertCraigie** [comment]
Thanks for the bug report, the `controller` property will be made public in the next release!
