### ISSUE TITLE
When streaming response of usage is missing

### ISSUE THREAD

**Issue by albseb511** [openai/openai-node#257]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

This is the response i should be getting where `usage` is part of the response.
```
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "model": "gpt-3.5-turbo-0613",
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}

```
When i am doing streams, i do not get any indicator of usage. either part of it, which i need to calculate, or a way i track it.

Use case:
- we are building a tool, and to calculate costs we are looking at total tokens per resource generated for internal tracking. 

### To Reproduce

1. Make a request for createCompletion
2. use streams
3. check response

### Code snippets

```JavaScript
const res = await openai.chat.completions.create(
            {
                model: model,
                messages,
                max_tokens: tokens,
                temperature: 0.2,
                stream: stream,
            },
            { responseType: stream ? 'stream' : 'json' }
        )
        if (stream) {
            for await (const part of res) {
                let msg = part.choices[0]?.delta?.content || ''
            }
        }
```
```


### OS

mac

### Node version

18.6

### Library version

4

**Comment by albseb511** [comment]
I did browse the community forums, and it seems to be a concern that it is not part of it, i understand when streaming we dont know the output yet. 
I see two ways this can be solved
1. in each streamed chunk, we add a token used, we can calculate total tokens from that
2. have a session id for each response, which can be used to decide total tokens used.

Is there any of 1,2 already existing or other solutions?

Right now, i am just calculating total words, and then making an assumption.

**Comment by rattrayalex** [comment]
Unfortunately, the API does not provide usage information while streaming right now.

Issues related to API limitations should be raised at https://community.openai.com rather than this repo (for example, [this one](https://community.openai.com/t/openai-api-get-usage-tokens-in-response-when-set-stream-true/141866/12)).
