### ISSUE TITLE
Azure API endpoint support with openai ^4.3.0

### ISSUE THREAD

**Issue by AntiMoron** [openai/openai-node#258]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I just ran into a 404 `Resource not found` error.

![image](https://github.com/openai/openai-node/assets/6587734/88d0b82d-a02f-490c-9aa8-4835f192c2ec)

**Comment by AntiMoron** [comment]
Here's my proposal:

1. Add a type when create a `OpenAI` instance.

```typescript

import OpenAI from "openai";

const apiVersion = '2022-12-01';
const apiKey = '********';

const openai = new OpenAI({
  apiKey,
  azureEndpoint: "https://*****.openai.azure.com", // Add this,
  type: 'azure', // Add this, type?: 'azure' | 'openai' 
  apiVersion, // Add this, apiVersion?: string;
});

```

2. when building url in APIPromise, check type option, and build up the url with azure rules.

Results:
New users will be easier to setup.

**Comment by rattrayalex** [comment]
See our README for information about using this library with Azure OpenAI: https://github.com/openai/openai-node#azure-openai

It links to a full example here: https://github.com/openai/openai-node/blob/master/examples/azure.ts

As you can see, you're missing some details from `baseURL`, and also need to add `defaultQuery` and `defaultHeaders`. 

Is there any reason you'd prefer not to use the [official Azure OpenAI SDK](https://www.npmjs.com/package/@azure/openai)?

**Comment by rattrayalex** [comment]
Azure OpenAI is a different API; it's _similar_ to OpenAI's API, but subtly different, and provided by Microsoft Azure, not by OpenAI.

**Comment by mattlgroff** [comment]
> See our README for information about using this library with Azure OpenAI: https://github.com/openai/openai-node#azure-openai
> 
> It links to a full example here: https://github.com/openai/openai-node/blob/master/examples/azure.ts
> 
> As you can see, you're missing some details from `baseURL`, and also need to add `defaultQuery` and `defaultHeaders`.
> 
> Is there any reason you'd prefer not to use the [official Azure OpenAI SDK](https://www.npmjs.com/package/@azure/openai)?

The Azure OpenAI SDK is slow to adapt to new features like Function Calling. 

https://github.com/Azure/azure-sdk-for-js/issues/27039

**Comment by deyaaeldeen** [comment]
@mattlgroff The Azure OpenAI SDK releases happen shortly after when features were added to the Azure OpenAI API. The issue you linked to is a bug in the already released function calls rather than a request to add support for function calls. We're quick to address most SDK issues and please feel free to open issues in https://github.com/Azure/azure-sdk-for-js with feature requests or bug reports.
