### ISSUE TITLE
Add type definitions for TS support

### ISSUE THREAD

**Issue by jsmonkey** [openai/openai-node#26]
### Describe the feature or improvement you're requesting

Right now, migrating to Typescript or creating a d.ts file manually are few of the options.
If the API is going to be minimal in the long term, then simple index.d.ts created manually should be enough.

**Comment by schnerd** [comment]
Typescript is supported, you can see the `.d.ts` files in the `/dist` folder here: https://github.com/openai/openai-node/tree/master/dist

If you find that the types aren't working for some reason, please open a separate issue with steps to reproduce the problem.
