### ISSUE TITLE
Library Warning About 'encoding' Module Not Existing Without Listing it in 'peerDependencies'

### ISSUE THREAD

**Issue by zoominGiladSher** [openai/openai-node#261]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm using a rather simple NextJS app to have an API layer to communicate with the OpenAI API using the `openai` npm package. After upgrading to the latest version to start using the built-in streaming capability (thanks for that BTW!) I'm seeing warnings about `encoding` not being able to resolve. I'm unsure if this is a problem with the OpenAI package not listing encoding as a `peerDependency` or a regular dependency, or maybe it's a problem with node-fetch not doing so. Either way, I ask that you kindly try to see if this is resolvable by adding it to your library as a `peerDependency`.
```
- warn ./node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/giladsher/repos/zoomin-gpt-api/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib'
```

If I install the `encoding` package the warning goes away as expected, but this might be easily solvable without a manual installation and dependency management.

### To Reproduce

In a NextJS app create a `route.ts` file that gets a prompt. Use the code snippet below to generate the completion and return it to the user as a stream. (I use the https://www.npmjs.com/package/ai package to get some easier-to-use abstractions).

```ts
openAI.chat.completions.create(
        {
          model: 'gpt-4',
          messages: [{ role: 'user', content: prompt }],
          temperature: 0,
          top_p: 1,
          n: 1,
          frequency_penalty: 0.0,
          presence_penalty: 0.0,
          stream: true,
        },
      );
```

See that you get the aforementioned warning about `encoding` module not being able to resolve

### Code snippets

```JavaScript
openAI.chat.completions.create(
        {
          model: 'gpt-4',
          messages: [{ role: 'user', content: prompt }],
          temperature: 0,
          top_p: 1,
          n: 1,
          frequency_penalty: 0.0,
          presence_penalty: 0.0,
          stream: true,
        },
      );
```

### OS

macOS

### Node version

v18.17.1

### Library version

v4.3.0

**Comment by rattrayalex** [comment]
Thanks for reporting. `node-fetch` does indeed mark this as an optional peer dependency: 

https://github.com/node-fetch/node-fetch/blob/2.x/package.json#L45-L48

and it's not required for this library to function, so this warning can be safely ignored. We wouldn't want to require users to install this library unnecessarily.

Perhaps an issue should be filed with `pnpm` to not emit this warning when the peerDependency is marked as optional?

**Comment by zoominGiladSher** [comment]
BTW, is there a reason that the library is using node-fetch 2.x instead of the latest 3.x version?

**Comment by rattrayalex** [comment]
Yes, node-fetch 2.x supports CJS & ESM, while 3.x only supports ESM. This library supports both CJS & ESM.
