### ISSUE TITLE
Typescript version below 4.5 not supported

### ISSUE THREAD

**Issue by derN3rd** [openai/openai-node#267]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hey there,

as we tried to update to the 4.x version of openai-node we got build issues that looked like this

```
[6:00:31 PM] Building project '/Users/derN3rd/git/openai-playground/tsconfig.json'...

node_modules/openai/core.d.ts:3:15 - error TS1005: ',' expected.

3 import { type Agent } from 'openai/_shims/agent';
                ~~~~~

node_modules/openai/core.d.ts:4:15 - error TS1005: ',' expected.

4 import { type RequestInfo, type RequestInit, type Response, type HeadersInit } from 'openai/_shims/fetch';
                ~~~~~~~~~~~

node_modules/openai/core.d.ts:4:33 - error TS1005: ',' expected.

4 import { type RequestInfo, type RequestInit, type Response, type HeadersInit } from 'openai/_shims/fetch';
                                  ~~~~~~~~~~~

node_modules/openai/core.d.ts:4:51 - error TS1005: ',' expected.

4 import { type RequestInfo, type RequestInit, type Response, type HeadersInit } from 'openai/_shims/fetch';
                                                    ~~~~~~~~

node_modules/openai/core.d.ts:4:66 - error TS1005: ',' expected.

4 import { type RequestInfo, type RequestInit, type Response, type HeadersInit } from 'openai/_shims/fetch';
                                                                   ~~~~~~~~~~~

node_modules/openai/core.d.ts:5:15 - error TS1005: ',' expected.

5 export { type Response };
                ~~~~~~~~

node_modules/openai/core.d.ts:10:8 - error TS1005: ',' expected.

10   type Uploadable,
          ~~~~~~~~~~

node_modules/openai/resources/audio/transcriptions.d.ts:4:15 - error TS1005: ',' expected.

4 import { type Uploadable } from 'openai/core';
                ~~~~~~~~~~

node_modules/openai/resources/audio/translations.d.ts:4:15 - error TS1005: ',' expected.

4 import { type Uploadable } from 'openai/core';
                ~~~~~~~~~~

node_modules/openai/resources/files.d.ts:4:15 - error TS1005: ',' expected.

4 import { type Uploadable } from 'openai/core';
                ~~~~~~~~~~

node_modules/openai/resources/images.d.ts:4:15 - error TS1005: ',' expected.

4 import { type Uploadable } from 'openai/core';
                ~~~~~~~~~~

node_modules/openai/uploads.d.ts:1:15 - error TS1005: ',' expected.

1 import { type RequestOptions } from './core.js';
                ~~~~~~~~~~~~~~

node_modules/openai/uploads.d.ts:2:15 - error TS1005: ',' expected.

2 import { type Readable } from 'openai/_shims/node-readable';
                ~~~~~~~~

node_modules/openai/uploads.d.ts:3:15 - error TS1005: ',' expected.

3 import { type BodyInit } from 'openai/_shims/fetch';
                ~~~~~~~~

node_modules/openai/uploads.d.ts:4:25 - error TS1005: ',' expected.

4 import { FormData, type Blob, type FilePropertyBag } from 'openai/_shims/formdata';
                          ~~~~

node_modules/openai/uploads.d.ts:4:36 - error TS1005: ',' expected.

4 import { FormData, type Blob, type FilePropertyBag } from 'openai/_shims/formdata';
                                     ~~~~~~~~~~~~~~~

node_modules/openai/uploads.d.ts:6:15 - error TS1005: ',' expected.

6 import { type FsReadStream } from 'openai/_shims/node-readable';

```

After trying out different node versions, we figured out that the imports in these files are only supported since [Typescript 4.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names).
Maybe this should be added to the [Requirements](https://github.com/openai/openai-node#requirements) in the readme.

This can be closed, just wanted to put it here in case someone has the same issue.

Thanks in advance

### To Reproduce

1. Install Typescript 4.4
2. install the openai module
3. use some example code
4. try to build with `tsc`
5. Error appears

### OS

macOS

### Node version

Node v16.17.0

### Library version

openai 4.3.1

**Comment by rattrayalex** [comment]
Thank you very much for opening this! We'll take a look at supporting earlier versions of TypeScript as well. For context as we do, can you share any perspective on how difficult is it to upgrade to TypeScript 4.5?

**Comment by derN3rd** [comment]
As we were using TS 4.3 before, we did not have a single error after the version bump.

Not sure how big this might be for people with TS 3

**Comment by rattrayalex** [comment]
Ah ok, great to hear. I think we'll just document that we're only TS 4.5+ for the time being then. Thanks!

**Comment by yilikun** [comment]
> Thank you very much for opening this! We'll take a look at supporting earlier versions of TypeScript as well. For context as we do, can you share any perspective on how difficult is it to upgrade to TypeScript 4.5?

`We'll take a look at supporting earlier versions of TypeScript as well. `
Has this job started? Is it compatible with version 3.x?
we use ts 3.8.0，if update to 4.x，appear 500+ error....
