### ISSUE TITLE
Add reverse proxy

### ISSUE THREAD

**Issue by YIKAILucas** [openai/openai-node#278]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I set up a reverse proxy for openai. But this lib can only access official api address. Could you plan to add custom url?

**Comment by rattrayalex** [comment]
You can configure `baseURL` and `httpAgent`: https://github.com/openai/openai-node#configuring-an-https-agent-eg-for-proxies
