### ISSUE TITLE
I use the official website method to use gpt-3.5-turbo，report an error "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions"

### ISSUE THREAD

**Issue by airuikun** [openai/openai-node#280]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I use the official website method to use gpt-3.5-turbo，report an error "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions"

code is：
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'

$OPENAI_API_KEY is replace my API key

### To Reproduce

1.in your terminal, copy code:
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'

$OPENAI_API_KEY is replace your API key

2.terminal report en error :
{
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

### Code snippets

```JavaScript
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'

$OPENAI_API_KEY is replace your API key
```

### OS

macOS

### Node version

Node 18

### Library version

terminal

**Comment by rattrayalex** [comment]
This is not an SDK bug; please report in https://community.openai.com

**Comment by jhallard** [comment]
Hello @airuikun, do you happen to have a request ID available?
