### ISSUE TITLE
FormData error

### ISSUE THREAD

**Issue by A-afflatus** [openai/openai-node#284]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

                const openai = new OpenAI(openaiConf)
                openai.files.create({
                    file: fs.createReadStream('C:\\Users\\18222\\Desktop\\workspace\\AfflatusBox\\1.jsonl'),
                    purpose: "fine-tune"
                }).then(fr=>{
                    console.log("fr",fr);
                    }）
The following problems occur：
TypeError: Received null for "file[fd]"; to pass null in FormData, you must use the string 'null'

### To Reproduce

                const openai = new OpenAI(openaiConf)
                openai.files.create({
                    file: fs.createReadStream('C:\\Users\\18222\\Desktop\\workspace\\AfflatusBox\\1.jsonl'),
                    purpose: "fine-tune"
                }).then(fr=>{
                    console.log("fr",fr);
                    }）
The following problems occur：
TypeError: Received null for "file[fd]"; to pass null in FormData, you must use the string 'null'

### OS

windows11

### Node version

18.17.0

### Library version

4.3.0

**Comment by A-afflatus** [comment]
Thank you for your response, see below：
```ts
import OpenAI, { ClientOptions, toFile } from 'openai';
import fs from 'fs';
```

```json
{
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build && electron-builder",
    "build:mac": "tsc && vite build && electron-builder --mac",
    "build:win": "tsc && vite build && electron-builder --win",
    "lint": "eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.379.1",
    "@aws-sdk/s3-request-presigner": "^3.370.0",
    "@mantine/core": "^6.0.16",
    "@mantine/form": "^6.0.17",
    "@mantine/hooks": "^6.0.16",
    "@mantine/notifications": "^6.0.16",
    "@mantine/prism": "^6.0.16",
    "@mantine/spotlight": "^6.0.16",
    "@reduxjs/toolkit": "^1.9.5",
    "@tabler/icons-react": "^2.25.0",
    "@traptitech/markdown-it-katex": "^3.6.0",
    "dayjs": "^1.11.9",
    "electron-settings": "^4.0.2",
    "framer-motion": "^10.13.0",
    "highlight.js": "^11.8.0",
    "lodash": "^4.17.21",
    "lowdb": "^6.0.1",
    "markdown-it": "^13.0.1",
    "markdown-it-emoji": "^2.0.2",
    "markdown-it-footnote": "^3.0.3",
    "markdown-it-link-attributes": "^4.0.1",
    "octokit": "^3.1.0",
    "openai": "^4.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.1.1",
    "react-router-dom": "^6.14.0"
  },
  "devDependencies": {
    "@types/markdown-it": "^12.2.3",
    "@types/markdown-it-emoji": "^2.0.2",
    "@types/markdown-it-footnote": "^3.0.0",
    "@types/markdown-it-link-attributes": "^3.0.1",
    "@types/polyfill-library": "^3.108.1",
    "@types/react": "^18.0.37",
    "@types/react-dom": "^18.0.11",
    "@types/uuid": "^9.0.2",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "@vitejs/plugin-react": "^4.0.0",
    "electron": "^24.4.0",
    "electron-builder": "^23.6.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vite-plugin-electron": "^0.11.2",
    "vite-plugin-electron-renderer": "^0.14.5"
  },
  "main": "dist-electron/main.js"
}


{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*":["src/*"]
    },
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src", "electron","types"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

Using your advice, I encountered the following error：
`
 UnhandledPromiseRejectionWarning: Error: file uploads aren't supported in this environment yet as 'File' is not defined
`
Additionally, I am using the Electron environment.
![image](https://github.com/openai/openai-node/assets/130149563/fd9847bb-6393-438a-a994-f4d15348c520)

**Comment by rattrayalex** [comment]
Ah, I see! That makes sense - Electron is not yet supported. 

You might try a polyfill that adds `File` support, but please note OpenAI [advises against](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety) calling the API from a client environment (such as Electron) since it can expose your API keys to attackers.

**Comment by A-afflatus** [comment]
Okay, I will try to modify my code privately and thank you for your patient assistance.
