### ISSUE TITLE
Add utilities to make creating messages easier

### ISSUE THREAD

**Issue by avin-kavish** [openai/openai-node#293]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Hey!

I use this helper utility to make it easier to build messages in the format accepted by the API. Feel free to add it centrally if others might find it useful too...

```ts
function createMessageFactory<T extends ChatCompletionMessageParam['role']>(role: T) {
  return function(strings: TemplateStringsArray, ...args: any[]) {
    let str = strings[0]
    for (let i = 0; i < args.length; i++) {
      str += args[i] + strings[i + 1]
    }
    return { role: role, content: str.trim() }
  }
}

export const system = createMessageFactory('system')
export const user = createMessageFactory('user')
export const assistant = createMessageFactory('assistant')

// usage
const prompt = system`Do a backflip!`
```

**Comment by rattrayalex** [comment]
Thanks for the suggestion! That looks like a handy piece of code and we'll be sure to point people this way if they ask for it.

For the time being, we'll close this as not planned, but may incorporate helpers like this in the future.
