### ISSUE TITLE
Fine tune request is being deprecated

### ISSUE THREAD

**Issue by thetrinh16698** [openai/openai-node#308]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hi, I have been trying to create the fine tune request for the GPT-3.5-turbo. I managed to successfully sent my file and received the id of my file from OpenAI. But when I used that file id to start the fine tune request, it returned an error that stated 
"gpt-3.5-turbo can only be fine-tuned on the new fine-tuning API. This API is being deprecated. Please refer to our documentation: https://platform.openai.com/docs/api-reference/fine-tuning"

### To Reproduce
Just use the fine tune request that is available on the newest version of the API

### Code snippets
  public async sendFineTuneRequest(file: Express.Multer.File) {
    try {
      console.log(file)
      let tmpFilePath = path.join(os.tmpdir(), file.originalname)
      await fsPromises.writeFile(tmpFilePath, file.buffer)

      let stream = fs.createReadStream(tmpFilePath)
      const sendFile = await this.openAI.files.create({
        file: stream,
        purpose: 'fine-tune',
      })
      await fsPromises.unlink(tmpFilePath)
      console.log(JSON.stringify(sendFile))
      const fineTune = await this.openAI.fineTunes.create({
        training_file: sendFile.id,
        model: 'gpt-3.5-turbo',
      })
      console.log(fineTune, 'fineTune')
      return '123'
    } catch (error) {
      Logger.error('fine tune request failed')
      throw error
    }
_No response_

### OS

Windows 11

### Node version

Node v16.13.1

### Library version

openai 4.6.0

**Comment by rattrayalex** [comment]
As it demonstrates in the linked documentation – https://platform.openai.com/docs/api-reference/fine-tuning/create?lang=node.js – you want to use `openai.fineTuning.jobs.create` instead of `fineTunes.create`.

```ts
import OpenAI from "openai";

const openai = new OpenAI();

async function main() {
  const fineTune = await openai.fineTuning.jobs.create({
    training_file: "file-abc123"
  });

  console.log(fineTune);
}

main();
```

**Comment by thetrinh16698** [comment]
But how can I use fineTuning.jobs.create if in the package only offer fineTunes.create?
