### ISSUE TITLE
all models except davinci 2 + not working...

### ISSUE THREAD

**Issue by temrb** [openai/openai-node#31]
### Describe the bug

all models except davinci 2 + not working... 

I get axios errors when trying to use models such as ada / babbage / etc EXCEPT davinci 2+ -> these models are not working; throws error. 

### To Reproduce

Fetch using redux. 

Error snip:

  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      date: 'Fri, 02 Dec 2022 00:49:31 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '158',
      connection: 'close',
      vary: 'Origin',
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',

### Code snippets

```JavaScript
import { OpenAIApi, Configuration } from 'openai';
import { Ratelimit } from '@upstash/ratelimit';
import { Redis } from '@upstash/redis';
import getIP from '../../../utils/get-ip';

const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

const redis = new Redis({
    url: process.env.UPSTASH_REST_API_DOMAIN,
    token: process.env.UPSTASH_REST_API_TOKEN,
});

const ratelimit = new Ratelimit({
    redis: redis,
    limiter: Ratelimit.slidingWindow(3, '1 d'),
});

export default async function response(req, res) {
    const ip = getIP(req);
    const result = await ratelimit.limit(ip);
    res.setHeader('X-RateLimit-Limit', result.limit);
    res.setHeader('X-RateLimit-Remaining', result.remaining);

    if (req.method !== 'POST') {
        res.status(405).json({ error: 'Method not allowed' });
        return;
    }

    if (!req.body.projectId) {
        res.status(400).json({ error: 'Missing projectId' });
        return;
    }

    if (!result.success) {
        res.status(429).json({
            error: 'You have reached your daily limit of 3 free completions. Try again tomorrow or upgrade your plan in account settings to continue using services regularly.',
        });
        return;
    }

    const completion = await openai.createCompletion({
        model: 'text-davinci-002',
        prompt: req.body.prompt,
        temperature: 0.6,
        max_tokens: 2000,
        presence_penalty: 0.5,
        // frequency_penalty: 0.5,
    });

    try {
        const completeModeration = await openai.createModeration({
            input: completion.data.choices[0].text,
            model: 'text-moderation-latest',
        });
        const moderationRes = completeModeration.data.results[0].flagged;
        if (moderationRes === false) {
            res.status(200).json({ response: completion.data.choices[0].text });
        } else {
            res.status(500).json({
                error: 'Sorry. The output has been flagged for inappropriate content. Please try again.',
            });
        }
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
}
```

### OS

mac

### Node version

v18.12.0

### Library version

3.1.0

**Comment by doverradio** [comment]
Having same issue

**Comment by schnerd** [comment]
Hi @temrb and @doverradio – The following code works for me on library version 3.1.0:

```js
// script.js
// Run with: node script.js
import { Configuration, OpenAIApi } from "openai";

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

async function init() {
    try {
        const resp = await openai.createCompletion({
            model: 'ada',
            prompt: 'Hello world',
        });
        console.log(resp.data);
    } catch (error) {
        console.log(error.response.status);
        console.log(error.response.data);
        console.log(error.message);
    }
}

init();
```

Does that work for you? If not, can you provide exact code that I can execute to replicate the issue you're experiencing?

**Comment by temrb** [comment]
Seems to be working now when I replace the model input in my original posted code from text-davinci-2 to just using the model name without numbers ; 'ada'

Where as in the documentation it says to use text-ada-001

When I opened the issue I was trying both ways and it was still giving issue. Not sure if it was an update that changed either way docs should be updated imo.

**Comment by schnerd** [comment]
> Where as in the documentation it says to use text-ada-001

`text-ada-001` works for me too if I replace `'ada'` with `'text-ada-001'` in my code snippet. I just assumed you were using the older legacy `ada` model based on your original post, but yes you should be using `'text-ada-001'`.

**Comment by schnerd** [comment]
Going to resolve this issue – feel free to open a new issue if you continue to run into problems.

**Comment by mepc36** [comment]
Hey @schnerd! I believe this error (where users can't use any model besides `davinci`) is still happening. My node version is 16.16. My library version is 3.2.0. Here is how I'm trying to call the `ada` model:

```
        await openaiClient.createCompletion({
          model: 'text-ada-001',
          prompt,
          temperature,
          n,
          presence_penalty,
          frequency_penalty,
          max_tokens,
        });
```

I tried passing in `ada` to the `model` parameter, but that didn't work either. If you could please advise I'd greatly appreciate it. Thanks!

**Comment by mepc36** [comment]
Nevermind, mistake was in my code. Turning it to `ada` from `text-ada-001` worked. Thank you! @schnerd
