### ISSUE TITLE
dalleRoutes.js (to fetch images from openapi)

### ISSUE THREAD

**Issue by Ashisid345** [openai/openai-node#317]
dalleRoutes.js (to fetch images from openapi)

import express from 'express';
import * as dotenv from 'dotenv';
import { OpenAI } from 'openai';

import Post from '../mongodb/models/post.js';

dotenv.config();

const router = express.Router();

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
})

router.route('/').get((req, res) => {
    res.send("Dall-e says 'HII'");
});

router.route('/').post(async (req, res) => {
    try {
        const { prompt } = req.body;

        const aiResponse = await openai.createImage({
            prompt,
            n: 1,
            size: '1024x1024',
            response_format: 'b64_json',
        });

        const image = aiResponse.data.data[0].b64_json;

        res.status(200).json({ photo: image });

    } catch (error) {
        res.status(500);
        console.log('Error in getting the prompt', error);
    }
})

export default router;

postRoutes.js (to post on homepage)

import express from 'express';
import * as dotenv from 'dotenv';
import { v2 as cloudinary } from 'cloudinary';

import Post from '../mongodb/models/post.js';

dotenv.config();

const router = express.Router();

cloudinary.config({
    cloud_name: process.env.CLOUDINARY_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
});

//GET ALL POSTS
router.route('/').get(async (req, res) => {
    try {
        const posts = await Post.find({});

        res.status(200).json({ success: true, data: posts })
    } catch (error) {
        res.status(500).json({ success: false, message: error })

    }
});

//CREATE A POST
router.route('/').post(async (req, res) => {
    try {
        const { name, prompt, photo } = req.body;
        const photoUrl = await cloudinary.uploader.upload(photo);

        const newPost = await Post.create({
            name,
            prompt,
            photo: photoUrl.url,
        })

        res.status(201).json({ success: true, data: newPost });
    } catch (e) {
        res.status(500).json({ success: false, message: error });
    }
});

export default router;

I'm getting this error:
Error in getting the prompt TypeError: openai.createImage is not a function
    at file:///E:/React_projects/DreamVerse/backend/routes/dalleRoutes.js:23:41..
Pls help!!!

_Originally posted by @Darshan2923 in https://github.com/openai/openai-node/discussions/217#discussioncomment-6891029_

**Comment by rattrayalex** [comment]
createImage is a v3 method; see the v4 migration guide. For developer help, check out the OpenAI discord.
