### ISSUE TITLE
openai.createTranscription is not a function.

### ISSUE THREAD

**Issue by biorisk2** [openai/openai-node#319]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

file:///C:/scambaiting/app.mjs:200
        const transcript = await openai.createTranscription(fs.createReadStream(filename), 'whisper-1');
                                        ^

TypeError: openai.createTranscription is not a function
    at transcribeAudio (file:///C:/scambaiting/app.mjs:200:34)
    at main (file:///C:/scambaiting/app.mjs:209:30)

### To Reproduce

const transcript = await openai.createTranscription(fs.createReadStream(filename), 'whisper-1');

this line returns the error, 

However, this works:

const completion = await openai.chat.completions.create({
    messages: [{ role: 'user', content: 'Tell me a random color.' }],
    model: 'gpt-3.5-turbo',
  });
  console.log(completion.choices); // prints out like "Indigo" or "Sea Foam Green"

### Code snippets

```JavaScript
import OpenAI from 'openai';

const openai = new OpenAI({
	apiKey: 'hehe_xd',
});

async function transcribeAudio(filename) {
	
	const transcript = await openai.createTranscription(fs.createReadStream(filename), 'whisper-1');

	return transcript.data.text;
}
```

### OS

win10

### Node version

Node.js v19.5.0

### Library version

latest

**Comment by rattrayalex** [comment]
createTranscription is a v3 method; see the v4 migration guide. For developer help, check out the OpenAI discord.
