### ISSUE TITLE
Type for finish_reason should include 'content_filter'

### ISSUE THREAD

**Issue by lox** [openai/openai-node#320]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Based on the docs at https://platform.openai.com/docs/guides/gpt/chat-completions-api, finish_reason can include:

```
stop: API returned complete message, or a message terminated by one of the [stop](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stop) sequences provided via the stop parameter

length: Incomplete model output due to [max_tokens](https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens) parameter or token limit

function_call: The model decided to call a function

content_filter: Omitted content due to a flag from our content filters

null: API response still in progress or incomplete 
```

Indeed Azure's API will return `content_filter` frequently.

The types at https://github.com/openai/openai-node/blob/03869373db52f0fc07ca07bde367057e6d56bbff/src/resources/chat/completions.ts#L81 should include content_filter.  

### To Reproduce

1. Read docs
2. Make calls to Azure
3. Write code to handle content_filter
4. Observe type errors

### OS

macOS

### Node version

Node v20.5.1

### Library version

openai v4.0.1

**Comment by rattrayalex** [comment]
Thanks for reporting! I've opened https://github.com/openai/openai-openapi/pull/88 to address this.

**Comment by lox** [comment]
Thanks for the quick fix @rattrayalex
