### ISSUE TITLE
String-based chunks in Stream object pose challenges for server-side implementation

### ISSUE THREAD

**Issue by bkyerv** [openai/openai-node#321]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

I'm implementing a server-side request to the OpenAI endpoint, following OpenAI's strong recommendation not to expose API keys on the client-side. While doing so, I've noticed that the Stream object returned from the endpoint contains chunks in string form, rather than byte-like data.

This design choice complicates the process of forwarding the server response to the client. Specifically, it adds complexity when attempting to use TransformStream, as the string-based chunks require an extra encoding step to convert them into byte-like data suitable for network transmission.

Could you clarify the reasoning behind delivering the stream chunks as strings? Knowing this could help simplify the process of securely transmitting data from the server to the client, in line with OpenAI's security recommendations.

**Comment by rattrayalex** [comment]
I'm not sure what you mean, can you include a code snippet? The chunks yielded are parsed json objects.

We do plan to release helpers for streaming to frontends soon, eg:

```ts
// backend
app.post('my-openai-proxy, () => {
  return new Response(
    client.chat.completions.stream(params)
      .on('content', text => process.stdout.println(text))
      .toReadableStream()
  )
})
```
```ts
// frontend
import { ChatCompletionStream } from 'openai'

const rsp = await fetch('/my-openai-proxy')
const stream = ChatCompletionStream.fromReadableStream(rsp.body)
  .on('content', (diff, snapshot) => updateUI(diff, snapshot))

const chat = await stream.finalChatCompletion()
console.log(chat.choices) // full object

**Comment by rattrayalex** [comment]
Hi @bkyerv , I'm going to go ahead and close this since I'm not quite sure what you're asking, but do share some code when you can and we can take another look.
