### ISSUE TITLE
How to use it with axios using custom fetch?

### ISSUE THREAD

**Issue by MiniSuperDev** [openai/openai-node#323]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I want to use axios to use [axios interceptors](https://axios-http.com/docs/interceptors), or the proxy config of axios.

I think it can be used in the fetch params of the ClientOptions, like this example

https://github.com/openai/openai-node/blob/03869373db52f0fc07ca07bde367057e6d56bbff/tests/index.test.ts#L86-L90

But I don't know how to use it

```ts
    const openai = new OpenAI({
      fetch: async (requestInfo: RequestInfo, init?: RequestInit) => {
        // TODO: Use acios
        // return axios()
      }
    })
```

Can you help me, and tell me If there are any limitations when using axios as a custom fetch?

I think this could be added to de docs.

Thanks

**Comment by rattrayalex** [comment]
You're correct that this can be achieved with a custom `fetch` function, but unfortunately we can't provide close guidance on how to do this, as there may be caveats we'd need to test.

However, [asking ChatGPT for help making requests with axios that conform to fetch request/responses seems useful](https://chat.openai.com/share/fa9e0003-200f-4543-b827-12272b3af9fa), you might try that as a starting point.
