### ISSUE TITLE
Configuring an HTTP(S) Agent (e.g., for proxies) not Work in Browser

### ISSUE THREAD

**Issue by MiniSuperDev** [openai/openai-node#324]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When use `httpAgent` in the browser, the agent is ignored and never used.

### To Reproduce

```ts
import OpenAI from "openai"
import http from 'http';
import HttpsProxyAgent from 'https-proxy-agent';

// Configure the default for all requests:
const openai = new OpenAI({
  dangerouslyAllowBrowser: true,
  httpAgent: new HttpsProxyAgent(process.env.PROXY_URL),
});
openai.models.list().then(console.log);
```

### OS

Windows 10

### Node version

v18.17.1

### Library version

v4.8.0

**Comment by rattrayalex** [comment]
For this use-case, you just want `baseURL`.
