### ISSUE TITLE
"lib/IsolatedGPT35TurboMutation/deleteFineTuneModel: AbortController is not defined"

### ISSUE THREAD

**Issue by pavelbrui** [openai/openai-node#333]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

What is this error?
It works fine locally, but when deploying I get this error..: "lib/IsolatedGPT35TurboMutation/deleteFineTuneModel: AbortController is not defined"

### To Reproduce

if (job.model_id) {
      if (!src.openAiKey) throw new Error('OpenAiKey not found');
      const openai = new OpenAI({ apiKey: src.openAiKey });
      const model = await openai.models.del(job.model_id);

### OS

macOS

### Node version

Node 18

### Library version

openai 4.0.8

**Comment by rattrayalex** [comment]
Can you check whether this happens on `"openai": "4.8.0"` and `"openai": "4.9.0"`? We changed behavior in 4.9.0, so it'd be helpful to know whether that version fixed the issue, regressed it, or didn't fix it.

**Comment by frankwo1** [comment]
unable to resolve the ReferenceError: AbortController is not defined error when trying to install 
openai>3.3.0 npm package. updated my node to 18.18.0 MacOS

**Comment by rattrayalex** [comment]
Can you please share what package version you are using, how you are running the code, and a traceback?

**Comment by frankwo1** [comment]
Running node 18.18
works with openai 3.3.0 - unable to run gpt-4 with this package version (but am able davince)  and cannot upgrade to openai 4 since it has error during install (ReferenceError: AbortController is not defined)

**Comment by rattrayalex** [comment]
@frankwo1 how are you installing and building your code?
