### ISSUE TITLE
The SDK examples for finetuning in the docs are wrong.

### ISSUE THREAD

**Issue by edmundmunday** [openai/openai-node#336]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

In the docs it tells you to use:
```js
const fineTune = await openai.fineTunes.create({ training_file: 'file-abc123', model: 'gpt-3.5-turbo' })
```

Whereas in the API reference, it says to use:
```js
const fineTune = await openai.fineTuning.jobs.create({ training_file: 'file-abc123', model: 'gpt-3.5-turbo' })
```

I'm assuming the API reference is the correct version, if so, the docs need to be updated.
Link to relevant section in docs: https://platform.openai.com/docs/guides/fine-tuning/create-a-fine-tuned-model

### To Reproduce

1. read docs here: https://platform.openai.com/docs/guides/fine-tuning/create-a-fine-tuned-model
2. read API reference here: https://platform.openai.com/docs/api-reference/fine-tuning/create

### OS

macOS

### Node version

Node v18.17.1

### Library version

openai v4.5.0

**Comment by rattrayalex** [comment]
Please report issues with the docs or API to https://community.openai.com.
