### ISSUE TITLE
Missing content_filter in finish_reason of chat completion chunk

### ISSUE THREAD

**Issue by dylanjcastillo** [openai/openai-node#337]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When trying to select events that were stopped due to content moderation, you get a warning that about `content_filter` not being one of the options of `finish_reason`:

![image](https://github.com/openai/openai-node/assets/7218756/06e172e8-7983-4c7f-8f57-df0c104cb841)

This doesn't match the official documentation of OpenAI: https://platform.openai.com/docs/api-reference/chat/streaming

### To Reproduce

Try to select events that were stopped due to content moderation.

### Code snippets

```JavaScript
    const stream = await openai.chat.completions.create({
      model: OPENAI_MODEL,
      messages: messages,
      stream: true,
    })

    for await (const event of stream) {
      for (const choice of event.choices) {
        if (choice.finish_reason === 'content_filter') {
          console.log("Content filter triggered")
        }
        console.log(event)
      }
    }
```
```


### OS

macOS

### Node version

Node v18

### Library version

openai v4.8.0

**Comment by rattrayalex** [comment]
This was [added](https://github.com/openai/openai-node/pull/329/files) in v4.10.0!

**Comment by dylanjcastillo** [comment]
@rattrayalex I think this isn't not fixed yet in `ChatCompletionChunk`: https://github.com/openai/openai-node/blob/7f36a5e082f6f8f4786e9e02915096aa99ff8553/src/resources/chat/completions.ts#L128

**Comment by rattrayalex** [comment]
Ah, thanks! Sorry about that. Added here: https://github.com/openai/openai-openapi/pull/90

I'd expect it to be released in the next day or two.

**Comment by dylanjcastillo** [comment]
Thank you
