### ISSUE TITLE
Reading stream response in JS client raises "TypeError: network error"

### ISSUE THREAD

**Issue by mark-mishyn** [openai/openai-node#347]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm trying to stream response from AWS Lambda using the library using Lambda's "Streaming Response" and "Function URL" features. But on client side I always facing  _**TypeError: network error**_  after 10-30 successfully read chunks of data.

I have this error in Google Chrome, Chromium, FIreFox. Also reproducible in other clients (for example Python requests). 

Not sure that this is the library's issue, but I cannot find solution.

### To Reproduce

1. npm install ... and use installed package as AWS Lambda Layer
2. deploy to AWS Lambda (Runtime Node 18 + Response Streming + Function URL + CORS enabled)
3. write simple client and run it

### Code snippets

```JavaScript
// Below is my server code (AWS Lambda):
import OpenAI from 'openai';

const openai = new OpenAI({
    apiKey: OPENAI_API_KEY,
    maxRetries: 5,
});

export const handler = awslambda.streamifyResponse(async (event, responseStream, _context) => {

    const stream = await openai.chat.completions.create({
        model: MODEL,
        messages: data.messages,
        stream: true,
    });

    for await (const part of stream) {
        let chunk = part.choices[0]?.delta?.content || '';
        if (chunk && chunk.length) {
            responseStream.write(chunk);
        }

    }
    responseStream.end();
})


// And client code (pure JS):
const response = await fetch(url, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify({messages}),
});

const reader = response.body.getReader();

while (true) {
    const {done, value} = await reader.read();  // <--- this line raises error
    if (done) break;
    const decodedValue = new TextDecoder().decode(value);
    console.log(decodedValue)
}
```

### OS

Linux

### Node version

Node.js v18.x

### Library version

4.11.0

**Comment by rattrayalex** [comment]
Sorry you're running into this, and thanks for sharing your sample code!

This sounds like an AWS Lambda issue; I recommend asking for help in that community, or adding server logs to see what could be going on.

We do hope to release some full-stack streaming helpers in the near future which _may_ help with this; I'll try to update you when it's ready. 

If you figure this out, please do share back here, as I'm sure others may run into the same issue!

**Comment by rattrayalex** [comment]
Glad it was an easy fix, thanks for sharing your learnings with the community!
