### ISSUE TITLE
openai.chat.completions.create throws a 404 Invalid URL error

### ISSUE THREAD

**Issue by saibimajdi** [openai/openai-node#348]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm trying to create a simple React Native app using the OpenAI npm package.
I have installed version  4.11.1

I keep getting an Invalid URL error `404 Invalid URL (POST /v1/chat/completions/)`

But when I call the same endpoint using Postman I get back the expected results.

I have noticed there's an additional `/` on the API endpoint mentioned in the error message, `/v1/chat/completions/`
So, I tried to build the URL myself using `openai.buildURL` and it worked as expected.

Everything works as expected if I add these two lines before the API call.

```
openAi.baseURL = 'https://api.openai.com/v1';
openAi.buildURL = (path: string) => `${openAi.baseURL}${path}`;
```

So I believe something is wrong with the endpoint URL.

### To Reproduce

1. Creating a new React Native app with Expo.
2. Install OpenAI npm package (I'm using version 4.11.1).
3. Call the `openai.chat.completions.create({...})` method.

### Code snippets

```JavaScript
const openAi = new OpenAI({ apiKey: 'sk-x0x0x0x0x0x0x0x' });

const response = await openAi.chat.completions.create({
                "model": "gpt-3.5-turbo",
                "messages": [
                  {
                    "role": "system",
                    "content": "You will be provided with a block of text, and your task is to extract a list of keywords from it."
                  },
                  {
                    "role": "user",
                    "content": CLEANED_USER_INPUT
                  }
                ],
                "temperature": 0.5,
                "max_tokens": 256,
                "top_p": 1,
                "frequency_penalty": 0,
                "presence_penalty": 0
              });
    
console.log('response', response);
    
return response.choices;
```

### OS

Windows 11

### Node version

16

### Library version

4.11.1

**Comment by rattrayalex** [comment]
React Native is not supported, as mentioned in the README. More details [here](https://github.com/openai/openai-node/issues/199#issuecomment-1642859127).
