### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected and Regular Expression Denial of Service

### ISSUE THREAD

**Issue by marck283** [openai/openai-node#349]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Using Node.js version 20.x or later in a project that depends on node-fetch prior to version 3.2.5 results in Node prompting a _MaxListenersExceededWarning: Possible EventEmitter memory leak detected_ warning (as can be seen [here](https://github.com/node-fetch/node-fetch/issues/1295#issuecomment-1144061991)). However, node-fetch versions between 3.1.0 and 3.2.10 also suffer from a _Regular Expression Denial of Service_ (as can be seen [here](https://security.snyk.io/package/npm/node-fetch)). Installing node-fetch@3.2.10 seems to solve both problems.

### To Reproduce

1. Initialize a new Node.js project;
2. install node-fetch prior to version 3.2.10 or packages that depend on node-fetch prior to version 3.2.10.

### OS

Windows 11

### Node version

Node v20.7.0

### Library version

openai v4.11.1

**Comment by rattrayalex** [comment]
We can't upgrade to node-fetch 3.x because it's ESM-only, and this library supports CJS as well.

We're looking into backporting the fix for that issue to the 2.x line.

FWIW, I don't believe the memory leak effects should be very significant, so this warning should be safe to ignore.

**Comment by rattrayalex** [comment]
In the meantime, @marck283 you can work around this by installing `node-fetch@3.2.10` and pass it in to the library:

```ts
import nodeFetch from 'node-fetch'
import OpenAI from 'openai'

const client = new OpenAI({ fetch: nodeFetch })
```

**Comment by rattrayalex** [comment]
We don't expect to action this directly, so closing. We are planning to remove our `node-fetch` dependency before long.
