### ISSUE TITLE
Can the axios dependency please be bumped to a current release of axios? 

### ISSUE THREAD

**Issue by duckdegen** [openai/openai-node#35]
### Describe the bug

Currently it uses axios ^0.26.0 while we are at axios 1.2.1

It's easy to mitigate, but feels really wrong to use such an old version which has a totally different type interface.

### To Reproduce

Simply install the openai package and try and pass a current version of axios into the openai instance constructor

### OS

osx

### Node version

node 19

### Library version

openai 3.1.0

**Comment by bads77** [comment]
Hi, Were you able to get past this? This is causing issue with docker builds

**Comment by grimmer0125** [comment]
I encounter the same issue. Half year after this issue was opened, the openai's axios is still `^0.26.0`, and `axios` has released `1.4.0`. version.

**Comment by rattrayalex** [comment]
We have an [upcoming version v4.0.0](https://github.com/openai/openai-node/discussions/182) that moves to `fetch`; please give it a try and let us know in the thread whether it suits your needs!
