### ISSUE TITLE
Make response accessible from the Stream class

### ISSUE THREAD

**Issue by Sylvestre67** [openai/openai-node#351]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I would like to propose allowing consumer of a `Stream` to be able to access the original `response` that includes the `Stream:PassThrough` as the `body`. When using the version `3.*.*` version of this library we (and probably a bunch of others) ended up having to build our own decoder. 

When migrating to `4.*.*` we realized the `response` object from the `Stream` class was flagged as `private` preventing us from consuming the response and leveraging all the code we already write to consume the `PassThrough` stream directly, in a **Typescript friendly way** (aka: don't `@ts-ignore` things). 

I understand the recommended way is to use the `AsyncIterator` to loop over the `decoded chunk`. This very small change would provide some backwards compatibility with the `v3 way of streaming` that a lot of consumer of this library may appreciate.  

### Additional context

Should be as simple as making the following change to the `Stream` class: 

```typescript
export class Stream<Item> implements AsyncIterable<Item> {
  controller: AbortController;
  response: Response;

  private decoder: SSEDecoder;
  ...
```

I would have open a PR but do not seem to have the permission to do so.

**Comment by rattrayalex** [comment]
This was an intentional design decision.

To access the raw response, you can use `.asResponse()` or `.withResponse()`, as documented [here](https://github.com/openai/openai-node#accessing-raw-response-data-eg-headers). Does that work for your use-case?

**Comment by Sylvestre67** [comment]
It does. Thanks ! Missed that in the documentation. The types for the `Response` is fairly wrong in the case of a Streamed response, as it does not reference the `response.body`  as `Node:PassThrough` . Had to come up with following to make this work: 
```typescript
return (response.body as unknown as PassThrough).pipe(
    transformGpt({prompt: messages})
  );
  ```

**Comment by rattrayalex** [comment]
Does setting `"moduleResolution": "NodeNext"` in your tsconfig fix the types? 

If not, does adding `import 'openai/shims/node'` before your first `import OpenAI from 'openai'` do it?
