### ISSUE TITLE
ReactNative: Error: 404 Invalid URL (POST /v1/chat/completions/)

### ISSUE THREAD

**Issue by julullc** [openai/openai-node#355]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The issue only happens when the OpenAI client is used in ReactNative code, specifically due to the following bug in ReactNative itself: https://github.com/facebook/react-native/issues/24428

Notice how the request is attempted to be sent to `/v1/chat/completions/` (with a trailing slash).

It can be resolved by installing the `https://www.npmjs.com/package/react-native-url-polyfill`; however, it can also be resolved by trimming the trailing slash in the `buildURL` method here: https://github.com/openai/openai-node/blob/master/src/core.ts#L436

Something along these lines:
```
return url.toString().endsWith('/')
      ? url.toString().slice(0, -1)
      : url.toString();
```

### To Reproduce

1. Try to send any message using the `openai.chat.completions.create` within a ReactNative app

### Code snippets

```JavaScript
const openai = new OpenAI({
  apiKey: process.env.EXPO_PUBLIC_OPENAI_API_KEY,
});

const chatCompletion = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "user",
            content: "test message",
          },
        ],
      });
```

### OS

macOS

### Node version

Node v20.3.1

### Library version

openai 4.11.1

**Comment by rattrayalex** [comment]
React Native is not supported, as documented in the README. More details [here](https://github.com/openai/openai-node/issues/199#issuecomment-1642859127).

**Comment by rattrayalex** [comment]
See also:

- https://github.com/openai/openai-node/issues/348
- https://github.com/openai/openai-node/issues/270

**Comment by PrantikMon** [comment]
> React Native is not supported, as documented in the README. More details [here](https://github.com/openai/openai-node/issues/199#issuecomment-1642859127).

Then What is the alternative process for React Native?

**Comment by depombo** [comment]
> > React Native is not supported, as documented in the README. More details [here](https://github.com/openai/openai-node/issues/199#issuecomment-1642859127).
> 
> Then What is the alternative process for React Native?

I ended up building an openai react native client that supports file upload and chat completion streaming without polyfills by using [react-native-sse](https://github.com/binaryminds/react-native-sse#readme) and the [expo file system](https://docs.expo.dev/versions/latest/sdk/filesystem/). The library uses the official node sdk everywhere else along with the same types and API

https://github.com/backmesh/openai-react-native
