### ISSUE TITLE
Nextjs issue with fetch (can't resolve encoding)

### ISSUE THREAD

**Issue by ShravanSunder** [openai/openai-node#359]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

usage of this module in a monorepo libary with Nextjs causes an error
```

Module not found: Can't resolve 'encoding' in '/Users/shravansunder/Documents/dev/project-dev/2023-askluna/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js
../../node_modules/.pnpm/openai@4.11.1/node_modules/openai/_shims/node-runtime.mjs
../../node_modules/.pnpm/openai@4.11.1/node_modules/openai/_shims/auto/runtime-node.mjs
../../node_modules/.pnpm/openai@4.11.1/node_modules/openai/_shims/index.mjs
../../node_modules/.pnpm/openai@4.11.1/node_modules/openai/core.mjs
../../node_modules/.pnpm/openai@4.11.1/node_modules/openai/index.mjs
../../packages/askluna-core/src/api/getOpenAIClient.ts
```

Its most likely the same issue supabase had:  https://github.com/supabase/supabase-js/issues/612
The recently resolved it.

### To Reproduce

1. create a monorepo library that uses the open api client
2. create a nextjs app
3. import the client or try to use it

you'll get this error during webpack compile.

### OS

macos

### Node version

20

### Library version

v4

**Comment by rattrayalex** [comment]
Is that an error, or just a warning? I believe you can safely ignore it (or silence it with `npm i -D encoding`, as noted in that thread). 

Supabase silenced this warning by depending on [their own fork of node-fetch](https://github.com/node-fetch/node-fetch/compare/2.x...supabase:node-fetch:2.x) which isn't something we'd like to do.
