### ISSUE TITLE
Response (completion) is always empty

### ISSUE THREAD

**Issue by polis80cy** [openai/openai-node#36]
### Describe the bug

I am trying to get the time complexity for some source code, and the response always comes back null. The call to OpenAI works, however:
![Screenshot 2022-12-23 at 12 39 34 PM](https://user-images.githubusercontent.com/14854276/209321887-e68ea1a5-3cb9-421a-971b-f7e42256e905.png)

I am doing this through a Firebase Callable Cloud function, and when I log the response, this is an example of what I typically get:
`completion.data.choices: [{"text":"","index":0,"logprobs":null,"finish_reason":"stop"}]`

Any idea what's happening here?

### To Reproduce

![Screenshot 2022-12-23 at 10 23 53 AM](https://user-images.githubusercontent.com/14854276/209300501-f7f40992-1462-4fda-9f74-cee5ec573fa0.png)

### Code snippets

```JavaScript
const { Configuration, OpenAIApi } = require("openai");
const key =  'xxxxxxxxxxxx';
const configuration = new Configuration({ apiKey: key });
const openai = new OpenAIApi(configuration);

exports.getTimeComplexity = functions.https.onCall(async (data, context) => {
    const selection = data.selection;
    if (selection.length === 0) {
        throw new functions.https.HttpsError('invalid-argument', '[getTimeComplexity] Selection must be > 0 characters long');
    }
    if (!context.auth) {
        throw new functions.https.HttpsError('failed-precondition', '[getTimeComplexity] The function must be called while authenticated.');
    }

    // Get time complexity
    openai.createCompletion({
        model: "text-davinci-003",
        prompt: selection,
        temperature: 0,
        max_tokens: 64,
        top_p: 1.0,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
        stop: ["\n"],
    }).then((completion) => {
        const timeComplexity = completion.data.choices[0].text;
        console.log(`[getTimeComplexity] Time Complexity ✅: ${timeComplexity}`);
        return { 'success': true, 'complexity': timeComplexity };
    });
});
```

### OS

macOS v12.6

### Node version

Node v16

### Library version

openai v3.1.0

**Comment by polis80cy** [comment]
Nevermind. This was my doing, apologies for the noise.

**Comment by hiwanz** [comment]
@polis80cy I'm facing the same problem, how did you fix it?

**Comment by jasonJamEther** [comment]
I am facing the same issue. What was the solution?

**Comment by hiwanz** [comment]
@jasonJamEther  if you run it over http proxy, that might be the key point, just stop proxy and try again

**Comment by polis80cy** [comment]
I don't remember really anymore, but I believe it was the way I was handling async / promises on the client side and had nothing to do with this API and/or HTTP proxies.
