### ISSUE TITLE
 Failed to minify the code from this file:    	./node_modules/openai/dist/base.js:36

### ISSUE THREAD

**Issue by zulkifleMaroof** [openai/openai-node#362]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The Version I am using for Open AI is 3.3.0.

When I run npm run build, it is giving me this error 

 Failed to minify the code from this file:    	./node_modules/openai/dist/base.js:36

Here is my package.json file

{
  "name": "loyalty",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "autoprefixer": "7.1.6",
    "axios": "^0.27.2",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "classnames": "^2.2.5",
    "css-loader": "0.28.7",
    "dotenv": "^4.0.0",
    "dotenv-expand": "4.0.1",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.5",
    "material-ui": "^0.20.1",
    "moment": "^2.20.1",
    "npm": "^6.4.0",
    "object-assign": "4.1.1",
    "openai": "^2.0.5",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "prop-types": "^15.6.0",
    "raf": "3.4.0",
    "react": "^16.2.0",
    "react-addons-shallow-compare": "^15.6.2",
    "react-bootstrap": "^0.32.1",
    "react-dates": "^16.2.1",
    "react-dev-utils": "^5.0.0",
    "react-dom": "^16.2.0",
    "react-dropzone": "^4.2.10",
    "react-dropzone-component": "^3.2.0",
    "react-facebook": "^6.0.15",
    "react-facebook-login": "^4.1.1",
    "react-fast-compare": "^2.0.2",
    "react-head": "^2.2.0",
    "react-images-uploader": "^1.2.0-rc1",
    "react-load-script": "0.0.6",
    "react-modal": "^3.1.11",
    "react-payment": "^0.1.8",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-square-hosted-fields": "^1.2.4",
    "react-stripe-checkout": "^2.6.3",
    "react-stripe-elements": "^1.6.0",
    "react-toastify": "^3.3.4",
    "recharts": "^1.0.0-beta.10",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "server": "^1.0.18",
    "square-connect": "^2.20181212.0",
    "stripe": "^6.4.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "uuid": "^3.2.1",
    "validator": "^9.4.0",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "devDependencies": {
    "react-square-cards": "^1.0.14"
  }
}

### To Reproduce

nom install openai than create build using rpm run build

### OS

macOs

### Node version

v16.18.0

### Library version

3.3.0

**Comment by rattrayalex** [comment]
Version 3.x is no longer supported, please [upgrade](https://github.com/openai/openai-node/discussions/217) to v4.
