### ISSUE TITLE
The chunk.choices item of completion stream sometimes is undefined.

### ISSUE THREAD

**Issue by MiniSuperDev** [openai/openai-node#364]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Using the readme example of chat stream.

```
part.choices 👈 undefined sometimes, so throw an error when try to access to index [0].
part.choices[0] 👈 error
```

```sh
TypeError: Cannot read properties of undefined (reading '0')
```

Is it normal that it can be undefined sometimes?
Should I check that it is not undefined before get the choice?
Or does being undefined mean some API error?
Thanks

<details>
<summary>Readme Example</summary>

```ts

async function main() {
  const stream = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [{ role: 'user', content: 'Say this is a test' }],
    stream: true,
  });
  for await (const part of stream) {
    process.stdout.write(part.choices[0]?.delta?.content || '');
  }
}
```
</details>

### To Reproduce

Use the readme example.
It doesn't happen very often, my server logs told me about it

### OS

Windows 10

### Node version

v18.17.1

### Library version

4.11.1

**Comment by MiniSuperDev** [comment]
I debug the code an this is the chunk when is undefined:

![image](https://github.com/openai/openai-node/assets/105388540/bffaf704-e34d-4458-a109-669fb17d7f5c)

**Comment by rattrayalex** [comment]
Thanks for the report; we should be throwing that error instead of yielding it as an object. 

As a workaround, you can write something like `if ('error' in chunk) throw new Error(JSON.stringify(chunk.error))`

**Comment by rattrayalex** [comment]
This was fixed in https://github.com/openai/openai-node/releases/tag/v4.12.2
