### ISSUE TITLE
Help me to createImageVariation Fromhttps://url

### ISSUE THREAD

**Issue by in-ceptive** [openai/openai-node#38]
### Describe the feature or improvement you're requesting

  #Working Below Code.
  let readStream = fs.createReadStream("image.png");
  response = await openai.createImageVariation(readStream, 1, "1024x1024");

   #Not Working Below Code. 
   let readStream = https.get("https://storage.googleapis.com/inceptivestudio/1672042338704.png", (stream) => {
     return stream;
   });
   response = await openai.createImageVariation(readStream, 1, "1024x1024");

**Comment by rattrayalex** [comment]
Please try our [upcoming v4](https://github.com/openai/openai-node/discussions/182) of this library and let us know if you run into any issues with this; we've overhauled file uploads and you should find them easier to use.
