### ISSUE TITLE
files.create() requires purpose param, even though it's supposed to be used only for specifying 'fine-tuning'

### ISSUE THREAD

**Issue by xml** [openai/openai-node#387]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When calling: 

`const podcast = await openaiClient.files.create({ file: fs.createReadStream('[path]')}); // note: no 'purpose' prop` 
then: 
`await openaiClient.audio.transcriptions.create({file: podcast})`

... the API responds with: 

`BadRequestError: 400 'purpose' is a required property` or (if attempting values other than 'fine-tune'): `BadRequestError: 400 'other' is not one of ['fine-tune'] - 'purpose'`

... even though the comments on files.ts say: _"The intended purpose of the file. Currently, only "fine-tune" is supported."_. This strongly suggests that `purpose` should be an optional param, given all the other uses beyond fine-tuning. But the `?` is conspicuously missing from the type declarations in files.ts. And the API clearly requires it. So, either: 

1. It needs to become truly optional, all the way through to the API
2. Or, the comments need to explain: A. it's required B. what the viable alternative values are, beyond "fine-tune"
    - And, TS/JS should enforce the requirement on the initial call to `files.create`

### To Reproduce

Call `client.files.create({ file: fs.createReadStream('[path]')});` without a defined `purpose` param, then call 

### Code snippets

```JavaScript
async function main() {
  console.log('About to read file and obtain transcription... ')
  const podcast = await openaiClient.files.create({ file: fs.createReadStream('[valid path]')});
  const transcript = await openaiClient.audio.transcriptions.create({
    model: 'whisper-1',
    file: podcast,
    language: 'en',
    prompt: promptText,
    response_format: 'verbose_json' // 'vtt' file should include time-stamps
  });
```

Response: 
```
BadRequestError: 400 'purpose' is a required property
    at APIError.generate (file://...node_modules/openai/error.mjs:39:20)
    at OpenAI.makeStatusError (file://...node_modules/openai/core.mjs:238:25)
    at OpenAI.makeRequest (file://...node_modules/openai/core.mjs:277:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file://...whisperPOC.mjs:9:17 {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '81829c6dc8442896-IAD',
    connection: 'keep-alive',
    'content-length': '145',
    'content-type': 'application/json',
    date: 'Wed, 18 Oct 2023 17:48:31 GMT',
    'openai-organization': 'user-OMITTED',
    'openai-processing-ms': '185',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-request-id': 'e3d9f3c6405aae82a421625db8885bf5'
  },
  error: {
    message: "'purpose' is a required property",
    type: 'invalid_request_error',
    param: null,
    code: null
  },
  code: null,
  param: null,
  type: 'invalid_request_error'
}
```
```


### OS

macOS 14

### Node version

v18.8

### Library version

4.12.4

**Comment by rattrayalex** [comment]
You want this:
```ts
await openaiClient.audio.transcriptions.create({file: fs.createReadStream('[path]')})
```

The file you pass to a transcription isn't the ID of a file object in the OpenAI API, but an actual file you upload.

If any OpenAI docs/examples were misleading on this, please report them at https://community.openai.com
