### ISSUE TITLE
Whisper translate other languages into english?

### ISSUE THREAD

**Issue by kenhuang1964** [openai/openai-node#395]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I realized that the open-ai node implementation of whisper-ai doesn't support taking audio from another language and then translating it into English. It only supports the same language transcription. Can someone please add that feature? It is available in python.

**Comment by rattrayalex** [comment]
This is available with `openai.audio.translations.create()`
