### ISSUE TITLE
Light/dark mode screen rapidly flashing back and forth

### ISSUE THREAD

**Issue by catalano2105** [openai/openai-node#40]
### Describe the bug

I was using open chat to make a few different calendars for this year, in the process I had multiple tabs of a new chat open, this way I was able to have one for the entire year, and one for the day-to-day routine, when I got to make the routine, however, I decided to toggle the screen into dark mode as it has been getting late, then upon doing so, the screen rapidly started flashing between the two as i forgot to close the other tabs, this happened for each tab. I closed the first 3 and the problem still seems to persist. 

### To Reproduce

1. open a new chat in multiple tabs, two should work but I had 3 to 4 open working on multiple projects.
2. have the first tabs in light mode, then toggle the third onto dark mode. It was fast to occur, and the button itself should be flashing making it hard to click in an effort to fix
3. enjoy your broken open chat screen as it annoyingly flashes while you try to be productive.
4. try to close the first two tabs and see if you can fix the third, it won't but you can try, you can even try closing the third. I am not sure how long it will last but after 30 seconds of trying anything I could think of I decided to report this bug
5. opening open chat is now taking ages to load, probably because the flickering has not yet stopped
6. after finally loading the flickering has slowed, but still persists consistently at least on this device.

### OS

chrome

### Node version

December 15th version

### Library version

v3.0.1 is what was filled in as a example of this text box, but I could not currently find it.

**Comment by schnerd** [comment]
Great ideas! This repository is not for chat-gpt ideas unfortunately, so I'm going to close this, but will share with the team.
