### ISSUE TITLE
Chat bot stopping in the middle of generating text

### ISSUE THREAD

**Issue by catalano2105** [openai/openai-node#41]
### Describe the bug

I have been using this chatbot to keep track of schedules for a yearly calendar and for keeping/organize notes. When making a calender or really anything that requires a decent amount of typing, the chatbot will stop mid-sentence. This is fixable when you say "continue" or "you stopped halfway" etc. but it is very tedious to keep typing this halfway through a length of text. This is especially annoying when you tell it to put it into a copyable format, and thus the stop results in having to copy multiple things, and editing a few lines so it is coherent where I paste the text into.organizing

### To Reproduce

1. Tell it to write out every day, each week, or monthly benchmarked calendar of the year. It will probably say that it is pointless to write out each individual day, might do the same for every week, but for months it can. 
2. with the calendar it has outlined, tell it to add benchmark dates like all key holidays, maybe put in a few birthdays of people you know, and just make an overbooked sort of calendar. 
3. If it manages to do that without stopping halfway, tell it to put it into a copyable format, or keep adding dates, and make the time slots more defined. Eventually, it will stop halfway through a sentence or forget its typical ending of "I hope this information provided fulfills your request" 
4. Tell it to continue until it gives the rest of the code, it's nothing system-breaking, but very annoying to do each time you want to revise a huge selection of text or add one too many days to your filled calendar.

### OS

chrome

### Node version

December 15th version

### Library version

v3.0.1 is what was filled in as a example of this text box, but I could not currently find it.

**Comment by drorm** [comment]
Ran into this.
Add   max_tokens: 1000,
```
max_tokens: 1000
```
to your code (or whatever number you want) and it should solve this issue.
The API is not well documented in the README, but node_modules/openai/api.ts has some good info.

**Comment by schnerd** [comment]
Great ideas! This repository is not for chat-gpt ideas unfortunately, so I'm going to close this, but will share with the team.
