### ISSUE TITLE
Model endpoint compatibility retrieval 

### ISSUE THREAD

**Issue by AmirAmArA** [openai/openai-node#412]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I stumbled upon the need for Models who have chat completion capability, and I didn't seem to find something similar in the context, 
so, if there were an API where I could request all models that are compatible with a specific endpoint, that would be nice :)

**Comment by rattrayalex** [comment]
Thanks for the suggestion – please share API feedback and ideas at https://community.openai.com 😄
