### ISSUE TITLE
Whisper Support for any ReadStream (any Readable)

### ISSUE THREAD

**Issue by nicolopadovan** [openai/openai-node#414]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Whenever using the Whisper model (`audio.transcriptions`), it is impossible to use any kind of readable that differs from a File System Readable.
The reason behind it seems to be the extension of `Readable`, `FsReadSteam`, which requires a `path` parameter.
It is not possible to use a dummy inside this parameter. I could not examine the source code thoroughly, but the `path` parameter does not seem to be used particularly in the code.
This disables any kind of streaming from a service external from the server into the Whisper API: the files must first be downloaded into the File System of the server, and once they are downloaded they can be streamed to the API.
This behaviour is totally possible using `axios` and `form-data`, bypassing the NodeJS library.

### To Reproduce

(Example using Firebase Storage inside serverless Firebase Functions)

1. Create a file
2. Upload it to an external service (in example, Firebase Storage)
3. Try streamlining it to OpenAI API

```javascript
const bucket = storage.bucket(bucketName);
const file = bucket.file(fileName);
const readStream = file.createReadStream();

const apiKey: string = openaiAPI.value();
const openai = new OpenAI({
    apiKey: apiKey,
});

const completion = await openai.audio.transcriptions.create({
    file: readStream,
    model: "whisper-1",
});
```

### Code snippets

```JavaScript
const bucket = storage.bucket(bucketName);
const file = bucket.file(fileName);
const readStream = file.createReadStream();

const apiKey: string = openaiAPI.value();
const openai = new OpenAI({
    apiKey: apiKey,
});

const completion = await openai.audio.transcriptions.create({
    file: readStream,
    model: "whisper-1",
});
```

### OS

Linux (Google Cloud Functions)

### Node version

18

### Library version

4.11.1

**Comment by rattrayalex** [comment]
@nicolopadovan you need to pass the `file` to [the `toFile()` helper](https://github.com/openai/openai-node#file-uploads) so that you can assign it a filename, which the API requires:

```ts
import {OpenAI, toFile} from 'openai'

const bucket = storage.bucket(bucketName);
const file = bucket.file(fileName);

const openai = new OpenAI({
    apiKey: apiKey,
});

const completion = await openai.audio.transcriptions.create({
    file: await toFile(file, "myfile.mp3"),
    model: "whisper-1",
});
```

`toFile` accepts `Readable` (and any NodeJS `ReadableStream`).

Note that we do plan to add support for a web `ReadableStream` to `toFile()` in the near future (NodeJS `ReadableStream` is different from a web `ReadableStream`). When we do, I'll try to make it more clear that `toFile` accepts a `ReadableStream` of either flavor.

**Comment by nicolopadovan** [comment]
> @nicolopadovan you need to pass the `file` to [the `toFile()` helper](https://github.com/openai/openai-node#file-uploads) so that you can assign it a filename, which the API requires:
> 
> ```ts
> import {OpenAI, toFile} from 'openai'
> 
> const bucket = storage.bucket(bucketName);
> const file = bucket.file(fileName);
> 
> const openai = new OpenAI({
>     apiKey: apiKey,
> });
> 
> const completion = await openai.audio.transcriptions.create({
>     file: await toFile(file, "myfile.mp3"),
>     model: "whisper-1",
> });
> ```
> 
> `toFile` accepts `Readable` (and any NodeJS `ReadableStream`).
> 
> Note that we do plan to add support for a web `ReadableStream` to `toFile()` in the near future (NodeJS `ReadableStream` is different from a web `ReadableStream`). When we do, I'll try to make it more clear that `toFile` accepts a `ReadableStream` of either flavor.

Does it maintain the `Stream` capabilities? 
Or does it instead download the full file and then send it as a new stream?

**Comment by rattrayalex** [comment]
It currently does buffer the full file into memory before sending it. I can certainly understand why you'd want to stream directly.

**Comment by nicolopadovan** [comment]
> It currently does buffer the full file into memory before sending it. I can certainly understand why you'd want to stream directly.

May I open this issue back or create a feature request for the direct streaming functionality?

**Comment by rattrayalex** [comment]
A separate issue would be best, thank you!
