### ISSUE TITLE
Self-referencing absolute import

### ISSUE THREAD

**Issue by transitive-bullshit** [openai/openai-node#415]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

In this line, which seems to be auto-generated by Stainless (cc @rattrayalex), the `openai` package is self-referencing itself, which may happen to work in most cases, but seems like very bad behavior to rely on more generally. This relies on the Node.js package import semantics, as opposed to using a relative import to reference something within the package.

https://github.com/openai/openai-node/blob/0e67361a5faa2bc1b2c0c3ff1de982a2e66ab0cc/src/index.ts#L8

### To Reproduce

Changing this line to a relative import fixes the issue.

### OS

macOS

### Node version

any node version

### Library version

4.14.2

**Comment by rattrayalex** [comment]
Heya @transitive-bullshit ! Can you share a repro of an issue you're seeing? 

We post-process many of our imports for different environments; could you be importing `from 'openai/src/…'` in your code instead of from `'openai/…'` perhchance?

**Comment by rattrayalex** [comment]
Ah, looking into the context of https://github.com/openai/openai-node/issues/415#:~:text=Fix%20absolute%20import%20in%20openai%2Dtypes%20dexaai/openai%2Dfetch%2333, I'm going to close this.

This package [makes extensive use of self-referential imports](https://github.com/search?q=repo%3Aopenai%2Fopenai-node+%22from+%27openai%2F%22&type=code), and works in a wide variety of runtimes. Copying the files into another project is not a supported use-case.

**Comment by transitive-bullshit** [comment]
Thanks @rattrayalex.

Regardless of the context, I've never seen self-referential imports in the source files of public npm packages, and it seems like a bad practice (though I can't quantify that aside from it setting off my spidey sense lol). Maybe consider switching to using TS paths in the auto-generated code instead of self-referential imports?

```json
"compilerOptions": {
    "paths": {
      "~/*": ["./src/*"]
    }
  }
```

**Comment by rattrayalex** [comment]
Thanks for the suggestion Travis!
