### ISSUE TITLE
Use Axios as custom Http agent

### ISSUE THREAD

**Issue by Jakub-Vacek** [openai/openai-node#417]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Can I use Axios instance as Http Agent in ^V4?
I need custom retry policies and this was possible in V3. I was not able to use Axios in `httpAgent` parametr in V4 constructor. Can you please provide code snippet how to use it?

Thanks👍

**Comment by rattrayalex** [comment]
You can't provide a drop-in axios client, but you can provide your own `fetch` client; we've [just added documentation](https://github.com/openai/openai-node/pull/420/files#customizing-the-fetch-client) on how to do that.

For your use-case, it might look something like this:

```ts
import OpenAI from 'openai'

const client = new OpenAI({
  maxRetries: 0,
  fetch(url: RequestInfo, init?: RequestInit): Response {
    return fetch(url, init).then(r => { 
      if (r.status >= 400) { 
        throw APIError.generate(r.status, await r.json(), undefined, r.headers)
      }
      return r;
    }).catch(err => {
      return myRetryLogic(err, url, init);
    })
  }
})
```

I hope this is helpful!

**Comment by rattrayalex** [comment]
Out of curiosity, how are you trying to customize the retry logic, and why?
