### ISSUE TITLE
Information of updates upon request

### ISSUE THREAD

**Issue by catalano2105** [openai/openai-node#42]
### Describe the feature or improvement you're requesting

It would be nice for the ability to ask open ai what new features it has. 

### Additional context

It can already tell you what the ai its self is capable of, but it seems oblivious to any new changes in updates. It would be nice if upon request it said new bug fixes, features added, and current version model. This would help to know if any issues or quality of life improvements have changed without having to play around to see what works. I know this information is probably already listed somewhere, but It would be nice for even just a link to the information upon the request to the ai.

**Comment by schnerd** [comment]
Great ideas! This repository is not for chat-gpt ideas unfortunately, so I'm going to close this, but will share with the team.
