### ISSUE TITLE
Ability to copy without having to request new format

### ISSUE THREAD

**Issue by catalano2105** [openai/openai-node#43]
### Describe the feature or improvement you're requesting

The ability to copy was something I found lacking at first, but as I played around a bit more I remembered that this thing can do basically anything, so I told it to put the text it generated into a copy-abel format. Usually, this works and if not I can say put it into code format. It would however be more convenient to have a copy button right there at the top right corner, below the prompt you entered; this way you would not have the same thing twice if you needed, for example, a record of notes. It would also mean fewer things to do for the ai as you would not need to request different formats to do one thing. I am aware I could highlight and copy manually, but sometimes text can get lengthy when fleshing out ideas.

### Additional context

This is mostly used for lengthy text generation, and because for the time being you occasionally have to tell the ai to continue what it was typing, it would greatly increase efficiency when moving stuff into a notes folder on EverNote. This is not something that is totally undoable, but adding this feature which the code format already has would make things a bit more complete and natural for creative and productive work.

**Comment by schnerd** [comment]
Great ideas! This repository is not for chat-gpt ideas unfortunately, so I'm going to close this, but will share with the team.
