### ISSUE TITLE
Permissions object not being returned with `openai.models.list().withResponse()`

### ISSUE THREAD

**Issue by microsoftbuild** [openai/openai-node#434]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [x] This is an issue with the Node library

### Describe the bug

Up until last day the `openai.models.list().withResponse()` call was returning the `permissions` object for each model. However starting today, the permissions object is no longer being returned.

Our app uses this object to programmatically differentiate between various kinds of models.

### To Reproduce

Initialize the openai simply run:
```ts
import OpenAI from "openai";
const oai = new OpenAI({
            apiKey: apiKey,
            organization: org,
        });
async function main() {
  const list = await oai.models.list();

  for await (const model of list) {
    console.log(model);
  }
}
main();
```

and look at the models returned.

### OS

macOS

### Node version

v18.16.0

### Library version

openai@4.15.4

**Comment by rattrayalex** [comment]
The undocumented response field `.permissions` has been removed from the API. We're sorry for the inconvenience.
