### ISSUE TITLE
gpt-4-vision-preview: Validation error for Request body -> functions extra fields not permitted (type=value_error.extra)

### ISSUE THREAD

**Issue by elcous** [openai/openai-node#438]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

`Error during openai.createChatCompletion: Error: 400 1 validation error for Request
body -> functions
  extra fields not permitted (type=value_error.extra)
    at APIError.generate (error.ts:66:14)
    at OpenAI.makeStatusError (core.ts:358:21)
    at OpenAI.makeRequest (core.ts:416:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatCompletionStream._createChatCompletion (ChatCompletionStream.ts:96:20)
    at async ChatCompletionStream._runChatCompletion (AbstractChatCompletionRunner.ts:426:12)
    `

gpt-4-vision-preview doesn't work with streaming and functions.

### To Reproduce

const callParams = {
        model,
        messages: api_messages,
        top_p: 0.1,
        stream: true,
      };
      
const stream = await this.openai.beta.chat.completions.stream(callParams, {
        signal: this.abortController.signal,
      });

### OS

macOS

### Node version

20.6

### Library version

4.16.1

**Comment by rattrayalex** [comment]
Sorry, this repo is for the TypeScript SDK - for help using the API, please try community.openai.com or the OpenAI Discord channel.

**Comment by elcous** [comment]
> Sorry, this repo is for the TypeScript SDK - for help using the API, please try community.openai.com or the OpenAI Discord channel.

that was the point, SDK works well with 'gpt-4-1106-preview', but  'gpt-4-vision-preview' for simple query like "hello" fails when functions included with streaming. But works fine without streaming.

**Comment by rattrayalex** [comment]
Can you share a full code example? What I see above doesn't include functions from what I can see...

**Comment by rattrayalex** [comment]
In any case, the error you're seeing is coming from the API, not the SDK.

**Comment by semanser** [comment]
I'm getting the same error when using gpt-4-vision-preview. "BadRequestError: 400 1 validation error for Request"

Here is a full demo:
```
import OpenAI from "openai";

const openai = new OpenAI();

async function main() {
  const response = await openai.chat.completions.create({
    model: "gpt-4-vision-preview",
    response_format: "json",
    messages: [
      {
        role: "system",
        content: "Return answer in JSON format",
      },
      {
        role: "user",
        content: [
          { type: "text", text: "What’s in this image?" },
          {
            type: "image_url",
            image_url:
              "https://assets2.devourtours.com/wp-content/uploads/slice-of-tortilla-de-patatas-on-white-plate-Cropped-1.jpeg",
          },
        ],
      },
    ],
  });
  console.log(response.choices[0]);
}
main();
```

**Comment by semanser** [comment]
For anyone who finds this issue via google.

Official OpenAI [response](https://community.openai.com/t/how-do-i-use-the-new-json-mode/475890/39):

JSON mode is supported for gpt-4-1106-preview but not for gpt-4-vision-preview, as of Nov 7th.
