### ISSUE TITLE
BadRequestError: 400 Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.

### ISSUE THREAD

**Issue by shihfu** [openai/openai-node#439]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [ ] This is an issue with the Node library

### Describe the bug

I am receiving the following error message when attempting to use the new `JSON mode` with `gpt-3.5-turbo`.

`BadRequestError: 400 Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.`

Related doc here: https://platform.openai.com/docs/guides/text-generation/json-mode

### To Reproduce

1. Update `openai` npm package to latest `4.16.1`.
2. Send following request: 
```
await openai.chat.completions.create({
    messages: [
      {
        role: 'system',
        content: `...`
      }
    ],
    model: 'gpt-3.5-turbo',
    temperature: 0.1,
    max_tokens: 1024,
    response_format: { type: 'json_object' }
  });
```

### OS

macOs

### Node version

v21.1.0

### Library version

openai v4.16.1

**Comment by rattrayalex** [comment]
`response_format: 'json_object'` is only available in new models: `gpt-4-1106-preview` or `gpt-3.5-turbo-1106`

[See the docs for more](https://platform.openai.com/docs/guides/text-generation/json-mode).

**Comment by shihfu** [comment]
I could have sworn I saw that `gpt-3.5-turbo` was supported in the docs, but thanks nonetheless 👍

**Comment by archasek** [comment]
Seems that both point to `gpt-3.5-turbo-1106`, so I supposes it should be supported?

![image](https://github.com/openai/openai-node/assets/2247211/1a20eb37-2821-4c79-9986-20693a2ad47d)
