### ISSUE TITLE
Search Option for previous conversations, groupings for similar chats

### ISSUE THREAD

**Issue by catalano2105** [openai/openai-node#44]
### Describe the feature or improvement you're requesting

It would be amazingly helpful if when exceeding 5 saved conversations, having 6 and up would grant a search bar in the chat selection. This way if you need to pull text or ideas from previous chats, you can simply search not just titles, but keywords. For example, you might ask in a previous conversation about planning out a goal. Maybe after talking and problem-solving keeping your resolutions you ask for a book recommendation or source to learn more from. A week later you are on amazon and you think maybe you want that book the ai recommended. So now the previous chat which was titled "new years resolution goals" will come up when typing in new Year, book/books, or the title of the book such as atomic habits. To take this idea further you could ask to group conversations, maybe you have three priorities for the year beyond general goals and plans, one working out, the second one diet, and the third general goals/habits. You could then group these into one titled New Year. Perhaps the ai would do this finding similar context between threads but even a manual option would be nice.

### Additional context

In using the ai so much for general questions, having new ideas, or simply keeping a branching idea separate from the previous topic, my prior chat selection box has the need a lot of scrolling when pulling out prior topics. This would greatly help out when recalling a record of past conversations.

**Comment by schnerd** [comment]
Great ideas! This repository is not for chat-gpt ideas unfortunately, so I'm going to close this, but will share with the team.
