### ISSUE TITLE
Bug Report: Typo in TypeScript Declaration

### ISSUE THREAD

**Issue by Maik0909** [openai/openai-node#440]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

**Description:**
There's a typo in the `AssistantToolsRetrieval` interface of the `AssistantCreateParams` namespace. The property `type` is misspelled as `'retreival'` instead of the correct `'retrieval'`.

**Impact:**
The typo may cause TypeScript errors and misconfigurations in the codebase.

**Fix:**
Correct the spelling to `'retrieval'` in the interface definition.

### To Reproduce

1. Navigate to the `AssistantCreateParams` namespace in the TypeScript declaration file.
2. Observe the incorrect spelling of the `type` property within the `AssistantToolsRetrieval` interface.

### OS

macOS

### Node version

20.9.0

### Library version

4.16.0

**Comment by rattrayalex** [comment]
This has been [fixed](https://github.com/openai/openai-node/pull/437) and released.

**Comment by Maik0909** [comment]
👍
