### ISSUE TITLE
New models are missing

### ISSUE THREAD

**Issue by MarcAMartin** [openai/openai-node#444]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

New models are missing

https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by rattrayalex** [comment]
Thanks, we'll have this addressed shortly.

**Comment by jerrycool123** [comment]
I've noticed that new GPT-4 models (`gpt-4-1106-preview` and `gpt-4-vision-preview`) have been added to the model list, but the new GPT-3.5 model, `gpt-3.5-turbo-1106`, hasn't been included.

**Comment by rattrayalex** [comment]
Sorry for the continued delay; this will land after https://github.com/openai/openai-openapi/pull/117 or equivalent is merged.
