### ISSUE TITLE
Getting response headers for rate limit tracking

### ISSUE THREAD

**Issue by minons1** [openai/openai-node#445]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Previously in v3, I am able to track my current usage and token limit since the chat completion response is an axios response, so I can use `response.headers` like so, but now chat completion response is `OpenAI.Chat.Completions.ChatCompletion` which representing `response.data` in v3 only

How I can get the same behaviour in v4?

Thank you in advance

```
// headers that i'm using
x-ratelimit-remaining-tokens
x-ratelimit-remaining-requests
x-ratelimit-reset-tokens
x-ratelimit-reset-requests
```

### To Reproduce

1. Call create chat completion function
2. Response does not contains header

### Code snippets

```JavaScript
import OpenAI from 'openai'

const ai = new OpenAI()

const response = await ai.chat.completions.create({
  // the payload
})

const headers = response.headers['x-ratelimit-remaining-tokens'] // errored
```

### OS

macOS

### Node version

Node v18.16.1

### Library version

openai v4.16.1

**Comment by rattrayalex** [comment]
This library provides `.asResponse()` and `.withResponse()` for this purpose:
https://github.com/openai/openai-node/#accessing-raw-response-data-eg-headers

```ts
const { data: chatCompletion, response: raw } = await openai.chat.completions
  .create({ messages: [{ role: 'user', content: 'Say this is a test' }], model: 'gpt-3.5-turbo' })
  .withResponse();

console.log(raw.headers.get('x-ratelimit-remaining-tokens'));
console.log(chatCompletion);
```

**Comment by minons1** [comment]
I see, I think it is better to be described in v3 to v4 migration guide, because I don't get the information there
https://github.com/openai/openai-node/discussions/217

Thank you @rattrayalex

**Comment by rattrayalex** [comment]
Thanks for the suggestion, updated!

**Comment by KhaledAbdelfattah** [comment]
Hi @minons1 @rattrayalex I'm currently running to this issue, I used withResponse, but I don't get headers back. 
<img width="780" alt="image" src="https://github.com/openai/openai-node/assets/31597639/3fa803ca-9953-4cf2-a47c-259774ce27a8">

the output:
<img width="1476" alt="image" src="https://github.com/openai/openai-node/assets/31597639/e093a6ce-53cf-45a6-900d-c866c82a5ade">

**Comment by rattrayalex** [comment]
How are you instantiating the client? What if you print this?
```ts
logger.info(`raw response: ${response}`)
logger.info(`raw headers: ${JSON.stringify(response.headers)}`)
```

**Comment by KhaledAbdelfattah** [comment]
const OPEN_API_REVIEW = new OpenAI({
    apiKey: process.env["OPENAI_REVIEWS_API_KEY"]!,
});
and compile error with logger.info(`raw headers: ${JSON.stringify(response.headers)}`)
<img width="564" alt="image" src="https://github.com/openai/openai-node/assets/31597639/ec83507a-f824-4a10-a0b5-a73cc4a288d3">
the will give me:
logger.info(`raw headers: ${JSON.stringify(response.headers)}`)
<img width="542" alt="image" src="https://github.com/openai/openai-node/assets/31597639/d3a6c1af-9363-48d1-ba86-9ed22989ce4a">

**Comment by rattrayalex** [comment]
Sorry, that should have been:

```ts
const headers = Object.fromEntries(response.headers);
logger.info(raw headers: ${JSON.stringify(headers, null, 2)})
```

**Comment by KhaledAbdelfattah** [comment]
property header doesn't exist:

<img width="694" alt="image" src="https://github.com/openai/openai-node/assets/31597639/a1dc97b0-d10b-4681-bbe6-c5b69260858e">

**Comment by rattrayalex** [comment]
You need to add `import "openai/shims/node"` (assuming you're using Node) before your first import `from 'openai'` (or change your tsconfig's moduleResolution setting to `NodeNext`).

**Comment by KhaledAbdelfattah** [comment]
Thank you so much! Both methods worked, It seemed like typescript resolve issue, but I'm not I totally understand it. could you elaborate or provide some links to do some reading about it.
