### ISSUE TITLE
OpenAI.Beta.AsssitantDeleted typo

### ISSUE THREAD

**Issue by transitive-bullshit** [openai/openai-node#447]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

small typo `AsssitantDeleted` should be `AssistantDeleted` in generated types

### To Reproduce

latest code on github

### OS

macos

### Node version

any node

### Library version

latest

**Comment by rattrayalex** [comment]
Thank you for catching that @transitive-bullshit ! Will fix shortly.

**Comment by rattrayalex** [comment]
Released a few days ago in https://github.com/openai/openai-node/releases/tag/v4.16.2
