### ISSUE TITLE
Creating a CSV File and attaching to an Assistant returns "Unsupported file ... type: application/octet-stream"

### ISSUE THREAD

**Issue by AaronFriel** [openai/openai-node#459]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Creating a file, whether via the Node API in this library, via the web UI, or via CURL / manually written POST, succeeds, however attaching the file to the Assistant fails with "Unsupported file ... type: application/octet-stream". 

It appears that the Node library or API, and likely the web UI library implementation (also this library?), disregards the MIME type explicitly set. There is no way to force a large CSV to be "application/csv".

### To Reproduce

1. Upload a CSV file via the Assistant playground or the code snippets below
2. Attach the file to the assistant (this will occur as part of step 1 in the web UI)
3. Observe error

### Code snippets

```JavaScript
const filedata = await fs.readFile(filename);

  const blob = new File([new Blob([filedata])], filename, {
    type: 'application/csv',
  });

  const file = await client.files.create({
    file: blob,
    purpose: 'assistants',
  });

  await client.beta.assistants.files.create(assistantId, {
    file_id: file.id,
  });


Or more directly, using a formdata and POST:

```ts

  const formData = new FormData();
  formData.append(
    'file',
    new File(
      [
        new Blob([filedata], {
          type: 'application/csv',
        }),
      ],
      filename,
    ),
  );
  formData.append('purpose', 'assistants');
  console.log({ keys: [...formData.keys()] });

  const encoder = new FormDataEncoder(formData);
  const readable = Readable.from(encoder);
  const body = new MultipartBody(readable);
  const headers = {
    ...encoder.headers,
    'Content-Length': encoder.contentLength,
  };

  const response: { id: string } = await client.post('/files', {
    body,
    headers,
  });
```
```


### OS

n/a

### Node version

Node v20.x

### Library version

openai v4.16.1

**Comment by rattrayalex** [comment]
Hey there @AaronFriel . This repo is intended just for issues specific to the Node SDK, not the API (which it sounds like this is), but I've passed your feedback along. 

Does your `filename` end with `.csv` btw? The script doesn't show. It may also help if you could provide a request ID.

**Comment by AaronFriel** [comment]
It does end with .csv - though I unfortunately have had no luck using CSV or JSON files with the Assistants API.

**Comment by AaronFriel** [comment]
Is there a public issue tracker for OpenAI issues like this anywhere? It would be great if I could link internal GitHub issues to issues like this.

**Comment by RobertCraigie** [comment]
I think you're looking for the developer forum! https://community.openai.com/
