### ISSUE TITLE
JSON mode support missing

### ISSUE THREAD

**Issue by jordanful** [openai/openai-node#461]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

The OpenAI completion endpoint [now supports JSON mode](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) on the request. It'd be great to have support for this param.

**Comment by RobertCraigie** [comment]
This is supported, are you on the latest version?

**Comment by jordanful** [comment]
I am, but I guess it's not clear how to pass this param in this library. Perhaps an update to the docs could help.

**Comment by Riley-Brown** [comment]
I am on the latest version 4.16.2 and am getting validation errors trying to use `response_format: {type: 'json_object'}` with `model: 'gpt-4-vision-preview'`

Response: 

```ts
{
  error: {
    code: null,
    message:
      '1 validation error for Request\nbody -> response_format\n  extra fields not permitted (type=value_error.extra)',
    param: null,
    type: 'invalid_request_error',
  },
}
```

Is the new JSON mode not supported with the vision model?

**Comment by cmmartin** [comment]
> Is the new JSON mode not supported with the vision model?

Correct. It's not supported in the vision model.
