### ISSUE TITLE
How to use stream with function call

### ISSUE THREAD

**Issue by user080975** [openai/openai-node#465]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I'm using the `openai.chat.completions.create` call to send messages with functions like this:

`const response = await openai.chat.completions.create({
  model: "gpt-4-1106-preview",
  messages: messages,
  tools: tools,
  tool_choice: "auto",
  stream: true
});
console.log(response)`

If I set `stream: false` then the function call works but regular messages no longer stream back. 

If I set `stream: true` then I get this error:

`Stream {
  iterator: [AsyncGeneratorFunction: iterator],
  controller: AbortController { signal: AbortSignal { aborted: false } }
}`

How can I ensure that message streaming function still works but function calls also work as well?

**Comment by rattrayalex** [comment]
I'm not sure what the issue or fix was here, but using the runTools helper (documented in the readme) works well with stream: true and may prove useful to you.
