### ISSUE TITLE
new `response_format` field not permitted with `gpt-4-vision-preview`

### ISSUE THREAD

**Issue by Riley-Brown** [openai/openai-node#469]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Trying to use the new JSON mode on the latest version `4.16.2` with model `gpt-4-vision-preview` is returning a validation error

```ts
{
  error: {
    code: null,
    message:
      '1 validation error for Request\nbody -> response_format\n  extra fields not permitted (type=value_error.extra)',
    param: null,
    type: 'invalid_request_error',
  },
}
```

### To Reproduce

1. Call chat completion method with response format property

```ts
const response = await openAI.chat.completions
  .create({
    model: 'gpt-4-vision-preview',
    max_tokens: 4048,
    temperature: 0,
    seed: 0,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content:
          'Summarize this image. Make sure your response is in valid JSON format',
      },
      {
        role: 'user',
        content: [
          {
            type: 'image_url',
            image_url: {
              url: `data:image/png;base64,${imageBuffer.toString( 'base64')}`,
            },
          },
        ],
      },
    ],
  })
```

### OS

PopOS

### Node version

18.14.2

### Library version

4.16.2

**Comment by harshanas** [comment]
I also had this issue and found out that the "JSON Mode" is only supported for the `gpt-4-1106-preview` and `gpt-3.5-turbo-1106`

Quoted from Documentation:

> To prevent these errors and improve model performance, when calling gpt-4-1106-preview or gpt-3.5-turbo-1106, you can set [response_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) to { "type": "json_object" } to enable JSON mode. When JSON mode is enabled, the model is constrained to only generate strings that parse into valid JSON.

Reference : [OpenAI Documentation](https://platform.openai.com/docs/guides/text-generation/json-mode)

**Comment by rattrayalex** [comment]
That's correct, that model doesn't support that feature yet.

**Comment by grabastart** [comment]
@rattrayalex cc @harshanas for the BETA Assistants it seems a showstopper. 

Here's a sample call to a named assistant.thread from curl on a Windows 10 terminal:
curl -X POST "https://api.openai.com/v1/threads/thread_Ko6iamCFlbDK1Osdksdj/runs" -H "Authorization:Bearer {myapiKey}" -H "Content-Type:application/json" -H "OpenAI-Beta:assistants=v1" -d "{\"assistant_id\": \"asst_qJ5u2DJHUPuBYOZqsd\", \"messages\": [{\"role\": \"user\", \"content\": \"tell me a bar joke.\"}] }"

Comment: of course myapKey is the actual key, not dummy pseudocode here.

Additional info:  { model:gpt-3.5-turbo }

Attempt to add the "response_format" attribute resulted in two errors vs one error reported above.

curl -X POST "https://api.openai.com/v1/threads/thread_Ko6iamCFlbDK1Osdksdj/runs" -H "Authorization:Bearer myapiKey" -H "Content-Type:application/json" -H "OpenAI-Beta:assistants=v1" -d "{\"assistant_id\": \"asst_qJ5u2DJHUPuBYOZqsd\", \"messages\": [{\"role\": \"user\", \"content\": \"tell me a bar joke.\"}], \"response_format\": {\"type\": \"json_object\"}}"
