### ISSUE TITLE
"Publish to Deno" failing

### ISSUE THREAD

**Issue by ChuckJonas** [openai/openai-node#476]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The github action to publish to deno is [currently failing in the pipeline](https://github.com/openai/openai-node/actions/runs/6816118401/job/18536724709).

Based on the logs, it seems like it's failing to connect to the [deno-build repo](https://github.com/openai/openai-deno-build).

### To Reproduce

na

### OS

na

### Node version

na

### Library version

na

**Comment by rattrayalex** [comment]
Thanks for the report – we're aware of this and working to configure our infrastructure to enable automatic deno releases.
