### ISSUE TITLE
No way to import types with Deno

### ISSUE THREAD

**Issue by ChuckJonas** [openai/openai-node#477]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Based on the docs, this library exposes the Request/Response types via the ["default" namespace](https://deno.land/x/openai@v4.16.1/mod.ts?s=default).

However, if I try to use the imports in my code, I get an error: `Identifier expected.`

<img width="665" alt="chatCompletion_ts_—_ccc-private-gpt" src="https://github.com/openai/openai-node/assets/5217568/54e17d1a-15f9-496c-8c29-776f52e72ac4">

I'm not 100% but it seems like maybe this is a reserved keyword that Deno doesn't support having as a namespace?

### To Reproduce

1. create deno project
1. install v4.16.1
1. add this code:
```
import { type default } from "https://deno.land/x/openai@v4.16.1/mod.ts";
const { ChatCompletion } = default;
```
[Code Sandbox Link](https://codesandbox.io/p/sandbox/nice-easley-7dt7y4?file=%2Findex.ts%3A2%2C36) (you might have to start typing to see error)

### OS

osx

### Node version

deno 1.38.0

### Library version

v4.16.1

**Comment by ChuckJonas** [comment]
Looks like the deno docs were just throwing me off.

You can import types like so:
```
import OpenAI from "openai";
export type ChatCompletion = OpenAI.Chat.Completions.ChatCompletion;
export type ChatCompletionOptions =
  OpenAI.Chat.Completions.ChatCompletionCreateParams;
```

**Comment by rattrayalex** [comment]
Glad you figured this out! 

> Looks like the deno docs were just throwing me off.

OOC, which deno docs are you referring to?

**Comment by ChuckJonas** [comment]
@rattrayalex I assume these are autogenerated via static analysis by deno?

<img width="923" alt="default_ChatCompletion____mod_ts___openai_v4_16_1___Deno" src="https://github.com/openai/openai-node/assets/5217568/a293fe82-621b-41fd-bdc3-486a5a04c3b5">

Trying to assign the type to a `const` should have been enough to realize there's something wrong, but I somehow missed that...

**Comment by rattrayalex** [comment]
Ah, I see, thank you for sharing that – I wasn't aware Deno generated docs like that. I'll see if there's something to be done about that.

**Comment by ChuckJonas** [comment]
oh, I also opened a ticket but on the `deno_doc` repo: https://github.com/denoland/deno_doc/issues/395

I'm actually not sure this is actually the related repo though...

**Comment by rattrayalex** [comment]
Ah, yours is more likely to be the correct location, well done. Added a pointer.
