### ISSUE TITLE
Supabase Deno Functions import issues

### ISSUE THREAD

**Issue by jacoblee93** [openai/openai-node#484]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Trying to import the SDK in version `4.17.2` fails in a Supabase Deno function with the following error:

```
Download https://esm.sh/openai@4.17.2
Download https://esm.sh/v133/openai@4.17.2/esnext/resources.js
Failed to load module: "https://esm.sh/v133/openai@4.17.2/esnext/resources.js" - Import 'https://esm.sh/v133/openai@4.17.2/esnext/resources.js' failed, not found.
```

It worked in `4.4.0`, and is possibly an `esm.sh` bundling issue, since it seems to work in a Deno kernel Jupyter notebook with `npm:` style imports.

### To Reproduce

1. Create a Supabase Deno function
2. Use the following code:

```
import { OpenAI } from "https://esm.sh/openai@4.17.2";

Deno.serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }
  const client = new OpenAI()

  return new Response(
    JSON.stringify({}),
    { headers: { "Content-Type": "application/json" } },
  )
})
```

### OS

Supabase Deno

### Node version

Deno

### Library version

4.17.2

**Comment by rattrayalex** [comment]
For Deno on Supabase or Netlify Edge functions you need to import like so:

```ts
https://deno.land/x/openai@v4.16.1/mod.ts
```

Note that we don't have auto-releases for Deno set up just yet, but we're actively working on that and hope to have it up soon. 

If you need a version newer than 4.16.1, let us know and @athyuttamre can get do a manual deploy.

The esm.sh failure is tracked here: https://github.com/esm-dev/esm.sh/issues/743

**Comment by jacoblee93** [comment]
Ah ok, will ask the dev to try the deno.land import and track that issue.

Downgrading also unblocked them.

**Comment by ije** [comment]
fixed in latest update

**Comment by jacoblee93** [comment]
Excellent, thank you!
