### ISSUE TITLE
Wrong return type for openai.audio.speech.create API

### ISSUE THREAD

**Issue by sangonzal** [openai/openai-node#485]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm following the tutorial for TTS on the OpenAI website: https://platform.openai.com/docs/guides/text-to-speech?lang=node

When I try to use that code in a typescript file, typescript always infers a return value of "never".  Ignoring TS for that line makes it work.  

<img width="852" alt="Screenshot 2023-11-10 at 4 19 18 PM" src="https://github.com/openai/openai-node/assets/35743865/32daac7c-da62-4826-b723-033c227a045a">

### To Reproduce

Save the code from https://platform.openai.com/docs/guides/text-to-speech?lang=node in a .ts file. 

### OS

macOS

### Node version

Node v19

### Library version

v4.17.17

**Comment by rattrayalex** [comment]
I can't reproduce this; can you share a stackblitz, replit, or similar that reproduces the problem?

**Comment by sangonzal** [comment]
@rattrayalex I can't reproduce this on Replit either. It's weird because I'm using other APIs in my project, and the types all work except this one. Either way, you can close this issue as it's not reproducible, I appreciate the prompt response.

**Comment by rattrayalex** [comment]
Okay, sorry for the difficulty. You might try deleting `node_modules` and reinstalling or something. 

If others encounter this as well, please comment with your tsconfig and other details of your installation.

**Comment by tan-dd** [comment]
I have the same issue
![image](https://github.com/openai/openai-node/assets/47315850/d62014a7-ec84-457f-92d4-1ba3889db8f7)

**Comment by tan-dd** [comment]
I am facing the same issue:
![image](https://github.com/openai/openai-node/assets/47315850/4d90e7a1-358d-4be4-947d-0f9d08515a3b)

**Comment by dackerman** [comment]
@tan-dd were you able to reproduce this one on a replit?

**Comment by DisorderedJJ** [comment]
I am getting the same issue, here is my tsconfig file 

`{
  "compilerOptions": {
    "lib": ["ES2020"],
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,  
    "moduleResolution": "node",
    "noUnusedParameters": false,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true, 
    "target": "ES2020",
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ]
}
`

**Comment by rattrayalex** [comment]
@DisorderedJJ could you please share a codesandbox, replit, or other reproduction link?
