### ISSUE TITLE
Unable to return normally when tool_choice is specified

### ISSUE THREAD

**Issue by lawetis** [openai/openai-node#486]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

We assume that tools has multiple functions in the following parameters.
```
const runner = openaiClient.beta.chat.completions.runTools(
  model: 'gpt-4-1106-preview',
  stream: true,
  messages: messages[],
  tools: toots[]
  tool_choice: {
    type: 'function',
    function: {
          name: 'func_name'
    }
  }
)
```
When tool_choice is specified in the above code, it seems that it cannot be executed normally. When set to `auto`, the process can make normal function calls and return normally.

Code snippets refer to [examples](https://github.com/openai/openai-node/blob/master/examples/tool-call-helpers.ts).

### To Reproduce

none

### OS

windows

### Node version

Node v18.15.1

### Library version

openai v4.17.3

**Comment by rattrayalex** [comment]
The intended behavior is that passing `tool_choice` results in the model running only once, not in a loop. 

This is [documented here](https://github.com/openai/openai-node/#automated-function-calls), though with a typo (`tool_call` should be `tool_choice`). 

Does that make sense?

If I might ask, why do you want to pass `tool_choice` and still run in a loop?

**Comment by rattrayalex** [comment]
Or could you clarify what you mean by "cannot be executed normally"?

**Comment by lawetis** [comment]
@rattrayalex Thank you, I understand. I now know how it works, thank you very much for your help.
