### ISSUE TITLE
APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by eleven8001** [openai/openai-node#492]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [ ] This is an issue with the Node library

### Describe the bug

APIConnectionError: Connection error.
    at OpenAI.makeRequest (E:\desk\demo\text-to-speech-demo\node_modules\openai\core.js:279:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\desk\demo\text-to-speech-demo\server.js:31:17 {
  status: undefined,
  headers: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: FetchError: request to https://api.openai.com/v1/audio/speech failed, reason: connect ETIMEDOUT 128.121.146.109:443
      at ClientRequest.<anonymous> (E:\desk\demo\text-to-speech-demo\node_modules\node-fetch\lib\index.js:1501:11)
      at ClientRequest.emit (node:events:514:28)
      at ClientRequest.emit (node:domain:489:12)
      at TLSSocket.socketErrorListener (node:_http_client:501:9)
      at TLSSocket.emit (node:events:514:28)
      at TLSSocket.emit (node:domain:489:12)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  }
}

### To Reproduce

写了一个 text-to-speech的接口，但是会报错，我的代码片段如下

### Code snippets

```JavaScript
这个是我的代码片段，我尝试使用express框架进行写一个 text-to-speech的接口，但是由于一些原因，我需要用魔法，所以才会Connection error，但是我不知道如何去解决这个问题。
const express = require('express');
const path = require('path');
const fs = require('fs');
const OpenAI = require('openai');

const app = express();
const port = 3000;
const cors = require('cors');

app.use(cors());
app.use(express.json());

const apiKey = process.env.OPENAI_API_KEY;
const openai = new OpenAI({
  apiKey: apiKey,
});

app.post('/speech', async (req, res) => {
  try {
    const { text } = req.body;
    const mp3 = await openai.audio.speech.create({
      model: "tts-1",
      voice: "alloy",
      input: text,
    });
    const buffer = Buffer.from(await mp3.arrayBuffer());
    const speechFile = path.resolve("./speech.mp3");
    await fs.promises.writeFile(speechFile, buffer);
    res.status(200).sendFile(speechFile);
  } catch (error) {
    console.error(error);
    res.status(500).send('Internal Server Error');
  }
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
```

### OS

windows11

### Node version

v18.17.1

### Library version

openai v4.17.4

**Comment by huangshaomo** [comment]
![image](https://github.com/openai/openai-node/assets/49508152/b5092f36-1abf-4e90-92c8-5946f4977b1a)

**Comment by huangshaomo** [comment]
![image](https://github.com/openai/openai-node/assets/49508152/925fba35-a3a2-4f7f-af5d-af544a2a4f15)
我在代理中启用这个模式就可以了，虽然我也不知道是为啥

**Comment by rattrayalex** [comment]
Are you able to connect to the API from the same machine using `curl`? If not, you may want to check this page: https://platform.openai.com/docs/supported-countries

I'm going to close this issue because it doesn't seem like a problem with the TypeScript library; for further help, I recommend the OpenAI Discord channel.

**Comment by real-jiakai** [comment]
Dear friends from China, if you are using the Clash series of software for proxy settings, it is important to note that these applications automatically bypass local addresses in the system proxy configuration. 

This becomes particularly relevant when you are engaged in local development, as local addresses are used in this context. Consequently, if you are in a region where OpenAI services are not supported, you might face difficulties in sending requests to OpenAI's API endpoints. 

To resolve this issue, you should consider modifying your system proxy settings. Specifically, you need to remove entries in the 'bypass address' section of your proxy configuration that include local addresses. By doing so, your system will not bypass these addresses, allowing your requests to OpenAI's API to be routed through the proxy, potentially circumventing regional restrictions.

Typically, when software from the Clash series activates the system proxy, it automatically adds entries to bypass local addresses. My suggestion is to let other software handle the system proxy settings, while using Clash solely for providing access through its port 7890.

In my case, remove the bypass proxy settings solves this issue.

![image](https://github.com/openai/openai-node/assets/82650452/c060a276-ea47-4dac-8c9f-e0eddd2197be)
