### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by Tohaker** [openai/openai-node#5]
I'm trying to upload a file that can then be used to create a fine-tune. It's been passed through the CLI validator so I know it's correct, but I keep getting the following error from Axios:

```js
data: {
      error: {
        message: 'The browser (or proxy) sent a request that this server could not understand.',
        type: 'server_error',
        param: null,
        code: null
      }
    }
```

Here's how I'm trying to upload the file;
```js
const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
  });
  const openai = new OpenAIApi(configuration);

await openai.createFile(`${uploadFilename}.jsonl`, "fine-tune");
```

Am I doing this right? I can't seem to see what the problem could be.

**Comment by npaez** [comment]
Hi Tohaker, in the examples they are sending the file as a readable stream. Using `createReadStream()` from the `fs` module.
Did you tried this?

```
const fs = require("fs");

const { Configuration, OpenAIApi } = require("openai");

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration);

const response = await openai.createFile(
  fs.createReadStream("puppy.jsonl"),
  "answers"
);
```

**Comment by Tohaker** [comment]
Thanks, that worked. The description in the API differs from how this is implemented, I'll see if I can raise a PR
