### ISSUE TITLE
Broken links in code comments

### ISSUE THREAD

**Issue by hakkikonu** [openai/openai-node#500]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Broken link: https://platform.openai.com/docs/guides/gpt/parameter-details 

Locations:

1. https://github.com/openai/openai-node/blob/09127e8425bb07ea0f9e6a80470edef6a87dcea7/src/resources/chat/completions.ts#L582

2. https://github.com/openai/openai-node/blob/09127e8425bb07ea0f9e6a80470edef6a87dcea7/src/resources/chat/completions.ts#L639C69-L639C130

### To Reproduce

You can go to the given locations on the source code.

### OS

macOS

### Node version

Node V20

### Library version

openai v4.18.0

**Comment by rattrayalex** [comment]
Thanks for reporting! This will be fixed by https://github.com/openai/openai-openapi/pull/126

Closing preemptively since it's a minor bug.
