### ISSUE TITLE
Potentially broken endpoints for chat completion

### ISSUE THREAD

**Issue by greffgreff** [openai/openai-node#503]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I am getting `404 Invalid URL POST /v1/chat/completions/` when performing chat completions.

### To Reproduce

I am have the reproducable code in ts:

```js
export async function getCompletion(
  prompt: string,
  model: string = 'gpt-3.5-turbo',
  temperature: number = 0,
): Promise<string> {
  const response = await openai.chat.completions.create({
    messages: [{ role: 'user', content: prompt }],
    model,
    temperature,
  })

  return response.choices[0].message.content!
}
```

### OS

React Native Expo

### Node version

v16.15.0.

### Library version

openai ^4.18.0

**Comment by RobertCraigie** [comment]
React native is not supported, for more details see this issue: https://github.com/openai/openai-node/issues/490
