### ISSUE TITLE
Extending Issue #499 to Deno Library:  GPT4 preview finish_details not supported

### ISSUE THREAD

**Issue by buyblvd-ryan** [openai/openai-node#504]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using any of the gpt4 preview models, they return choices with finish_details instead of finish_reason.  This was just addressed in issue #499 for the node library, but the change needs to be extended to the Deno build.

### To Reproduce

1. Use deno
2. Query a gpt4 preview model
3. Be upset when typescript yells at you for selecting an element that it doesn't think exists

### OS

macOS

### Node version

N/A

### Library version

openai v4.16.1

**Comment by rattrayalex** [comment]
There's no difference between the Node and Deno build for this purpose; closing as a dup of https://github.com/openai/openai-node/issues/499
