### ISSUE TITLE
Why did V4 API drop support for "name" parameter in chat messages?

### ISSUE THREAD

**Issue by jens-totemic** [openai/openai-node#508]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

In the node V4 API I try this:

```
let message: OpenAI.Chat.ChatCompletionMessageParam = {role: 'system', content: "my content", name: "Test"};
```

which causes this error because `name` is not allowed for a system role. 
```
Type '{ role: "system"; content: string; name: string; }' is not assignable to type 'ChatCompletionMessageParam'.
  Object literal may only specify known properties, and 'name' does not exist in type 'ChatCompletionSystemMessageParam'.ts(2322)
```

But the official API description at https://platform.openai.com/docs/api-reference/chat/create
states that the `name` parameter is still supported as "optional" value for roles "system", "user" and "assistant". 

This worked in the node V3 API. Why was this support removed in the V4 API? Was this done on purpose or by mistake?

### To Reproduce

See steps above

### OS

macOS

### Node version

Node v18

### Library version

openai v4.19.0

**Comment by rattrayalex** [comment]
This hasn't been added to the public OpenAPI spec yet, but I expect it will be shortly - when it is, it'll be reflected in this SDK.

In the meantime, you can work around this with a `// @type-expect-error` comment or equivalent.

**Comment by jwd-dev** [comment]
Does the actual API respect these parameters?

**Comment by rattrayalex** [comment]
`name` is now being added back into the types!
