### ISSUE TITLE
OpenAI not working on AWS Lambda

### ISSUE THREAD

**Issue by sattarab** [openai/openai-node#510]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I am trying to use OpenAI on AWS Lambda but currently the code just hangs. I have also tried adding OpenAI as a lambda layer but that is not working as well

### To Reproduce

I have the following package.json

```
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "yarn && ../../node_modules/.bin/tsc --build tsconfig.json",
    "deploy:dev": "yarn build && ../../node_modules/.bin/serverless deploy --stage dev",
    "preinstall": "../../bin/check-yarn"
  },
  "engines": {
    "node": ">=18.0"
  },
  "devDependencies": {
    "@serverless/typescript": "2.70.0",
    "esbuild": "0.19.5",
    "openai": "4.19.0",
    "serverless-bundle": "6.0.0",
    "serverless-domain-manager": "5.1.5",
    "serverless-esbuild": "1.48.5",
    "serverless-stage-manager": "1.0.5",
    "ts-node": "10.9.1"
  }
}
```

The following is the openai as a Layer package
[layer-package.zip](https://github.com/openai/openai-node/files/13387805/layer-package.zip)

### Code snippets

```JavaScript
export async function test() {
  console.log( "test" )
  const openai = new OpenAIApi( { apiKey: process.env.OPENAI_KEY } )

  console.log( "openai initialized", openai )
  const completion_response = await openai.completions.create( { model: "gpt-3.5-turbo-instruct", prompt: "Can you briefly tell me about the first president of America?" } )

  console.log( "completion_response", completion_response )
  if( ! completion_response.choices?.length ) {
    return null
  }

  return completion_response.choices[ 0 ].text || null
}
```

### OS

AWS Lambda

### Node version

18

### Library version

openai v4.19.0

**Comment by MatildaApp** [comment]
Having this issue as well trying to figure out solution from last 2 days.

`[Error]: Connection error.
    at Xt.makeRequest (/var/task/src/handleWebsocketMessage.js:100:7540)
    at async Ts (/var/task/src/handleWebsocketMessage.js:308:4294) {
  status: undefined,
  headers: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: Expected signal to be an instanceof AbortSignal
      at new W0 (/var/task/src/handleWebsocketMessage.js:77:15624)
      at /var/task/src/handleWebsocketMessage.js:77:18139
      at new Promise (<anonymous>)
      at Y1 (/var/task/src/handleWebsocketMessage.js:77:18099)
      at Xt.fetchWithTimeout (/var/task/src/handleWebsocketMessage.js:100:8908)
      at Xt.makeRequest (/var/task/src/handleWebsocketMessage.js:100:7359)
      at async Ts (/var/task/src/handleWebsocketMessage.js:308:4294)
}`

Tried downgrading to v3. it has response issue.
Tried upgrading, downgrading to multiple node versions.
Tried polyfiling fetch from undici, node-fetch.

Nothing is working.
is this known issue in library?
or something with nodejs?

**Comment by jdgalani** [comment]
Having this issue as well trying to figure out solution from last 2 days.

`[Error]: Connection error.
    at Xt.makeRequest (/var/task/src/handleWebsocketMessage.js:100:7540)
    at async Ts (/var/task/src/handleWebsocketMessage.js:308:4294) {
  status: undefined,
  headers: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: Expected signal to be an instanceof AbortSignal
      at new W0 (/var/task/src/handleWebsocketMessage.js:77:15624)
      at /var/task/src/handleWebsocketMessage.js:77:18139
      at new Promise (<anonymous>)
      at Y1 (/var/task/src/handleWebsocketMessage.js:77:18099)
      at Xt.fetchWithTimeout (/var/task/src/handleWebsocketMessage.js:100:8908)
      at Xt.makeRequest (/var/task/src/handleWebsocketMessage.js:100:7359)
      at async Ts (/var/task/src/handleWebsocketMessage.js:308:4294)
}`

Tried downgrading to v3. it has response issue.
Tried upgrading, downgrading to multiple node versions.
Tried polyfiling fetch from undici, node-fetch.

Nothing is working.
is this known issue in library?
or something with nodejs?

**Comment by rattrayalex** [comment]
@sattarb I don't see `openai` in your package.json `dependencies`, and I don't see how you're importing the package. This package does not export `OpenAIApi` in v4. It seems you may be using another package?

@jdgalani that looks like an unrelated issue. Can you open a separate thread and include a repo that reproduces the issue, along with reproduction steps?

**Comment by sattarab** [comment]
@rattrayalex I do have `openai` as a dependency in package.json.

## package.jsopn

```
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "yarn && ../../node_modules/.bin/tsc --build tsconfig.json",
    "deploy:dev": "yarn build && ../../node_modules/.bin/serverless deploy --stage dev",
    "preinstall": "../../bin/check-yarn"
  },
  "engines": {
    "node": ">=18.0"
  },
  "devDependencies": {
    "@serverless/typescript": "2.70.0",
    "esbuild": "0.19.5",
    "openai": "4.19.0",
    "serverless-bundle": "6.0.0",
    "serverless-domain-manager": "5.1.5",
    "serverless-esbuild": "1.48.5",
    "serverless-stage-manager": "1.0.5",
    "ts-node": "10.9.1"
  }
}
```

## Code Snippets

```
...
import { OpenAI as OpenAIApi } from "openai"

export async function test() {
  console.log( "test" )
  const openai = new OpenAIApi( { apiKey: process.env.OPENAI_KEY } )

  console.log( "openai initialized", openai )
  const completion_response = await openai.completions.create( { model: "gpt-3.5-turbo-instruct", prompt: "Can you briefly tell me about the first president of America?" } )

  console.log( "completion_response", completion_response )
  if( ! completion_response.choices?.length ) {
    return null
  }

  return completion_response.choices[ 0 ].text || null
}
```

As I mentioned above I tried with both OpenAI as a layer with devDependency and OpenAI as a production dependency. Both didn't work.

It is really sad that you didn't wait even for a reply and just close the issue

**Comment by rattrayalex** [comment]
Got it, thank you @sattarab. 

Can you please share a repo that can be used for a reproduction?

Failing that, can you share the logging output? Does it log `"completion_response"`?

**Comment by jdgalani** [comment]
@sattarab did you find the solution or the exact issue?

**Comment by jpv123** [comment]
Hi guys, found any solution. Having the same issue but with cloud functions from firebase

**Comment by rattrayalex** [comment]
If anyone could share a repro repo / steps that would be helpful.

**Comment by jdgalani** [comment]
to me AbortSignal was culprit or I don't know what/who real culprit was but this worked.


```
const openai = new OpenAI({
  apiKey: OPENAI_API_KEY,
  fetch: async (url: RequestInfo, init: RequestInit): Promise<Response> => {
    delete init.signal;
    console.log("About to make request");
    const response = await fetch(url as string, init);
    console.log("Got response");
    return response;
  },
});
```

Tried creating sandbox but on simple request it works. can not reproduce it on sandbox.
so it must be with some 3rd party libraries or their versions.
Assuming: `node`, `pinecone-database` must be problamtic.

**Comment by rattrayalex** [comment]
Thank you @jdgalani ! Which third-party libraries are you using?

**Comment by jdoxit** [comment]
Check this out, content from package.json.

'''

 "dependencies": {
    "@pinecone-database/pinecone": "^1.1.2",
    "ajv": "^8.6.2",
    "axios": "^0.27.2",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.21",
    "luxon": "^2.0.1",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.43",
    "nanoid": "^3.1.23",
    "openai": "4.19.0",
    "serverless-websockets-plugin": "^1.0.0",
    "stripe": "^8.167.0",
    "twilio": "^3.75.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.81",
    "@types/jwt-decode": "^3.1.0",
    "@types/luxon": "^1.27.1",
    "@types/node": "^16.4.10",
    "aws-sdk": "^2.959.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.3.2",
    "serverless": "^2.52.1",
    "serverless-bundle": "^5.5.0",
    "serverless-dynamodb-local": "^0.2.40",
    "serverless-offline": "^8.0.0",
    "serverless-seed": "^0.3.13",
    "serverless-websockets-plugin": "^1.0.0"
  }
'''

**Comment by jdgalani** [comment]
check this out @rattrayalex ,
content from my package.json

```
 "dependencies": {
    "@pinecone-database/pinecone": "^1.1.2",
    "ajv": "^8.6.2",
    "axios": "^0.27.2",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.21",
    "luxon": "^2.0.1",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.43",
    "nanoid": "^3.1.23",
    "openai": "4.19.0",
    "serverless-websockets-plugin": "^1.0.0",
    "stripe": "^8.167.0",
    "twilio": "^3.75.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.81",
    "@types/jwt-decode": "^3.1.0",
    "@types/luxon": "^1.27.1",
    "@types/node": "^16.4.10",
    "aws-sdk": "^2.959.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.3.2",
    "serverless": "^2.52.1",
    "serverless-bundle": "^5.5.0",
    "serverless-dynamodb-local": "^0.2.40",
    "serverless-offline": "^8.0.0",
    "serverless-seed": "^0.3.13",
    "serverless-websockets-plugin": "^1.0.0"
  }
```

**Comment by rattrayalex** [comment]
Can you show me how you call the OpenAI API? A full, working example application file would be very helpful.

**Comment by antstanley** [comment]
Just adding 2 cents here. I've happily got the `openai` package working in Lambda. My code is written in TypeScript and I bundle it using `esbuild` . 

@jdgalani it looks like your issue is actually with the `serverless-websockets-plugin` package, which is deprecated, and hasn't been updated in 5 years. Serverless Framework has [native support for AWS's API Gateway Websockets](https://www.serverless.com/framework/docs/providers/aws/events/websocket) functionality now, so I would recommend using that. I also recommend swapping out the `serverless-bundle` package with the `serverless-esbuild` package, and upgrade your Node runtime to v20 (v14 is deprecated, and v16 will be deprecated this year in Lambda).

@sattarab you have both `serverless-bundle` and `serverless-esbuild`. I would ditch `serverless-bundle` and only use `serverless-esbuild`. Also upgrade to Node v20 (though v18 should work fine), and check your CloudWatch logs for any errors, even if it is just timeouts.

**Comment by rattrayalex** [comment]
Thank you so much @antstanley !
