### ISSUE TITLE
TS7006: Parameter 'ctrl' implicitly has an 'any' type.  in ./node_modules/openai/src/streaming.ts:187:18

### ISSUE THREAD

**Issue by teto-soft** [openai/openai-node#511]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The build not works with typescript, becase the param of pull has no type.
https://github.com/openai/openai-node/blob/049ce6fa66ebe9a6aa0d64dead1e5fd8c3da1083/src/streaming.ts#L187

The build now works by doing the following.
```diff
-       async pull(ctrl) {
+       async pull(ctrl: ReadableStreamDefaultController) {
```

### To Reproduce

1. npm i openai
2. write openai.chat.completion.create()
3. npm run build
4. throw error (TS7006)

### OS

macOS

### Node version

Node v18.18.0

### Library version

openai 4.17.0

**Comment by RobertCraigie** [comment]
Are you importing from openai/src?

**Comment by rattrayalex** [comment]
The fix should be to make sure that you're not importing `from 'openai/src'` anywhere in your codebase.
