### ISSUE TITLE
Can't use GPT-4-1106-Preview

### ISSUE THREAD

**Issue by MoShizzle** [openai/openai-node#512]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using the Node package, trying to create chat completions with gpt-4-1106-preview model returns this: Invalid model: gpt-4-1106-preview.

Using it through the API directly works fine.

### To Reproduce

1. Create a chat completion with gpt-4-1106-preview
2. See error
3. Try with API directly, not using the package
4. It works

### OS

macOS

### Node version

Node v18.17.1

### Library version

openai v4.19.0

**Comment by clickeo-dev** [comment]
It gives me an error like this: [Error: Model 'gpt-4-1106-preview' does not support chat.]

**Comment by MoShizzle** [comment]
Found the issue, it's from another package I'm using not OpenAI.

Closing since it's not valid.
