### ISSUE TITLE
Incorrect Type Definition for Assistants text responses

### ISSUE THREAD

**Issue by wmelton** [openai/openai-node#513]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The tree path for the text response from an assistant is `content.text.value` when return type is `text`.

However, type definitions skip the `text` part of the tree causing type errors.

From the API, this is an example response:

`content: [ { type: 'text', text: { value: 'this is a response' } } ],`

However, when accessing it, type says `Property 'text' does not exist on type 'MessageContentImageFile | MessageContentText'`

### To Reproduce

Fetch a response from the assistant API and then attempt to access the text value. 

### Code snippets

```JavaScript
For example:


const messages = await openai.beta.threads.messages.list(
          threadId,
        )
const content = messages.data
          .filter(message => message.role === 'assistant').pop()

const response = content?.content[0].text.value
```

In VS Code, `text` will be underlined in red and throw the type error described above.
```


### OS

macOS

### Node version

v18.13.0

### Library version

4.19.0

**Comment by devodii** [comment]
Can I work on a fix for this?

**Comment by rattrayalex** [comment]
See https://github.com/openai/openai-node/issues/454#issuecomment-1806646219 and the following comment – this is confusing TypeScript behavior, but not an incorrect type definition.

**Comment by wmelton** [comment]
@rattrayalex Yeah you're right. It makes sense now in light of your other comment, but I suppose it wasn't intuitive to me before because I didn't realize Assistants could return image_urls as their response.
