### ISSUE TITLE
Why is functions being deprecated in favor of tools?

### ISSUE THREAD

**Issue by huypham50** [openai/openai-node#515]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

```
  /**
   * Deprecated in favor of `tool_choice`.
   *
   * Controls which (if any) function is called by the model. `none` means the model
   * will not call a function and instead generates a message. `auto` means the model
   * can pick between generating a message or calling a function. Specifying a
   * particular function via `{"name": "my_function"}` forces the model to call that
   * function.
   *
   * `none` is the default when no functions are present. `auto`` is the default if
   * functions are present.
   */
  function_call?: 'none' | 'auto' | ChatCompletionFunctionCallOption;

  /**
   * Deprecated in favor of `tools`.
   *
   * A list of functions the model may generate JSON inputs for.
   */
  functions?: Array<ChatCompletionCreateParams.Function>;
```

Is there a reason for this change? This looks like a soft deprecation to me because it's still working, when should we expect things to break?

Also, this is pretty confusing to me because we're deprecating `functions` in favor of `tools` but the beta features still introduce `runFunctions` and `runTools`, should it be `runTools` only?

**Comment by rattrayalex** [comment]
Fair questions!

> Is there a reason for this change?

tools are more flexible for future expansion of functionality.

> This looks like a soft deprecation to me because it's still working, when should we expect things to break?

This is indeed soft; I don't believe we've shared a timeline for `functions` to be removed, but I suggest moving to `tools` at your soonest convenience and sharing any feedback you have if there's anything lacking compared to `functions`.

> should it be runTools only?

Yes, you should just use `runTools`.
