### ISSUE TITLE
Openai MODULE_NOT_FOUND error during deployment

### ISSUE THREAD

**Issue by Letalus** [openai/openai-node#518]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I recently included the openai node package within my node.js application.

Before I included this package into my app the deployment was working perfectly fine.

Once I implemented all the needed endpoints and finished testing locally I tried to deploy it to my google cloud server instance.

But here the problem started. When I deployed the new server version, I got following error:

`yarn cache v1.22.11
warning package.json: No license field
success Cleared cache.
Done in 4.16s.
yarn install v1.22.11
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 48.54s.
[PM2] Applying action deleteProcessId on app [all](ids: [ 0, 1 ])
[PM2] [index](0) ✓
[PM2] [index](1) ✓
[PM2] [v] All Applications Stopped
[PM2] [v] PM2 Daemon Stopped
yarn run v1.22.11
warning package.json: No license field
$ cross-env NODE_ENV=dev NODE_OPTIONS='--max-old-space-size=4096' ts-node src/index.ts
    at Object.require.extensions.<computed> [as .js] (/XXX/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
 '/home/user/my_app/node_modules/openai/_shims/node-runtime.js',
'/home/user/my_app/node_modules/openai/_shims/auto/runtime-node.js',
'/home/user/my_app/node_modules/openai/_shims/index.js',
'/home/user/my_app/node_modules/openai/streaming.js',
'/home/user/my_app/node_modules/openai/core.js',
'/home/user/my_app/node_modules/openai/index.js',
'/home/user/my_app/src/functions/chat/trainerMessages/generateTrainerMessage.ts',
'/home/user/my_app/src/functions/chat/trainerMessages/sendTrainerToUserChatMessage.ts',
'/home/user/my_app/src/functions/chat/trainerMessages/sendTrainerChatMessage.ts',
'/home/user/my_app/src/graphql/resolvers/mutation.ts',
'/home/user/my_app/src/graphql/rootResolver.ts',
'/home/user/my_app/src/index.ts'
  ]
}`

Apparently the _shims/node-runtime.js is not found within my project.
Does someone, what kind of reasons there could be that during deployment this code part can't be found?

### To Reproduce

- Include the openai package to a node.js api
- deploy it on google cloud compute engine
- receive the error

### OS

14.0 (23A344)

### Node version

Node.js v20.8.0

### Library version

openai v4.19.0

**Comment by rattrayalex** [comment]
Does this persist across repeated fresh deploys, or could it be that there was a corrupted `node_modules` or `yarn cache` after installation?

When you install locally, does `node_modules/openai/_shims/node-runtime.js` exist for you?

**Comment by rattrayalex** [comment]
Thank you for sharing the resolution!
