### ISSUE TITLE
Max prompt token not work when using text-davinci-003

### ISSUE THREAD

**Issue by telecare-zeno** [openai/openai-node#52]
### Describe the bug

Hi team, I'm using openai pkg with model `text-davinci-003` in my code.

I tried to use `createCompletion` to get a response back, and all work well if I just make prompt length blew 2000. 
But if I use a prompt which more than 2000 tokens, it will return 400 error.

I can see the document told us it could accept 4000 tokens.
https://beta.openai.com/docs/models/gpt-3

SO is it a bug will be fixed in the future?

- Calculate the tokens: https://beta.openai.com/tokenizer
- Node version: v18.12.0
- Openai package version: 3.1.0
- model: text-davinci-003

Here is the code with params:
```
await openAIAgent.createCompletion({
  model: "text-davinci-003",
  prompt: prompt,
  temperature: 0.3,
  max_tokens: 2048,
  top_p: 1.0,
  frequency_penalty: 0.8,
  presence_penalty: 0.0,
})
```

### To Reproduce

Use createCompletion, the `prompt` should more than 2000 tokens, maybe directly use a `prompt` between 3000 and 4000
The params same as follow code:
```
await openAIAgent.createCompletion({
  model: "text-davinci-003",
  prompt: prompt,
  temperature: 0.3,
  max_tokens: 2048,
  top_p: 1.0,
  frequency_penalty: 0.8,
  presence_penalty: 0.0,
})
```

### OS

macOS

### Node version

 Node v18.12.0

### Library version

openai v3.1.0

**Comment by telecare-zeno** [comment]
Does anyone know this issue?  Is it just me or is this a generic problem?

**Comment by ezzcodeezzlife** [comment]
max_tokens = input (prompt) + generated text

[to calculate tokens before use this](https://github.com/openai/tiktoken)

**Comment by telecare-zeno** [comment]
Thanks @ezzcodeezzlife, it's useful! 
Sorry, I didn't realize the `4000` tokens should consider both `max_tokens` and `prompt` fields

I tested it locally by using `gpt-3-encoder` in the js code. it works well!
