### ISSUE TITLE
Token usage information is not available in the assistants API

### ISSUE THREAD

**Issue by anandsathe67** [openai/openai-node#531]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

In the completions API, the response contains information about promptTokens, completionTokens and totalTokens. While prototyping use of the Assistant API, I noticed the response (or the run result) does not provide this information. This is critical for us to devise usage limits for our users. Is this something which was purposely left out or we can expect this information to be available in one of the upcoming releases?

### To Reproduce

In the snippet below, I was expecting token information in the response.data field. However, no such information is available

### Code snippets

```JavaScript
const res = await this.openai.beta.threads.runs.retrieve(threadId, runId).withResponse();
const run = res.data
if (run.status === 'completed') {
 const response = await this.openai.beta.threads.runs.retrieve(threadId, runId).withResponse();
 const result = response.data
 const messagesFromThread: OpenAI.Beta.Threads.Messages.ThreadMessagesPage =
            (await this.openai.beta.threads.messages.list(threadId).withResponse()).data;
 resolve({ runResult: result, messages: messagesFromThread });
```

### OS

macOS

### Node version

node v18.18.2

### Library version

openai v4.20.0

**Comment by anandsathe67** [comment]
Using the gpt-4-1106-preview model

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the TypeScript library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by heymartinadams** [comment]
Mentioned [here](https://community.openai.com/t/update-request-please-add-used-tokens-to-assistants-api/497310) as well as in several other places in the community forum.
