### ISSUE TITLE
Types missing when using with Deno

### ISSUE THREAD

**Issue by ivasilov** [openai/openai-node#538]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using this library with Deno, the type information are missing for all types exported from [resources/index](https://github.com/openai/openai-node/blob/master/src/resources/index.ts). 
![Screenshot 2023-11-27 at 17 29 20](https://github.com/openai/openai-node/assets/568291/edd5b95e-badc-47cb-9462-27c28700af70)

This is probably due to [main index file](https://github.com/openai/openai-node/blob/master/src/index.ts#L8) importing the resources/index as `openai/resources/index` instead of `./resources.index`.
![Screenshot 2023-11-27 at 17 30 55](https://github.com/openai/openai-node/assets/568291/dc04bfa3-983f-4c2f-8bfd-45ecfa5bf507)

I'm using VSCode 1.84.2.

### To Reproduce

To reproduce:
1. Setup a Deno project with VSCode
2. Add `import OpenAI from 'https://esm.sh/openai@4.20.0'`
3. Try to use any of the functions (`openAI.embeddings.create`, for example).

### OS

MacOS

### Node version

Deno 1.38.2

### Library version

OpenAI 4.20.0

**Comment by rattrayalex** [comment]
I can reproduce this with `esm.sh`, but [this type error does not exist](https://www.val.town/v/rattrayalex/untitled_coralHornet) when using the official `deno.land` package, e.g.:

```ts
import OpenAI from "https://deno.land/x/openai@v4.20.0/mod.ts";

const client = new OpenAI();

client.embeddings.create()
```

I'll open an issue about the esm.sh problem in that repo.

**Comment by waptik** [comment]
> I can reproduce this with `esm.sh`, but [this type error does not exist](https://www.val.town/v/rattrayalex/untitled_coralHornet) when using the official `deno.land` package, e.g.:
> 
> ```ts
> import OpenAI from "https://deno.land/x/openai@v4.20.0/mod.ts";
> 
> const client = new OpenAI();
> 
> client.embeddings.create()
> ```
> 
> I'll open an issue about the esm.sh problem in that repo.

Great. I think you don’t need to use esm.sh when the official one exists and it’s up to date. 

Good luck tho

**Comment by rattrayalex** [comment]
I'm told this error should be fixed in the next release of esm.sh!
