### ISSUE TITLE
prompt history

### ISSUE THREAD

**Issue by lpasquini** [openai/openai-node#54]
### Describe the feature or improvement you're requesting

Maybe it exists and I am not finding how, I need to make multiple calls while maintaining history, for example:

1- What is the size of the earth?
2- And of the moon?

Does this functionality exist or would it be a feature?

**Comment by schnerd** [comment]
For now, we leave this to developers to handle themselves. You can maintain the conversation history on your servers and send it along with each new prompt so that the model has the full context of the conversation.
