### ISSUE TITLE
Missing one parameter baseURL

### ISSUE THREAD

**Issue by liuyenhui** [openai/openai-node#541]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

+ set system evn export OPENAI_BASE_URL='...'
The following code is invalid.
const client = new OpenAI() 

### To Reproduce

https://github.com/openai/openai-node/blob/08833f20ae4eab6d23ddf989557e1c05a471352b/src/index.ts#L105C1-L106C1

### OS

MacOS

### Node version

node v20.9.0

### Library version

OpenAI 4.20.0

**Comment by efmoyano** [comment]
You can set it as an env variable, but consider pointing to a custom instance could not work due auth headers.

**Comment by rattrayalex** [comment]
You simply need to update your version of the library: https://github.com/openai/openai-node/blob/fa88266e2cd231fa78c2e12006e488472332a694/src/index.ts#L106
