### ISSUE TITLE
回答出问题了，代码太旧了

### ISSUE THREAD

**Issue by cityflysky** [openai/openai-node#55]
### Describe the bug

![image](https://user-images.githubusercontent.com/109882297/216003485-47c42b8d-1679-45f2-a105-40eee9e3bd11.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/109882297/216003485-47c42b8d-1679-45f2-a105-40eee9e3bd11.png)

### OS

windows

### Node version

Node v16

### Library version

openai^3.1.0

**Comment by schnerd** [comment]
This repository is for issues with the client SDK itself, not the underlying models.
