### ISSUE TITLE
Encountering timeouts for longer prompt when using SDK with `gpt-4-1106-preview`, but not when hitting API directly.

### ISSUE THREAD

**Issue by nicolaerusan** [openai/openai-node#557]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

We are using some longer prompts and consistently seeing the NodeSDK timeout, whereas the issue does not occur when calling the API directly with the same prompt.

Works reliably:
```
await axios.post(
      'https://api.openai.com/v1/chat/completions',
      {
        model: 'gpt-4-1106-preview',
        messages: [
          {
            role: 'system',
            content: systemPrompt
              ? systemPrompt
              : 'You are a helpful assistant.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      },
```

Times out consistently:
```
const result = await openai.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: `You are a helpful assistant.`,
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      model: 'gpt-4-1106-preview',
    });
    return {
      completion: result.choices[0].message.content,
    };    
```

I can't share the prompts as they contain customer information, but the length of them is:
Tokens
5,531
Characters
25661

### To Reproduce

1. Make a call with longer prompt using the Node SDK -> Get Timeout error
```
Error: Request timed out.
    at OpenAI.makeRequest 
    at process.processTicksAndRejections 
    at async completeChat 
``` 

2. Make same call directly to the API via `axios` -> No problem.

I've reproduced this issue consistently in production and locally. It does not occur as I shrink the length of the prompt, so it seems to have to do with prompt length and the SDK.

### Code snippets

```JavaScript
const result = await openai.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: `You are a helpful assistant.`,
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      model: 'gpt-4-1106-preview',
    });
    return {
      completion: result.choices[0].message.content,
    };    
```

```
await axios.post(
      'https://api.openai.com/v1/chat/completions',
      {
        model: 'gpt-4-1106-preview',
        messages: [
          {
            role: 'system',
            content: systemPrompt
              ? systemPrompt
              : 'You are a helpful assistant.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      },
```
```


### OS

macOS - 14.0 - 23A344

### Node version

v18.15.0

### Library version

4.20.1

**Comment by rattrayalex** [comment]
How quickly does it time out? The default timeout should be set to 10 minutes. Are you overriding that anywhere?

**Comment by rattrayalex** [comment]
If this is a `APIConnectionTimeoutError`, it may be because you're connecting differently than before, which is especially impactful if you're coming from behind a firewall / through proxies / etc. If so you may need to adjust how you use those.

**Comment by nicolaerusan** [comment]
@rattrayalex you were right about this, there was a default timeout being set in the OpenAI client that I wasn't aware of. Thanks for the suggestion!

```
export const openai = new OpenAI({
  apiKey: env.OPENAI_API_KEY,
  /*
   * Edge functions time out if there's no response within 25 seconds,
   * this ensures we won't reach that if openai hangs for some reason
   */
  timeout: 24000,
});
```
