### ISSUE TITLE
node_modules/openai/src/streaming.ts(187,18): error TS7006: Parameter 'ctrl' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by hiroshinishio** [openai/openai-node#560]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

node_modules/openai/src/streaming.ts(187,18): error TS7006: Parameter 'ctrl' implicitly has an 'any' type.

### To Reproduce

"openai": "^4.20.1",

### OS

macOS

### Node version

rwest@Roshis-MacBook-Pro slackgpt3 % node -v      v21.2.0

### Library version

"openai": "^4.20.1",

**Comment by hiroshinishio** [comment]
4.12.0 was OK
But from 4.13.0 to the latest 4.20.1 were not OK.

**Comment by hiroshinishio** [comment]
That's why I am using 4.12.0 right now.
I found this because I tried to update to the latest 4.20.1

**Comment by hiroshinishio** [comment]
This bug prevent me from updating the version and using assistant API...

**Comment by rattrayalex** [comment]
It looks like you might be importing `from "openai/src…` instead of `from "openai…` – can you search for that in your codebase?

**Comment by hiroshinishio** [comment]
@rattrayalex 
Yes as you can see, there is.
<img width="1080" alt="image" src="https://github.com/openai/openai-node/assets/4620828/c4f9d238-ea55-4545-9df6-4c6600983064">

**Comment by hiroshinishio** [comment]
Please kindly re-open and it is not resolved yet.

**Comment by rattrayalex** [comment]
Your code should not be importing from `openai/src`, which is where this error is showing up.

Can you install ripgrep, and run `rg 'from ['"'"'"]openai/src'` in your repo, and show me the results?

**Comment by hiroshinishio** [comment]
Ah I found I don't do that but LangChain does.

**Comment by rattrayalex** [comment]
ah, I will open a ticket with them.

**Comment by jacoblee93** [comment]
@hiroshinishio do you know where? I am not seeing any direct imports - it all should be `from "openai"`

**Comment by hiroshinishio** [comment]
@hiroshinishio Hey Jacob. It's been a while. Maybe because I use langchain@0.0.118? I know the latest version is 0.0.212 as of today, and I tried to catch up to the latest of course but I could not because when I updated it, as there are many changes.

**Comment by jacoblee93** [comment]
Ah, yeah that is quite old 😬 would say try upgrading if possible - happy to help guide through any changes!
