### ISSUE TITLE
TypeError: Reflect.get called on non-object on Cloudflare

### ISSUE THREAD

**Issue by maghfoor-dev** [openai/openai-node#563]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hi I am using Next js and deploying it on cloudflare. I am making sure everything is running on edge runtime. When I run my project locally, everything works fine.

However, on my deployed project, when I try to make a call to my api endpoint. I get an error of
`TypeError: Reflect.get called on non-object` in the logs on cloudflare.

### To Reproduce

1) Create a simple next js project with openai api call.
2) Deploy it on Cloudflare.
3) You will not be able to make a call.

### OS

Linux

### Node version

18+

### Library version

openai v.4.21.0

**Comment by rattrayalex** [comment]
Can you share a stacktrace?

**Comment by maghfoor-dev** [comment]
Unfortunately cloudflare logs only give me this info when i make call to openai
```
    {
      "message": [
        "TypeError: Reflect.get called on non-object"
      ],
      "level": "error",
      "timestamp": 1702628471370
    }

```

**Comment by maghfoor-dev** [comment]
Found out this issue is not related with open package but instead with `next-on-pages` package used to build next js project.
There is already an open issue on there :D 
https://github.com/cloudflare/next-on-pages/issues/499

**Comment by maghfoor-dev** [comment]
Found out this issue is not related with open package but instead with next-on-pages package used to build next js project.
There is already an open issue on there :D
https://github.com/cloudflare/next-on-pages/issues/499
