### ISSUE TITLE
functions don't support array params on top level

### ISSUE THREAD

**Issue by grmkris** [openai/openai-node#564]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

when using array as top level object in json schema i get error 400 from the openAI API

well it is not a big deal, i can just wrap the array one level below i think

**Comment by rattrayalex** [comment]
That's right, the OpenAI API only supports objects at the top level at this time. Your suggested workaround is appropriate.
