### ISSUE TITLE
Why does the message get cut off abruptly sometimes?

### ISSUE THREAD

**Issue by dosstx** [openai/openai-node#584]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Sometimes streaming message gets cut off mid-sentence.

### To Reproduce

1. Make a post request to openai.chat.completions.create()
2. Sometimes returned message is cut off and does not finish

### Code snippets

I am using the OpenAI API Node SDK in a Firebase Cloud Function to generate short stories. I am trying to debug why the messages stream gets cut off sometimes mid-sentence. For example:

![image](https://github.com/vercel/ai/assets/6342102/fb245759-98c0-4c6c-bc94-d9e30b6beca0)

Anyone got any advice on how to debug this? Here are my openAI chat completions settings:

```
    try {
      const { messages } = request.body
      const config = {
        // model: 'gpt-3.5-turbo',
        model: 'gpt-4-1106-preview',
        stream: true,
        messages: [
          {
            role: 'system',
            content:
              "<My custom system message here.>"
          },
          {
            role: messages[0].role,
            content: messages[0].content
          }
        ],
        temperature: 1,
        max_tokens: 3000,
        top_p: 0.82,
        frequency_penalty: 0,
        presence_penalty: 0
      }
      const openaiResponse = await openai.chat.completions.create(config)
      ```
```
The total characters in the generated stories is about 3000. 

Any thoughts?
```

### OS

Windows

### Node version

Node v18

### Library version

openai v4.23.0

**Comment by rattrayalex** [comment]
For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!

**Comment by rattrayalex** [comment]
Note you are passing `max_tokens: 3000,` which is a likely cause.

**Comment by dosstx** [comment]
> Note you are passing `max_tokens: 3000,` which is a likely cause.
Should I be increasing that? I thought that 3000 is more than adequate for a 3000 characters.
