### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position X

### ISSUE THREAD

**Issue by hiroshinishio** [openai/openai-node#596]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The following arguments were received at Function Calling.

```
{
functionArgText: `{"query": "What do I want to be by the time I'm 40?"}{"query": "Where do I want my career to be by the time I'm 40?"}{"query": "What kind of family do I want to have by the time I'm 40?"}`
}
```

And trying to parse the above,

`SyntaxError: Unexpected non-whitespace character after JSON at position 53`

I was told "SyntaxError: Unexpected non-whitespace character after JSON at position 53 For some reason, it often happens that similar queries are repeated 3 times, like this one. What should I do?

### To Reproduce

1. Use OpenAI API via Node.js
2. Set a Tool

```
export const googleSearchSchema: AssistantCreateParams.AssistantToolsFunction = {
  type: "function",
  function: {
    name: "googleSearch",
    description: "Search the web using Google Custom Search Engine API.",
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: `The search query. Multiple search terms should be separated by spaces. DO NOT use line breakers such as "\\n". The number of terms should be between 1 and 10. Less is better. Use Google search operators to refine your search. For example 1, "site:en.wikipedia.org" will search only Wikipedia.`,
        },
      },
      required: ["query"],
    },
  },
} as const;
```

### OS

macOS

### Node version

v20.10.0

### Library version

"openai": "^4.24.0",

**Comment by rattrayalex** [comment]
Hi @hiroshinishio . I recommend our `runTools` helper method, which will automatically attempt to recover from a situation like this.

**Comment by hiroshinishio** [comment]
Hi @rattrayalex Thank you for your introduction to the runTools helper method.
However I use this in stream mode.
Does that `runTools` support stream?
If not, I would be happy if you share with us how to avoid almost infinite \\n\\n\\n\\n\\n... loop like this.

```
functionArgText: '{"query":"\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n'}
```

**Comment by hiroshinishio** [comment]
Hi @rattrayalex I tried to use `runTools` with stream and it run as a stream but provided tool argument and it responsed an infinite `\\n\\n\\n\\n`... Any other workaround?

**Comment by hiroshinishio** [comment]
Also this tool description did not help.

> Google search query. The search query must contain either a sentence such as "What is the capital of France?" or one or more multiple search terms separated by spaces, such as "France capital". NEVER use new line strings such as "\n" or "\\n" in your search query, as this will result in an error. The number of keywords should be in the range of 1 to 10, the fewer the better. NEVER repeat the same search query or object.

**Comment by rattrayalex** [comment]
I'm glad `runTools` helped!

For help with prompt engineering, I suggest asking fellow developers in the [OpenAI Discord](https://discord.com/invite/openai) server.

**Comment by hiroshinishio** [comment]
No I mean `runTools` did not help for me.

**Comment by rattrayalex** [comment]
Yes, that sounds like a prompt engineering problem to me. For that, you should seek help elsewhere, such as Discord.

**Comment by hiroshinishio** [comment]
I successfully resolved this and here is the prompt for people who will experience the same issue in the future.

```
Google search query. The search query must contain either a sentence such as '{"query":"What is the capital of France?"}' or one or more multiple search terms separated by spaces, such as '{"query":"France capital"}'. NEVER, NEVER, EVER use ANY new line strings SUCH AS "\n", "\\n", "\\\n", OR "\\\\n" in the search query, BECAUSE THIS WILL RESULT IN A CRITICAL ERROR like '{"query":"\\nWhat is the capital of France?"}'. The number of keywords should be in the range of 1 to 10, the fewer the better. NEVER repeat the same search query or object. 
```

**Comment by TiagoGouvea** [comment]
I'm facing this today on version `"openai": "^4.80.1"`

```
SyntaxError: Unexpected non-whitespace character after JSON at position 164 (line 2 column 1)
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/helpers/zod.mjs:58:42)
    at parseResponseFormat (file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/lib/parser.mjs:80:36)
    at file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/lib/parser.mjs:66:21
    at Array.map (<anonymous>)
    at parseChatCompletion (file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/lib/parser.mjs:53:40)
    at file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/resources/beta/chat/completions.mjs:22:42
    at file:///Users/tiagogouvea/www/agencyAgents/node_modules/openai/core.mjs:74:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callOpenAI (file:///Users/tiagogouvea/www/agencyAgents/src/callModel.ts:100:20)
```

I thought that providing a `response_format` with a zodObject the model would respect the "rules", but it's failing.

**Comment by TiagoGouvea** [comment]
It happens everyday...  I have been using [jsonrepair](https://github.com/josdejong/jsonrepair/) to to handle some of the broken JSON, but there are cases where neither it can fix it.

I created a issue for [listing these cases](https://github.com/josdejong/jsonrepair/issues/139)
