### ISSUE TITLE
openai.createEmbedding() bug: cannot pass in array for "input" param

### ISSUE THREAD

**Issue by Johnrobmiller** [openai/openai-node#60]
### Describe the bug

When I pass in an array of strings for the "input" param as specified [here](https://platform.openai.com/docs/api-reference/embeddings/create), the connection times out and eventually I get an error 500 with the error message: "Error: read ECONNRESET".

Passing in a non-array string for "input" works fine.

I am using Next.js using their serverless endpoints testing on localhost.

### To Reproduce

Reproduction info in description

### Code snippets

```JavaScript
try {
    const promptEmbeddingsRes = await openAi.createEmbedding({
      model: 'text-embedding-ada-002',
      input: ['test', 'test', 'test'], 
    })
    console.log('prompt embeddings', promptEmbeddingRes.data.data)
    return res.status(200).json(promptEmbeddingsRes.data.data)
  } catch (e) {
    console.error('Error creating embedding: ', e)
    return res.status(500).send("Error creating embedding: " + e)
  }
```

### OS

macOS

### Node version

v16

### Library version

3.1

**Comment by Johnrobmiller** [comment]
Whoops, I stuck `promptEmbeddingRes.data.data` in the `.json()`, and that was not allowed. Once i fixed that, the api worked fine.

**Comment by Johnrobmiller** [comment]
Nope, the error happened again after that json issue was fixed, so reopening this

**Comment by aashutoshrathi** [comment]
Hey! I'm facing this issue in the streaming APIs as well

**Comment by rattrayalex** [comment]
Does this issue persist in [v4 of this library](https://github.com/openai/openai-node/discussions/182)? If so, you may need to tokenize your strings to pass them as an array.
