### ISSUE TITLE
Typescript - cannot build with openai import

### ISSUE THREAD

**Issue by mkontsek** [openai/openai-node#602]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

<img width="668" alt="image" src="https://github.com/openai/openai-node/assets/2892242/7caecdc6-b8e9-4955-9b80-bae6f1f37021">

Cannot use named exports, need to circumvent with unusual type `OpenAI.Beta.AssistantCreateParams` and `OpenAI.Beta.Threads.MessageContentText`

### To Reproduce

1. Create a turborepo with nextjs and openai lib.
2. Add the following type imports
```
import type { AssistantCreateParams } from 'openai/src/resources/beta/assistants/assistants';
import type { MessageContentText } from 'openai/resources/beta/threads';
```
3. Run the build

Expected state: Build is ok

Observerd state: Build failed on `Type error: 'opts' is declared but its value is never read.` at `../../node_modules/.pnpm/openai@4.24.1_encoding@0.1.13/node_modules/openai/src/core.ts:187:25`

### OS

macOS 14.1.1

### Node version

node v21.2.0

### Library version

openai 4.24.1

**Comment by rattrayalex** [comment]
Don't import from `openai/src`. 

You need to replace `from 'openai/src/resources/beta/assistants/assistants';` with `from 'openai/resources/beta/assistants/assistants';`
