### ISSUE TITLE
Nextjs + Typescript - cannot start application - Uncaught SyntaxError: Identifier 'Audio' has already been declared

### ISSUE THREAD

**Issue by mkontsek** [openai/openai-node#603]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

<img width="1087" alt="image" src="https://github.com/openai/openai-node/assets/2892242/023b6c49-26e9-42bb-80f5-6db1a3d0114f">

### To Reproduce

1. Create a turborepo with nextjs and openai imports
2. Build the app
3. Start the app

Expected behavior: App starts

Observed behavior: White screen with `Uncaught SyntaxError: Identifier 'Audio' has already been declared` in console

### OS

macOS 14.1.1

### Node version

node v21.2.0

### Library version

openai 4.24.1

**Comment by rattrayalex** [comment]
Hmm, that's not a lot to go on. Can you share a stackblitz that minimally reproduces the issue?

**Comment by rattrayalex** [comment]
Thank you @mutewinter ! I'll close this accordingly.

**Comment by rafhofman** [comment]
I confirm I had a similar problem recently and fixed it by bumping the Next.js version

**Comment by sumanwave** [comment]
Upgrading to Next.js 14.0.4 resolved this issue for me.
