### ISSUE TITLE
Conversation and Parent Message Id Feature Request

### ISSUE THREAD

**Issue by moradi-morteza** [openai/openai-node#61]
The **conversation_id** and **parent_id** parameters can be used to keep track of the context of a conversation between a user and an AI.

The **conversation_id** parameter is a unique identifier for a specific conversation, and it can be generated by the client. This allows the API to keep track of all messages in a specific conversation and return relevant responses.

The **parent_id** parameter is used to identify the previous message in the conversation and provides context for the current message. By including the parent_id in the API request, you can indicate to the API which message should be considered the previous message in the conversation, and the API can use this information to generate a more contextually appropriate response.

``` javascript
async function sendMessage(conversation_id, parent_id, message) {
  const response = await axios.post('https://api.openai.com/v1/engines/davinci/completions', {
    prompt: message,
    max_tokens: 100,
    temperature: 0.5,
    n: 1,
    conversation_id,
    parent_id
  }, {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer <API_KEY>'
    }
  });

  return response.data.choices[0].text;
}
```

**please add support them to returned response from api and send request api.**

**Comment by iosifnicolae2** [comment]
any news about this functionality?

**Comment by ssgriffen** [comment]
Agree this would be useful. Currently you have to send the entire conversation via the "messages" property to give the AI context into the whole conversation. But you quickly hit the 4000 token limit. Starting a new conversation would wipe the context?

**Comment by ericwangqing** [comment]
Maybe we should use the `createChatCompletion` method instead in this situation. Unfortunately, the server side doesn't hold historical messages, and we have to manage them by ourself.

**Comment by rattrayalex** [comment]
Related: https://github.com/openai/openai-node/issues/149

We are considering adding helper methods for this in the future.

**Comment by rattrayalex** [comment]
Closing this as it's an API feature request rather than a client library feature request. If you're still interested in this functionality, please post it in [community.openai.com](https://community.openai.com)

**Comment by internauticos** [comment]
Hi everybody. Any news about this feature?
