### ISSUE TITLE
Function calls are running even after restarting the service

### ISSUE THREAD

**Issue by milosmns** [openai/openai-node#610]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hi, I believe I have found a major issue in the SDK.

Here's what I'm doing:

1. Firebase functions deployment
2. Single API contact point for users (`/message`)
3. After `/message` is called with the latest chat message, I do the following:
    a. Collect message history from the DB
    b. Assemble the messages to call Open AI
    c. Assemble the list of functions to add (I use the `.beta` module)
    d. Send all functions and past messages to OpenAI + use automatic function calling
4. Report the result back to the caller

Now this setup works, almost always. However, there's a critical problem I'm facing:

### >> Function calling gets stuck in a loop and calls my functions forever <<

---

Stuff that I've observed so far:

- Functions are being called and results are being processed by GPT always, whether the function result is successful or not
- Functions are being called and results are being processed by GPT always, whether the API token is valid or not (I changed mine on purpose to further test)
- Functions are being called even after **redeploying Firebase functions with the new SDK version**
- Deleting Firebase functions and recreating them doesn't solve the problem
- I couldn't reproduce this locally on my machine

I don't know any way of stopping the execution. Please advise.

Note: I acknowledge that I might be doing something else wrong. However, it seems likely that this SDK is to blame, because I never had this problem until I started using `.beta` with automatic function calling.

Thanks for the support in advance.

### To Reproduce

I already summarized what I'm doing in the description.

### OS

Linux

### Node version

Node 18

### Library version

4.17.4, 4.24.1

**Comment by rattrayalex** [comment]
Hmm, this sounds like more of a Firebase issue – the SDK can't make successful requests without a valid API key, for example.

Note that regarding this:
> Functions are being called and results are being processed by GPT always, whether the function result is successful or not

I'm not sure what you consider "successful", but throwing an error from one of your functions should halt execution.

For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!
