### ISSUE TITLE
Why is the result of my request response always incomplete? 

### ISSUE THREAD

**Issue by liujiapeng** [openai/openai-node#62]
### Describe the bug

Is there a maximum length set for the output result?

![image](https://user-images.githubusercontent.com/47778412/219552135-ae427300-fcb3-412c-b0fa-0a5478e9009b.png)

![image](https://user-images.githubusercontent.com/47778412/219552194-790c94b8-2e7a-4947-b11d-f73331d24e9d.png)

### To Reproduce

i just try to run the demo and find that the result is always incomplete

### OS

windows

### Node version

node v14.16.0

### Library version

openai v3.1.0

**Comment by timegated** [comment]
Hi, it looks like you need to add the max_token property to the options argument.

The max_token property: https://github.com/openai/openai-node/blob/master/dist/api.d.ts#L86

**Comment by yudapc** [comment]
> Hi, it looks like you need to add the max_token property to the options argument for the createCompletion call on line 11.
> 
> The max_token property: https://github.com/openai/openai-node/blob/master/dist/api.d.ts#L86

I tried set `max_tokens: 1024` and works for me.

Thank you @timegated
