### ISSUE TITLE
Open AI Bug Reveals Previous User Response Instead of Mine

### ISSUE THREAD

**Issue by androidinfotech** [openai/openai-node#63]
### Describe the bug

When I ask Rewrite the previous response Or Show a Previous Response instead of My answer, it shows a different user response instead of my prompts every time.
![2023-02-19 16 38 10](https://user-images.githubusercontent.com/17807617/219944349-2b88ce40-47ea-4f22-8ae1-98ec0412b222.jpg)
![2023-02-19 16 38 50](https://user-images.githubusercontent.com/17807617/219944350-0b704213-d088-40ff-8aab-3c0974b1dd0d.jpg)

### To Reproduce

Rewrite the previous response

### OS

Windows 10

### Node version

Node Unknown

### Library version

ChatGPT Feb 13 Version

**Comment by kitfit-dave** [comment]
Do you have an actual transcript, not just two disconnected screenshots? Do you have something reproducible? I would want to know how you know it's the "previous user's response" and not just some made-up stuff? If anything it is likely to just be that, however, if I ask it to rewrite the previous response as the first message in a session, it responds with "I apologize, but I cannot rewrite my previous response as I do not have any previous interactions with you." or something similar.
