### ISSUE TITLE
Improved docs for runTools helper

### ISSUE THREAD

**Issue by Rohan-raftlabs** [openai/openai-node#630]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Improved docs for the runTools method to integrate custom functions to the open ai client

### Additional context

The docs for the runTools helper method seem to be very limited at the moment.The method is indeed a great abstraction to passback tool responses to GPT automatically but seems to remove a bunch of necessary things from the response. The finish_reason for instance.
It will be great to have more docs on this function as tools serve a very key purpose in implementing AI personas specific to several business usecases. Would love to use this abstraction but the removal of other relevant keys from the response makes it a deal breaker.If the docs do exist please point to the same.use cases

**Comment by rattrayalex** [comment]
Have you seen https://github.com/openai/openai-node/blob/master/helpers.md? 

I agree we should add better `runTools()` docs across OpenAI's developer documentation – I believe @logankilpatrick is working on that!
