### ISSUE TITLE
API question:  how to make a uuid for topic, and can keep post request(ask questions) in this uuid topic?

### ISSUE THREAD

**Issue by gowy222** [openai/openai-node#64]
### Describe the feature or improvement you're requesting

such as Create completion get 1st response, 
and then I need keep continue ask question based on this opened completion. 

In case I need start two topic/task/completion at one time, and can keep asking each other... like one task for help me doing office doc, and other one for doing excel... at the same time in two completion, so i need uuid for completion 
thus, during next post, i wanna bring this uuid to make sure GPT in the right track.

**Comment by jackson-sandland** [comment]
I am also interested in how to maintain context between requests. Is the use of a `uuid` the way we should be handling this? I've seen some approaches where you include previous responses in role "system" messages but I'm not sure how scalable this is. How does ChatGPT as a website preserve context in a single "chat". 
This is the approach I mentioned that does work but not sure about scalability: 
``` 
const prevContext = "How would I ensure my ChatGPT web app is scalable?"
const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: [
        {role: "system", "content": "Act as a Staff Software Engineer at Google who is an expert in LLMs."},
        {role: "system", content: `${prevContext}`},
        {role: "user", content:`${body}`}],
  });```
By including a previous question from the user and including when the new question is asked, the API will return an answer to the next question that preserves the context of the previous question. If this is not included I'm seeing responses from the API saying it has no idea what I'm talking about if the follow up questions lack context.

**Comment by jackson-sandland** [comment]
One approach to solving this is saving the prompt / content from previous invocations of the OpenAI API and then retrieving them on subsequent invocations and passing them into the API call like this: 
```  
// Create an array of messages for the OpenAI API
  const messages = [
    { role: "system", content: AI_DIRECTIVE },
    ...conversationHistory.map((turn) => ({ role: "user", content: turn.prompt })),
    { role: "user", content: `${prompt}` },
  ];
  logger.debug(`These are the messages: ${JSON.stringify(messages)}`);

  const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages,
  });
```
