### ISSUE TITLE
Unnecessary required `isJsonMime` property

### ISSUE THREAD

**Issue by andreasciamanna** [openai/openai-node#65]
### Describe the bug

`BaseAPI::constructor` requires an instance of `Configuration`.

`Configuration` class requires setting an unnecessary `isJsonMime` property.

### To Reproduce

As per the docs, to create a new instance of `OpenAIApi`, this should suffice:

```ts
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
```

When I do that, TypeScript complains because I must implement `isJsonMime(mime: string): boolean;`.

The error goes away if I write it as such:

```ts
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
  isJsonMime: () => true,
});
```

### OS

Linux (Ubuntu) 22.10

### Node version

v18.7.0

### Library version

3.1.0

**Comment by GeorgeMD** [comment]
I thought I had the same issue, but I was using the library wrong. In Typescript I was writing:
```
const config: Configuration = {
  apiKey: ...,
}
```

And it was asking for `isJsonMime`. However the correct usage is:
```
const config = new Configuration({
  apiKey: ...
});
```

This way it doesn't ask for `isJsonMime` anymore. Hope this helps anyone stumbling upon this.
