### ISSUE TITLE
Stream is aborted unexpectedly

### ISSUE THREAD

**Issue by arata-ae** [openai/openai-node#655]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm using OpenAI SDK in the client (Next.js) and server (App Router, edge runtime) setting.

The issue is that if I passed an `AbortController` to the fetch call, the stream was aborted as soon as it's initialized on the client side. I received no content/error on the client side, and only "Error: aborted" on the server side.

This is my first time using this SDK, but I had read the docs and scoured the issues on GitHub. I'm sorry if I missed anything obvious.

### To Reproduce

Client code:

```ts
const abort = new AbortController();
const res = await fetch('http://localhost:3000/api/chat', {
  body: JSON.stringify(params),
  headers: { 'Content-Type': 'application/json' },
  method: 'POST',
  signal: abort.signal,
});

const stream = ChatCompletionStreamingRunner.fromReadableStream(res.body);
console.log(abort.signal.aborted); // false

// not called
stream.on('content', (delta) => {...});

// not called
stream.on('error', (err) => {});

stream.on('abort', () => {
  // abort callback called
  console.log(abort.signal.aborted); // true
});
```

Server code:
```ts
export const POST = async (req: Request) => {
  const params: OpenAI.ChatCompletionCreateParamsStreaming = await req.json();

  const stream = openai.beta.chat.completions.stream(params, {
    signal: req.signal, // even if I removed this line, the issue still persists
  });

  return new Response(stream.toReadableStream());
};
```

Sanity check: if I don't pass the abort controller to the fetch call, I won't have this issue (obviously).

For personal reference, this issue is similar to #194

### OS

macOS

### Node version

18

### Library version

4.26.0

**Comment by GureSinghh** [comment]
it was working fine from past few days now it is aborting from back end side even I haven't changed the code . did you find any fix ? 

```
Error:-
Stream {
  iterator: [AsyncGeneratorFunction: iterator],
  controller: AbortController { signal: AbortSignal { aborted: false } }
} 
```
