### ISSUE TITLE
The `create` call fails on some non-unicode character combinations

### ISSUE THREAD

**Issue by Fmstrat** [openai/openai-node#658]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When making calls using `openai.chat.completions.create` and passing in `messages.content` of a non-unicode character such as `¼` instead of unicode friendly `1/4`, the call to OpenAI times out.

### To Reproduce

1. Use the code snippet below
2. Get a request timed out

### Code snippets
This is a slimmed down version of what I've run into, and may require more of our prompt and tooling, but I can provide more context if required:

```JavaScript

const response = await openai.chat.completions.create({
    model: 'gpt-4-1106-preview',
    messages: [
      {
        role: 'user',
        content: 'Tell me about ¼',
      },
    ]
});
```
```


### OS

Docker

### Node version

20.3.1

### Library version

^4.21.0

**Comment by rattrayalex** [comment]
Is this an SDK bug, or a problem in the API? What happens if you do the same with curl?

**Comment by rattrayalex** [comment]
I cannot repro – I assume this was a problem with the underlying model during preview and has been resolved.
