### ISSUE TITLE
gpt-3.5-turbo model example

### ISSUE THREAD

**Issue by theavijitsarkar** [openai/openai-node#66]
### Describe the feature or improvement you're requesting

Hey guys, Amazing work on the quick update for the node library with ChatGPT api.
Since the website's playground still does not have a gpt-3.5-turbo model option, neither is there any documentation on node. Could you please add how to use gpt-3.5-turbo model with a few examples.

Thanks

**Comment by Frohrer** [comment]
See examples here: https://platform.openai.com/docs/api-reference/chat/create?lang=node.js

**Comment by theavijitsarkar** [comment]
Thank you for pointing me the right direction. Got it working!

**Comment by theavijitsarkar** [comment]
@Frohrer I had another doubt, if you could nudge me in the right direction.

I wish to build a conversational app, is there a way I could pass the id of the response and continue the conversation.
Current docs suggests that I have to resend the entire conversation to the api/sdk.

**Comment by Frohrer** [comment]
You are correct. Unfortunately there is no way to continue a conversation context without sending the entire history with each response.

**Comment by theavijitsarkar** [comment]
I see! Thanks for the confirmation, I hope this becomes available soon.
