### ISSUE TITLE
Text-to-Speech Stream

### ISSUE THREAD

**Issue by ghostlexly** [openai/openai-node#660]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Can we get the streaming for text-to-speech ?

### Additional context

Example for the python library can be found here 

- https://platform.openai.com/docs/guides/text-to-speech

**Comment by rattrayalex** [comment]
Yes, an example of how to do that is here: https://github.com/openai/openai-node/blob/c9bb4edaf5bc72ccd81fd7978abd468169255f1c/examples/audio.ts#L19-L31
