### ISSUE TITLE
Support command line usage

### ISSUE THREAD

**Issue by fulldecent** [openai/openai-node#665]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Use `openai` bin command from the command line like:

```sh
openai api images.generate -m dall-e-3 -p "$DESCRIPTION" -n 1 -s "$SIZE"
```

This could be similar to or different than [the Python SDK command line](https://github.com/openai/openai-python).

### Additional context

It will be nice to have both the npm and Python products to support the command line because there's way more people that know how to use a command line tool than know how to write source code.

**Comment by rattrayalex** [comment]
Thanks for the suggestion – unfortunately, we do not expect to do this anytime soon, as it's simply too much duplication of work (and we don't want to install the python package for everyone who npm installs the SDK).

However, I could see it being beneficial to add the openai CLI to `brew` and similar distribution channels – what do you think?
