### ISSUE TITLE
[gpt-3.5-turbo] Getting "Invalid status code: Cannot read properties of undefined (reading 'create')"

### ISSUE THREAD

**Issue by mikron123** [openai/openai-node#68]
### Describe the bug

I'm getting "Invalid status code: Cannot read properties of undefined (reading 'create')" on the next Node JS code:

### To Reproduce

`const { Configuration, OpenAIApi } = require("openai");`

` const openai = new OpenAIApi(configuration);`

`const completion = await openai.ChatCompletion.create(`
             ` model="gpt-3.5-turbo",`
             ` messages=[`
                     `   {"role": "system", "content": "You are a helpful assistant."},`
                     `   {"role": "user", "content": "How are you?"},`
               ` ],`
                  `  max_tokens=1000,`
           ` );`

### OS

Windows 11

### Node version

Node.js v18.12.1

### Library version

3.2.0

**Comment by mikron123** [comment]
Use wrong syntax. createChatCompletion

**Comment by getlittletech** [comment]
Then the documentation is wrong on this page:
https://platform.openai.com/docs/guides/chat/introduction
