### ISSUE TITLE
Enhancing `completions` Endpoint Response with Maximum Available Tokens

### ISSUE THREAD

**Issue by MiguelAngelGarciaGomez** [openai/openai-node#695]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I've been looking into how we could further enrich the data returned from a request to the `completions` endpoint. One piece of information that might be highly beneficial is the inclusion of the maximum available tokens in the meta information of the response.

Currently, the [endpoint's response](https://platform.openai.com/docs/api-reference/making-requests) already includes useful meta information such as the `finish_reason`. However, having extra data about the available tokens could aid us in effectively making follow-up requests or better managing our token usage.

### Additional context

There's already a palpable demand for this feature from the user community, as evidenced by discussions such as this [post on the community page](https://community.openai.com/t/max-tokens-how-to-get-gpt-to-use-the-maximum-available-tokens/433367). Unfortunately, there isn't a practical workaround available to them at the moment.

Given the circumstances, I believe incorporating this feature directly into the endpoint's response could greatly improve its usefulness. Looking forward to your thoughts on this.

**Comment by rattrayalex** [comment]
This sounds like a feature request for the underlying OpenAI API and not the Node library, so I'm going to go ahead and close this issue.

The community post is the appropriate place to track this issue.
