### ISSUE TITLE
CreateCompletionRequest Types

### ISSUE THREAD

**Issue by myleslinder** [openai/openai-node#7]
As part of a 'Pre-launch Review' we've been instructed to provide a user id as part of our completion requests:

> Pass a uniqueID for every user w/ each API call (both for Completion & the Content Filter) e.g. user= $uniqueID. This 'user' param can be passed in the request body along with other params such as prompt, max_tokens etc.

However, the `CreateCompletionRequest` interface does not have an optional `user` property. 

Let me know if I'm missing anything or if anything else is required on my end.

**Comment by rattrayalex** [comment]
Our [upcoming v4](https://github.com/openai/openai-node/discussions/182) should have the correct type here.
