### ISSUE TITLE
Batching?

### ISSUE THREAD

**Issue by daweimau** [openai/openai-node#707]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

From the OpenAI [docs](https://platform.openai.com/docs/guides/rate-limits/batching-requests):

>  The OpenAI API has separate limits for requests per minute and tokens per minute.
> 
> If you're hitting the limit on requests per minute, but have available capacity on tokens per minute, you can increase your throughput by batching multiple tasks into each request. This will allow you to process more tokens per minute, especially with our smaller models.
> 
> Sending in a batch of prompts works exactly the same as a normal API call, except you pass in a list of strings to the prompt parameter instead of a single string.

The example code excerpt, which is python, seems to show a legacy API. Roughly:

## Single prompt, no batching
```python
prompt = "Once upon a time,"
 
# serial example, with one story completion per request
  response = client.completions.create(
      model="curie",
      prompt=prompt,
      max_tokens=20,
  )
```
## Batched prompts
```python
prompts = ["Once upon a time,"] * 10
 
# batched example, with 10 story completions per request
response = client.completions.create(
    model="curie",
    prompt=prompts,
    max_tokens=20,
)
```

However, in today's node library, our chat completion must always include `messages: ChatCompletionMessageParam[]` (being: "a list of messages comprising the conversation so far").   

With the current API spec (and current models eg `gpt-4`) and this node library, how can we batch completion requests as described the docs? 

Is it even possible?

**Comment by rattrayalex** [comment]
Sorry, this is only available for the legacy Completions API, not for Chat Completions. We'll look into removing that from the docs.

**Comment by dbersan** [comment]
So it is not possible to make batch requested to chat completion?

**Comment by rattrayalex** [comment]
It is not.
