### ISSUE TITLE
I see the project was updated a few hours ago, does this support "gpt-3.5-turbo"

### ISSUE THREAD

**Issue by phusting** [openai/openai-node#71]
### Describe the feature or improvement you're requesting

I tried the new "gpt-3.5-turbo" with my previous install and I get an 404 error on return.  Has this been updated for the new "gpt-3.5-turbo" model?

**Comment by adamk22** [comment]
You have to use the `createChatCompletion()` method instead of the `createCompletion()` method.

**Comment by phusting** [comment]
I just Homer Simpsoned.....

**Comment by phusting** [comment]
so it no longer  prompt, but a message?  Just confirming

**Comment by phusting** [comment]
I get a "TypeError: Cannot read properties of undefined (reading 'create')"

                    var completion = await openai.ChatCompletion.create({
                        model: "gpt-3.5-turbo",
                        messages: [{ "role": "user", "content": "Hello! world" }]

Any suggestions what I'm doing wrong?  I'm using Javascript.

**Comment by phusting** [comment]
> You have to use the `createChatCompletion()` method instead of the `createCompletion()` method. Read [the docs](https://platform.openai.com/docs/api-reference/chat) for more info.

I just Homer Simpsoned.....

**Comment by NoirVoider** [comment]
gpt-3.5-turbo , createChatCompletion How to use stream: true ?

**Comment by dytra** [comment]
according to the docs it should be like this

```js
const completion = await openai.createChatCompletion({
        model:"gpt-3.5-turbo",
        messages: [{role: "user", content:"Hello"}],
});

**Comment by cumt-robin** [comment]
@phusting  you can try  https://www.npmjs.com/package/gpt-node

**Comment by shospodarets** [comment]
Here is a simple overview of Node.js `openai` usage changes between `text-davinci-003` and `gpt-3.5-turbo` models :
**New code**:
```
const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: [{
        role: "user",
        content: prompt,
    }],
});
console.log(completion.data.choices[0].message.content);
```
**Git diff**:
![image](https://i.imgur.com/ozhDLG6.png)
[Here is more from the official docs](https://platform.openai.com/docs/api-reference/chat/create)

**Comment by abuelgasimsaadeldin** [comment]
hi @shospodarets @dytra @adamk22 

I have followed the instructions but I am getting ```openai.createChatCompletion is not a function``` may I know why is that?

Here is my working GPT 3 Davinci:
![image](https://user-images.githubusercontent.com/68045710/222414221-8bd25165-85cf-4e3f-893f-aedb5c53a00b.png)

And this is my GPT 3.5 Turbo:
![image](https://user-images.githubusercontent.com/68045710/222414530-032e0a94-93c2-405f-a6e0-e3ff149f2139.png)

Your guidance is highly appreciated 🙏

Regards,
Abu

**Comment by robertbak** [comment]
Did you update your `openai` library version from npm?

**Comment by abuelgasimsaadeldin** [comment]
Hi @robertbak,

Thanks allot for that! I've updated from version 3.1.0 to 3.2.1 and I'm able to get a response now.

I am getting the following error now however: ```TypeError: Cannot read properties of undefined (reading '0')``` from the code ```console.log(completion.data.choices[0].message.content);```

For reference, I've printed out just the "completions" and this is what I get:
![image](https://user-images.githubusercontent.com/68045710/222418844-cebab1f4-a317-4e6b-8792-2589ba11d5c3.png)

**Comment by abuelgasimsaadeldin** [comment]
@robertbak I kind of see the pattern better when I put it this way, I guess it's just a matter of extracting out the answer from the response..

Prompt give: "Hello"
Response: "Hello! How can I assist you"
![image](https://user-images.githubusercontent.com/68045710/222433434-9315f829-35f4-4586-a93c-d8bd964b84bb.png)

**Comment by abuelgasimsaadeldin** [comment]
Issue has been resolved, just got rid of ```stream: true```.

> Hi @robertbak,
> 
> Thanks allot for that! I've updated from version 3.1.0 to 3.2.1 and I'm able to get a response now.
> 
> I am getting the following error now however: `TypeError: Cannot read properties of undefined (reading '0')` from the code `console.log(completion.data.choices[0].message.content);`
> 
> For reference, I've printed out the entire "completions" and this is what I get: ![image](https://user-images.githubusercontent.com/68045710/222418844-cebab1f4-a317-4e6b-8792-2589ba11d5c3.png)

**Comment by jgui1129** [comment]
Hi, how can we use stream? Thank you.

**Comment by shospodarets** [comment]
@jgui1129 @phusting Here you can find the working and supported example of latest ChatGPT API used with the streams:
https://github.com/Nutlope/twitterbio/blob/main/utils/OpenAIStream.ts
https://github.com/Nutlope/twitterbio/blob/main/pages/api/generate.ts

 + live demo
https://www.twitterbio.com/ 😉
