### ISSUE TITLE
SDK 4.28.4 Too large message error

### ISSUE THREAD

**Issue by dh-free** [openai/openai-node#713]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

APIError: 431 <html>
  <head>
    <title>Request Header Fields Too Large</title>
  </head>
  <body>
    <h1><p>Request Header Fields Too Large</p></h1>
    Error parsing headers: &#x27;limit request headers fields&#x27;
  </body>
</html>

### To Reproduce

    const completion = await openai.chat.completions.create({
      messages: [
        { role: 'system', content: await this.promptUtil.getSystemPrompt() },
        { role: 'user', content: message },
      ],
      model: 'moonshot-v1-32k',
    });

If message is too large, an error will be thrown

### OS

windows

### Node version

Node V18.17.1

### Library version

openai V4.28.4

**Comment by dh-free** [comment]
Lower version to 4.20.1 will work

**Comment by ECKSTASYY** [comment]
Thank you!

`npm i openai@4.20.1`

For those that want copy paste.

**Comment by ECKSTASYY** [comment]
Correcting Myself. The issue for me was that i was confusing context window size and maximum of output tokens. 😔
