### ISSUE TITLE
Open ai moderation not working for node js 

### ISSUE THREAD

**Issue by rajdavid** [openai/openai-node#732]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 

### To Reproduce

make the call to open ai using this      await this.openai.createModeration("Hello"))   

### Code snippets

```JavaScript
const config = new Configuration({
      apiKey: process.env.OPEN_AI_KEY,
    });
    this.openai = new OpenAIApi(config);
```

### OS

Windows

### Node version

v18.16.0

### Library version

"^3.2.1"

**Comment by rattrayalex** [comment]
You need to upgrade your code to the latest SDK version. See [the v4 migration guide](https://github.com/openai/openai-node/discussions/217).
