### ISSUE TITLE
TS error: Property 'delta' does not exist on type 'CreateChatCompletionResponseChoicesInner'. ts(2339)

### ISSUE THREAD

**Issue by brandonmcconnell** [openai/openai-node#74]
### Describe the bug

```
Property 'delta' does not exist on type 'CreateChatCompletionResponseChoicesInner'.ts(2339)
```

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5913254/222353711-6ab85140-2814-4a48-ad9b-cb5f59964555.png">

### To Reproduce

When streaming, try accessing `completion.data.choices?.[0].delta` instead of `completion.data.choices?.[0].message`

### OS

macOS v13.1 (22C65)

### Node version

node v18.12.1

### Library version

openai v3.2.1

**Comment by rattrayalex** [comment]
We have an [upcoming version v4.0.0](https://github.com/openai/openai-node/discussions/182) that ovehauled our TypeScript types; please give it a try and let us know in the thread whether it suits your needs!
