### ISSUE TITLE
Why is `usage` optional?

### ISSUE THREAD

**Issue by MatanYadaev** [openai/openai-node#746]
### Describe the bug

https://github.com/openai/openai-node/blob/abb0be7bcc6777e2efa8682c8a044842addb755a/src/resources/chat/completions.ts#L76-L79

### To Reproduce

```ts
const chatCompletion = new OpenAI({ ... }).chat.completion.create({ ... })

const totalTokens = chatCompletion.usage.total_tokens; // TS18048: `chatCompletion.usage` is possibly `undefined` 
```

### Library version

v4.31.0

**Comment by rattrayalex** [comment]
When streaming, this is not supplied from the server currently.

**Comment by MatanYadaev** [comment]
@rattrayalex Worth mentioning that in the JSDoc of this property. I thought it's optional only when streaming, but wasn't sure if in the other cases, it will 100% base present.

**Comment by rattrayalex** [comment]
That's a good point, I'll bump that to the relevant team (this would flow through from the OpenAPI spec).

**Comment by rattrayalex** [comment]
Related: https://github.com/openai/openai-node/issues/506
