### ISSUE TITLE
localVarFormParams.getHeaders is not a function

### ISSUE THREAD

**Issue by sidmohanty11** [openai/openai-node#75]
### Describe the bug

When I am using OpenAI node SDK to `createTranscription`,

I am sending it the file like this,
```
  const mediaBlob = await fetch(url)
    .then(response => response.blob());

const audio = new File(
    [mediaBlob],
    'demo.mp4',
    { type: 'video/mp4' },
  );

const resp = await openai.createTranscription(audio, 'whisper-1'); // even audio.text(), stream() etc doesn't work
```

It's throwing me `localVarFormParams.getHeaders is not a function`

### To Reproduce

1. Try to send an audio file for transcription using `openai.createTranscription`
2. Try to send a file
3. Error thrown - `localVarFormParams.getHeaders is not a function`

### OS

macOS

### Node version

Node v16.16.0

### Library version

openai v3.2.1

**Comment by estepona** [comment]
I had the same issue. Same error with cresateTranslation API

**Comment by AlexNeep** [comment]
You need to pass in your API key as part of the configuration object

```javascript
const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
  });
  const openai = new OpenAIApi(configuration);
```

**Comment by el7or** [comment]
> Not a solution I recommend, but it does make the createTranscription function accessible. So for a testing/dev environment I don't see any harm 🙂
> 
> ```js
> class CustomFormData extends FormData {
>     getHeaders() {
>         return {}
>     }
> }
> 
> const configuration = new Configuration({
>     apiKey: process.env.OPENAI_API_KEY,
>     formDataCtor: CustomFormData
> })
> ```

This fixed it, Thank you.

**Comment by TomPeak** [comment]
I have the same Problem with createImageVariationes. I do ny app in react. Tried some way, always this error. No Syntax highlighting in WebStrom.

**Comment by rattrayalex** [comment]
Our upcoming [v4](https://github.com/openai/openai-node/discussions/182) fixes this; please give it a try!
