### ISSUE TITLE
Add support for error types.

### ISSUE THREAD

**Issue by anzemur** [openai/openai-node#76]
### Describe the feature or improvement you're requesting

For error handling, it would be great if error types were defined in the library, like in the python version (https://platform.openai.com/docs/guides/error-codes/python-library-error-types). It would be easier to detect rate limit errors, perform exponential backoff only for specific errors, etc.

**Comment by rattrayalex** [comment]
Hi @anzemur, we have an [upcoming version v4.0.0](https://github.com/openai/openai-node/discussions/182) that includes granular error types; please give it a try and let us know in the thread whether it suits your needs!
