### ISSUE TITLE
[Important] Add max_prompt_tokens and max_completion_tokens for Runs API

### ISSUE THREAD

**Issue by Neilord** [openai/openai-node#765]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Hi, I belive that `max_prompt_tokens` and `max_completion_tokens` are essential features for using the whole Assistants API. Without being able to specify the max tokens, the thread is just getting longer, and running the AI model getting very expensive. Please add the `max_prompt_tokens` and `max_completion_tokens` parameters to the `openai.beta.threads.runs.create`. Thanks!

**Comment by rattrayalex** [comment]
I believe @pstern-sl is working on this.

**Comment by pstern-sl** [comment]
This is available starting in version 4.34 - released today https://github.com/openai/openai-node/pull/767

**Comment by Neilord** [comment]
Awesome! Thanks a lot for implementing this! :)
