### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by jellehak** [openai/openai-node#780]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

On node 21, shows a warning:
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### To Reproduce

1. Use node v 21
2. Make a request with the library

### Code snippets

```JavaScript
export async function convert({ prompt }) {
    const response = await openai.images.generate({
        prompt: `${prompt}`,
        n: 1,
        size: "1024x1024",
    });
    return response.data
}
```
```


### OS

macOS

### Node version

Node v21.7.2

### Library version

openai v4.37.1

**Comment by marck283** [comment]
Looks like the most recent version of this library still depends on node-fetch@2.6.7, but the developers here are trying to move to undici in #402.

**Comment by rattrayalex** [comment]
Yes, see other issues linking to that PR. Closing as a duplicate.
