### ISSUE TITLE
Thread.message.attachment

### ISSUE THREAD

**Issue by oljaskrut** [openai/openai-node#785]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I see you've changed types, so that 
attachment : {
file_id: string
tools: ["file_search" | "code_interpreter"]
}

but API errors with expected attachment.tools[0] be object not string

plus: i could not get files work with assistant v2, via both attachment and assistant/thread vectorStore attachments

### To Reproduce

1. Attach file to message, via attachment = [{file_id: your_file_id, tools: ["file_search"] }
2. Get API error when creating thread message

### OS

Windows 11 + WSL 1.0

### Node version

20.11.0

### Library version

4.38.1

**Comment by Clad012** [comment]
+1

**Comment by oljaskrut** [comment]
typing fix introduced in new version

**Comment by DanielHindi** [comment]
even in v2 with the code changes while it doesnt break. the Assistant cannot read files in the thread vector store. But magically sometimes it can.
Super frustrating
