### ISSUE TITLE
Assistant API - tools: [{ type: ‘retrieval’ }] not allowing any more

### ISSUE THREAD

**Issue by DamithaPerera** [openai/openai-node#791]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

couple of months ago I started working with openAI assistant. I created a simple pdf analyzer. I implemented using Nodejs. (“openai”: “^4.31.0”,). When I created the application it worked fine. But reasonly when i delete the all the node_module and installed. then I’m getting an error saying “rgument type {instructions: string, name: string, model: “gpt-3.5-turbo”, tools: {type: “retrieval”}} is not assignable to parameter type AssistantCreateParams”. Seems like now " tools: [{ type: ‘retrieval’ }]" is not working.

below is the code that used to work.

but the best thing is curl version of below code is working perfectly in potsman. I started installing the latest openAI version also. but still same.
Please note that I’m new for openAI.

### To Reproduce

install “openai”: “^4.31.0”

### Code snippets

```JavaScript
const assistant = await openai.beta.assistants.create({
      name: 'recruiter',
      instructions: 'Analyze the give 'file IDs' and return an summary"
      tools: [{ type: 'retrieval' }],
      model: 'gpt-3.5-turbo',
"file_ids": [
    "file-0EtPDfxuS6IUS1AWBY5BNDty",
    "file-5wFhHiCae4ygard1O1aKc2jM",
  ]
    });
```

### OS

windows 11

### Node version

20.10.0

### Library version

^4.31.0

**Comment by oljaskrut** [comment]
try npm i -E openai@4.31.0

**Comment by nknj** [comment]
Hi there -- this tool belongs to an older version of the API and the Node SDK. You can either use older versions of the SDKs, like @oljaskrut pointed out above. Or you can migrate to the new retrieval tool as documented here: https://platform.openai.com/docs/assistants/migration
