### ISSUE TITLE
Incorrect error: file_search tool configuration is invalid. file_ids must be non-empty

### ISSUE THREAD

**Issue by chrisvariety** [openai/openai-node#795]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When creating an assistant with `tools: [{ type: 'file_search' }]`, the `tool_resources: { file_search: { vector_stores: [...] } }` is not evaluated properly. Specifically, when creating a empty vector store, you will receive the following error:

> BadRequestError: 400 file_search tool configuration is invalid. file_ids must be non-empty
    at APIError.generate (file:///Users/chrismcc/workspace/atlas/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///Users/chrismcc/workspace/atlas/node_modules/openai/core.mjs:256:25)
    at OpenAI.makeRequest (file:///Users/chrismcc/workspace/atlas/node_modules/openai/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/chrismcc/workspace/atlas/test.js:10:3)

This is incorrect [per the docs](https://platform.openai.com/docs/api-reference/assistants/createAssistant) which indicates `file_ids` is optional:
![CleanShot 2024-04-22 at 17 59 27@2x](https://github.com/openai/openai-node/assets/44855/297982a7-943f-4aa9-b60f-cd04f8d83810)

Additionally, creating a vector store without `file_ids` works just fine within `openai.beta.vectorStores.create`, so this seems specific to creating the vector store as part of the `openai.beta.assistants.create` call.

### To Reproduce

Specify something like this when creating an assistant:

```
tool_resources: {
  file_search: {
    vector_stores: [
      {
        metadata: {foo: 'bar'}
      }
    ]
  }
}
```

(Note `vector_stores: [{file_ids: []}]` doesn't work either)

### Code snippets

```JavaScript
import OpenAI from 'openai';
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
  maxRetries: 10,
  timeout: 60 * 1000,
  defaultHeaders: { 'OpenAI-Beta': 'assistants=v2' }
});

async function main() {
  await openai.beta.assistants.create({
    instructions:
      'You are a helpful assistant. Use your knowledge base to answer questions.',
    name: 'Test',
    tools: [{ type: 'file_search' }],
    tool_resources: {
      file_search: {
        vector_stores: [
          {
            metadata: {foo: 'bar'}
          }
        ]
      }
    },
    model: 'gpt-3.5-turbo',
    temperature: 1
  });
}

main();
```

(note `file_ids: []` doesn't work either)
```


### OS

macOS 14.0 (23A344)

### Node version

Node v20.11.0

### Library version

openai v4.38.3

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
