### ISSUE TITLE
batch error when upload file vector in file_search type tool assistant ia

### ISSUE THREAD

**Issue by raharinjatovo** [openai/openai-node#805]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

when i upload file vector to file_seach type tool assistant, then I follow instruction from doc, i had that error when i process to finish data :`js  file-batches.js:99
        if (files === null || files.length == 0) {
                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
`

### To Reproduce

1 install
2 create assistant ia tool type file_search
3 upload file for this tools 

### OS

win 10

### Node version

>=20

### Library version

>=5.4.4

**Comment by irakligeek** [comment]
Same error

**Comment by jfernandezrico** [comment]
Same error with library version 4.46.1

**Comment by wgrientidev** [comment]
Hi.

Could you show some code?
I had this error too while I was trying to implement an assistant with file_search.

I do:

- Create files with openai.files.create()
- Create vector store
- CreateAndPoll vector store files.
- Update assistant

```
 const fileData = await openai.files.create({
            file: fs.createReadStream("kit-idraulici.pdf"),
            purpose: "fine-tune",
        });

        let vectorStore = await openai.beta.vectorStores.create({
            name: "Test",
        });

        await openai.beta.vectorStores.files.createAndPoll(
            vectorStore.id,
            {
                file_id: fileData.id,
            }
        );

        await openai.beta.assistants.update(assistant.id, {
            tool_resources: { file_search: { vector_store_ids: [vectorStore.id] } },
        });
```

This works for me but I may have misunderstood your issue.

**Comment by jfernandezrico** [comment]
But what if the purpose of my assistant is "file_search".
Following the Openai API documentation, I need to create a vector store with the new version of the library.
https://platform.openai.com/docs/assistants/tools/file-search/quickstart


`
// Step 1: Create an Assistant with File Search Enabled
const myAssistant = await openai.beta.assistants.create({
       model: "gpt-3.5-turbo-1106",
       instructions:
        "You are a customer support chatbot. Use your knowledge base to best respond to customer queries.",
      name: "Customer Support Chatbot",
       tools: [{ type: "file_search" }],
 });


// Step 2: Upload files and add them to a Vector Store
const fileStreams = ["file1.txt"].map((path) =>
    fs.createReadStream(path)
  );


  // Create a vector store including our files.
  let vectorStore = await openai.beta.vectorStores.create({
    name: "Customer queries Vector Store",
  });

  await openai.beta.vectorStores.fileBatches.uploadAndPoll(
    vectorStore.id,
    fileStreams
  );
`

and here is where the error appears

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll look into this soon.

**Comment by jfernandezrico** [comment]
If you attach directly the file to the new thread, it works!

```
const knowledgeFile = await openai.files.create({
    file: fs.createReadStream("knowledge.txt"),
    purpose: "assistants",
  });

  const thread = await openai.beta.threads.create({
    messages: [
      {
        role: "user",
        content: "What can I buy in your online store?",
        // Attach the new file to the message.
        attachments: [
          { file_id: knowledgeFile.id, tools: [{ type: "file_search" }] },
        ],
      },
    ],
  });
```

**Comment by hnputech** [comment]
> Hi.
> 
> Could you show some code? I had this error too while I was trying to implement an assistant with file_search.
> 
> I do:
> 
> * Create files with openai.files.create()
> * Create vector store
> * CreateAndPoll vector store files.
> * Update assistant
> 
> ```
>  const fileData = await openai.files.create({
>             file: fs.createReadStream("kit-idraulici.pdf"),
>             purpose: "fine-tune",
>         });
> 
>         let vectorStore = await openai.beta.vectorStores.create({
>             name: "Test",
>         });
> 
>         await openai.beta.vectorStores.files.createAndPoll(
>             vectorStore.id,
>             {
>                 file_id: fileData.id,
>             }
>         );
> 
>         await openai.beta.assistants.update(assistant.id, {
>             tool_resources: { file_search: { vector_store_ids: [vectorStore.id] } },
>         });
> ```
> 
> This works for me but I may have misunderstood your issue.

it is working fine with createand pull but when we use the updatreandpull it's throws the error

**Comment by dgellow** [comment]
Hi, thank you all for reporting that issue, we greatly appreciate the discussion and helpful details you already provided.

We will need a bit of time to investigate, it's not directly clear to me if the problem is from our SDK documentation, or OpenAI quick start guide being incorrect / outdated, or if the cause is an actual bug in the SDK or OpenAI backend (or a combination of all of this). I will do some testing on my side and review the thread internally with my colleagues. We will let you know once we have more details, but in the meantime feel free to keep this thread alive.

**Comment by coloz** [comment]
Same error

**Comment by dews** [comment]
This works for me, because uploadAndPoll's parameter is `{ files, fileIds = [] }`
```
 const fileStreams = [
    "a.docx",
    "b.docx",
  ].map((path) => fs.createReadStream(path));

  // Create a vector store including our two files.
  let vectorStore = await openai.beta.vectorStores.create({
    name: "IDM docs",
  });

  await openai.beta.vectorStores.fileBatches.uploadAndPoll(vectorStore.id, {
    files: fileStreams,
  });
```

**Comment by Hussein-Ali-6** [comment]
As mentioned in the comment above, the issue is that the second parameter in `uploadAndPoll` accepts `{ files: Uploadable[]; fileIds?: string[] | undefined; }`. 
I believe there are no issues with the SDK itself, but rather with the documentation. When I copied the code from the documentation into my TypeScript project, it showed a type error.

**Comment by RobertCraigie** [comment]
Really sorry for the confusion here, @Hussein-Ali-6 is correct, the example snippet in the docs isn't correct, we'll get this snippet fixed.

The next release will also fix the error message here.
