### ISSUE TITLE
Vector store file uploadAndPoll has wrong implementation

### ISSUE THREAD

**Issue by ceifa** [openai/openai-node#807]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Whe using the uploadAndPoll helper for vector store files, an error is thrown "NotFoundError: 404 No file found with id"
Looking at the code, this is because the files are uploaded to file api, but not to the vector store api, making it throw when polling if the file was uploaded.

### To Reproduce

Try this with a new file:
`vectorStores.files.uploadAndPoll`

### OS

Any

### Node version

v20

### Library version

4.39.0

**Comment by rattrayalex** [comment]
Thanks for the report, and sorry for the bug. We'll look into it shortly.

**Comment by pstern-sl** [comment]
Hi, I believe this was resolved in 4.40.2. 
https://github.com/openai/openai-node/pull/818
