### ISSUE TITLE
createChatCompletion method returning undefined in the choices array

### ISSUE THREAD

**Issue by ViLourenco** [openai/openai-node#81]
### Describe the bug

I'm using node.js with the official opean ai lib and when I tried to send a request, I got nothing, the choices array is empty.

It's working fine with davinci model, just this new one `model: "gpt-3.5-turbo",` isn't working.

![image](https://user-images.githubusercontent.com/1047262/222527869-5e299097-7249-4cad-ab8b-1b6bfc6fca89.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/1047262/222528452-8a358228-a5fd-41e5-9260-53b492685d2e.png)

### OS

windows

### Node version

v10.19.0

### Library version

3.2.1

**Comment by lucianot** [comment]
The response for the 'gpt-3.5-turbo' model is not `choices[0].text` but rather `choices[0].message.content`. In any case, `choices` should not be empty.

I am also getting an error for the following code:

```
async function gptCompletion() {
  try {
    const response = await openai.createCompletion({
      model: "gpt-3.5-turbo",
      messages: [{"role":"user", "content":"Hello World"}],
    })

    return response
  } catch (e) {
    console.log("Error getting GPT completion: ", e)
    throw e
  }
}

gptCompletion() 
```

Getting an "Error: Request failed with status code 400"

**Comment by Fndroid** [comment]
@lucianot  you should call `createChatCompletion` instead of `createCompletion`

**Comment by tv-ankur** [comment]
@Fndroid its says "openai.createChatCompletion" is not a function

**Comment by benunternaehrer** [comment]
> 



> @Fndroid its says "openai.createChatCompletion" is not a function

Make sure to use the latest version of openai (current: 3.2.1)

**Comment by lucianot** [comment]
> @lucianot you should call `createChatCompletion` instead of `createCompletion`

Worked! Thanks.

**Comment by timashoff** [comment]
To summarize all the issues you may have struggled with during the update to the new **gpt-3.5-turbo** model:

- [ ] `npm update` make sure you are using the latest version of OpenAI, which is 3.2.1
- [ ] this new model optimized for **chat** and you should call `openai.createChatCompletion()` instead of `openai.createCompletion()`
- [ ] the response now is `data.choices[0].message.content` not `data.choices[0].text`

Thanks to everyone who clarified this question above

**Comment by yPrianikc** [comment]
const {Configuration, OpenAIApi} = require('openai');

const configuration = new Configuration({
    apiKey: apiKey
});
it shold be work

**Comment by fractastical** [comment]
You also need this line:

const openai = new OpenAIApi(
  new Configuration({ apiKey: process.env.OPENAI_API_KEY })
);

**Comment by rattrayalex** [comment]
If you still need help working with the API, give the community a try: https://community.openai.com

**Comment by shakstzy** [comment]
you have to write it like this, the syntax has been updated for chatcompletions

const chatCompletion = await openai.chat.completions.create

**Comment by Kamilhc1125** [comment]
const chatCompletion = await openai.chat.completions.create({...})

The response structure also should be modified like below.
console.log(chatCompletion .choices[0].message);
