### ISSUE TITLE
Incorrect TS typing for `finish_reason`

### ISSUE THREAD

**Issue by brandonmcconnell** [openai/openai-node#82]
### Describe the bug

<img width="523" alt="image" src="https://user-images.githubusercontent.com/5913254/222606557-b8f7fcdb-dc83-4da4-b3f4-e734b9ae06e5.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/5913254/222606673-6fb87bc3-9783-4594-8ecf-227d9bf99565.png">

The typing for `finish_reason` sets its type to `string | undefined` but its actual type used is `string | null`.

### To Reproduce

Reference a `CreateChatCompletionResponse` object and access the `finish_reason` property to inspect its type.

### OS

macOS v13.1 (22C65)

### Node version

node v18.12.1

### Library version

openai v3.2.1

**Comment by rattrayalex** [comment]
Thanks for the report; I've opened a PR to the openapi spec here: https://github.com/openai/openai-openapi/pull/60
