### ISSUE TITLE
The library has no method to list threads

### ISSUE THREAD

**Issue by OperationalFallacy** [openai/openai-node#821]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [ ] This is an issue with the Node library

### Describe the bug

There is no method in the API to list threads, although technically they can be listed in the dashboard at https://platform.openai.com/threads (has to be enabled in the org setting)

This question was asked in the community as well
https://community.openai.com/t/where-can-i-see-all-the-threads-ive-created-with-the-api/592963/9

You may also want to update the documentation page to warn users that thread information should be maintained in the external system while you fix the API.

### To Reproduce

Easy to reproduce: look at official documentation page - https://platform.openai.com/docs/api-reference/threads

### OS

macOs

### Node version

node 20

### Library version

3.0.35

**Comment by OperationalFallacy** [comment]
I hope the endpoint is simply not documented yet, nope - API blocks access for API keys

```
{
    "message": "Your request to GET /v1/threads must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "invalid_request_error",
    "param": null,
    "code": "missing_scope"
  }
```

**Comment by rattrayalex** [comment]
The SDK generally does not support endpoints which are not generally available.

**Comment by OGD42** [comment]
So I got the Grammar correction example and it doesn't work, I'm not sure why in the documentation is available as an option but when you try to use the API it doesn't work. What we can do to make it work?
