### ISSUE TITLE
Not able to use OpenAI API key as local environment variable

### ISSUE THREAD

**Issue by Joeri38** [openai/openai-node#859]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'd like to use the API in nodejs to create images. I know it is recommended to have global environments, but I'd like to deploy it for production in Vercel as a nextjs project. Therefor, I use local environment variables. I am however not able to load the API key as a local environment variable.

### To Reproduce

import OpenAI from 'openai';

const openai = new OpenAI({
    apiKey: process.env['NEXT_PUBLIC_OPENAI_API_KEY'], // This is the default and can be omitted
});

### OS

macOS

### Node version

v17.9.1

### Library version

openai v3.3.0

**Comment by rattrayalex** [comment]
I'm not sure why the code snippet you shared isn't working, but the reason is not likely related to this SDK. You might try using `OPENAI_API_KEY` perhaps. 

For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!
