### ISSUE TITLE
Type CreateChatCompletionResponse doesn't seem to be exported correctly

### ISSUE THREAD

**Issue by chanmathew** [openai/openai-node#87]
### Describe the bug

On 3.2.1, can't seem to find the `CreateChatCompletionResponse` type definition, even though I see it in the definitions file:
https://github.com/openai/openai-node/blob/master/dist/api.d.ts#L345

No exported member detected when trying to export it in my TS project:
<img width="1012" alt="CleanShot 2023-03-03 at 22 27 09@2x" src="https://user-images.githubusercontent.com/2940761/222873904-232cda74-0f7f-4731-b530-7b40dc260294.png">

### To Reproduce

1. Try to import type `CreateChatCompletionResponse` from `openai`
2. Cannot find type declaration

### OS

macOS

### Node version

Node v16.17.0

### Library version

openai v3.2.1

**Comment by joseshiru** [comment]
I'm having the same issue.

**Comment by murtio** [comment]
Try updating the library. Inside your project 
` npm update openai`

**Comment by chanmathew** [comment]
> Try updating the library. Inside your project ` npm update openai`

It's already on the latest version. Even tried reinstalling the latest just now, still same issue.

**Comment by rattrayalex** [comment]
Our fully rewritten [upcoming v4](https://github.com/openai/openai-node/discussions/182) redoes our types; you should be able to import types more easily now (though note, all the types are different).
