### ISSUE TITLE
"Unknown parameter: 'attachments[0].tools[0].file_search'."

### ISSUE THREAD

**Issue by bradleyball** [openai/openai-node#886]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

with the new api update there should be a file_search object available on the tools array when passing to attachments

` attachments: [
      {
        file_id: 'fileid',
        tools: [{ type: 'file_search', file_search: { max_num_results: 50 } }],
      },
      {
        file_id: 'fileidl',
        tools: [{ type: 'file_search', file_search: { max_num_results: 50 } }],
      },
    ],`

however I get a 400 error when creating messages "Unknown parameter: 'attachments[0].tools[0].file_search'."

no typescript errors when passing this information

### To Reproduce

see above

### OS

mac

### Node version

v18.5.0

### Library version

"^4.48.2"

**Comment by meorphis** [comment]
Thanks for the report @bradleyball. We'll take a look.

**Comment by meorphis** [comment]
We were able to repro and are working on resolving. We'll keep you posted. Thanks again for reporting.

**Comment by meorphis** [comment]
We've removed this parameter since it was included erroneously. You can instead specify the `max_num_results` when creating the run (https://platform.openai.com/docs/api-reference/runs/createRun - see `file_search.max_num_results` in the `tools` array).
