### ISSUE TITLE
createChatCompletion() takes a long time to process. 

### ISSUE THREAD

**Issue by ikramhasan** [openai/openai-node#89]
### Describe the bug

As described in the title, the method takes a while to load. This is a big problem because, in Vercel, the timeout limit for any call is 5 seconds. And in Netlify, the limit is 10 seconds. But most often the call takes more than 10 seconds to respond. As a result, my website is not working after refactoring the site to use the new gpt-3.5-trubo model. (It works fine with davinci) 

Basically, my website works on localhost but not when I deploy it to any service. Am I missing something? Is there a way to reduce the time?

### To Reproduce

```javascript
 const completion = await openai.createChatCompletion({
       model: "gpt-3.5-turbo",
       messages: [
           {
             role: 'user',
             content: "Write a blog on artificial intelligence",
           }
       ],
      });
```

This takes more than 10 seconds to complete.

### OS

Windows 11

### Node version

v18.12.1

### Library version

3.2.1

**Comment by Developeranees** [comment]
same issue

**Comment by zhongkai** [comment]
The definition of createChatCompletion is modified from
`createImageEdit: async (image: File, mask: File, prompt: string, n?: number ...`
to
createImageEdit: async (image: File, prompt: string, mask?: File, n?: number ...`

the second param is `prompt`,  and the `mask` turns to be optional.

**Comment by eumemic** [comment]
Sometimes `createChatCompletion` hangs indefinitely for me 😕

**Comment by Olovorr** [comment]
> Sometimes `createChatCompletion` hangs indefinitely for me 😕

It never really hanged indefinitely for me, but I had some 240 seconds timeouts 😅

**Comment by imagine** [comment]
It hangs indefinitely for me sometimes, even with a timeout passed into the options.

**Comment by patcat** [comment]
I'm also finding responses from 10736ms to 22304ms using this API, even with shorter questions and prompts. Is this just the nature of how long responses take to generate? Or is there more that can be done to make the response more efficient?

**Comment by kitfit-dave** [comment]
It would be nice to see some of the _many_ similar questions about the performance of the API be answered by openai... For those of us working on projects that will use the API this is a big risk to pass off as "teething problems" that "will surely be fixed in time"
These issues do not seem to be unique to any one person and their implementation, they are widespread. The same delays do not seem to affect the playground.

**Comment by rattrayalex** [comment]
The speed of `gpt-3.5-turbo` has been greatly improved since March. 

You may also consider using a smaller `max_tokens` to limit the amount of time the model spends creating the response.
