### ISSUE TITLE
Batch API - `files.content` not returning a `.jsonl` file format like documentation says

### ISSUE THREAD

**Issue by VioletaCalvo** [openai/openai-node#898]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

The files.content method doesn't return a file content (like the documentation says)[https://platform.openai.com/docs/guides/batch/5-retrieving-the-results], it returns an API response that we should treat as an streaming response to be able to retrieve the data.

### To Reproduce

1. Try to run (the example the documentation shows)[https://platform.openai.com/docs/guides/batch/5-retrieving-the-results]
2. The type of the result is not a `.jsonl` file but an API response.

### OS

macOS

### Node version

Node v20.9.0

### Library version

"openai": "^4.50.0",

**Comment by rattrayalex** [comment]
Sorry for the confusion @VioletaCalvo, we'll try to update those docs soon!
