### ISSUE TITLE
`Unrecognized request argument supplied: maxChatCompletions` | Object literal may only specify known properties, and maxChatCompletions does not exist in type:

### ISSUE THREAD

**Issue by flexchar** [openai/openai-node#899]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Attempting to set `maxChatCompletions` parameter as described [here](https://github.com/openai/openai-node/blob/HEAD/helpers.md#automated-function-calls) throws error in TypeScript and API response.

`'Unrecognized request argument supplied: maxChatCompletions'`

### To Reproduce

Follow the example. Let me know if reproducible is needed. I suspect mismatch in documentation.

### Code snippets

```JavaScript
const runner = openai.beta.chat.completions.runTools({
        maxChatCompletions: 3,
        model: 'gpt-3.5-turbo',
        messages: [...]
});
```

### OS

macOS

### Node version

Node 22

### Library version

4.51.0

**Comment by rattrayalex** [comment]
Sorry for the poor documentation here; this belongs in a second argument:

```ts
const runner = openai.beta.chat.completions.runTools(
  {
    model: 'gpt-3.5-turbo',
    messages: [...],
  }, {
    maxChatCompletions: 3,
  }
);
```
