### ISSUE TITLE
[Whisper] Support URLs for createTranscription call

### ISSUE THREAD

**Issue by wacioc** [openai/openai-node#90]
### Describe the feature or improvement you're requesting

Right now the only way to provide input to createTranscription method is to have the file on disk and create a ReadStream for that. It's a very common use case where the files are stored somewhere (cloud hosting most of the cases) and easiest way is to provide a signed URL (GCP case) to the audio file to be transcribed.
When I'm providing a URL as a parameter for the audio file path I'm getting a "400 - Bad Request" back.

**Comment by rattrayalex** [comment]
Our [upcoming v4](https://github.com/openai/openai-node/discussions/182) makes uploading files much more convenient. For example, you can pass a `fetch` response directly, eg:

```ts
await openai.audio.transcriptions.create({
  file: fetch('https://example.com/my/file.mp3'),
  model: 'whisper-1',
})
```
Note that if the URL of the file you are passing does not end in a file extension like `.mp3`, you will need to specify that:
```ts
import {toFile} from 'openai';

await openai.audio.transcriptions.create({
  file: toFile(fetch('https://example.com/my/file'), 'file.mp3'),
  model: 'whisper-1',
})
```
