### ISSUE TITLE
TypeError: getDefaultAgent is not a function 

### ISSUE THREAD

**Issue by guidev** [openai/openai-node#903]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using openai-node with langchain and datadog, ESM, I get the following error: 

```
TypeError: getDefaultAgent is not a function
    at OpenAI.buildRequest (file:///Users/name/Progetti/nonworking/node_modules/openai/core.mjs:208:66)
    at OpenAI.makeRequest (file:///Users/name/Progetti/nonworking/node_modules/openai/core.mjs:279:44)
    at async file:///Users/name/Progetti/nonworking/node_modules/@langchain/openai/dist/chat_models.js:796:29
    at async RetryOperation._fn (/Users/name/Progetti/nonworking/node_modules/p-retry/index.js:50:12)

Node.js v22.3.0


```

### To Reproduce

```
1. git clone https://github.com/guidev/nonworking/tree/node20

2. npm run start 
```

### OS

macOS

### Node version

node 20, node 22

### Library version

4.52.0

**Comment by dgellow** [comment]
Hi @guidev,

Thanks for the bug report, and I appreciate the repo example to reproduce the issue. Looking into it.

**Comment by ericallam** [comment]
@dgellow this is an issue with `import-in-the-middle`, it somehow breaks the shims system. I've recreated the issue as a failing test in the import-in-the-middle repo here: https://github.com/DataDog/import-in-the-middle/pull/113

**Comment by rattrayalex** [comment]
Thanks for reporting. 

Closing this issue as it seems like an `import-in-the-middle` bug. Hopefully it gets fixed there. 

It's possible we'll be able to substantially reduce or eliminate our `shims` systems once we drop `node-fetch` as a dependency, which could solve this, but we won't target it specifically.

Members of the community are welcome to share workaround here, but I encourage you to otherwise bring this up with `import-in-the-middle` or datadog.

**Comment by rattrayalex** [comment]
One possible workaround you could try would be to explicitly `import 'openai/shims/node'` or `import 'openai/shims/web'` before your first `import … from 'openai'`

**Comment by ericallam** [comment]
@rattrayalex this isn't solved by importing the shim manually, that just results in a different error. The way to fix this is with the latest version of `import-in-the-middle` and writing your own loader:

```js
// loader.mjs
import { register } from "node:module";

register("import-in-the-middle/hook.mjs", import.meta.url, {
  parentURL: import.meta.url,
  data: { include: ["openai"]},
});
```

Then running in node with `node --import ./loader.mjs ...`

**Comment by adam-on-tailwind** [comment]
FYI the loader.mjs workaround prevented the error in my project, but also stopped traces from being sent. The way I was able to fix this was by importing the openai web shims using the `--import` flag, enabling experimental fetch `--experimental-fetch` and supplying an http `Agent` to the openai client at initialization.

Start node like this:

```
node --import openai/shims/web --import dd-trace/register.js --require dd-trace/init --experimental-fetch src/main/index.js
```

When initializing the openai client:

```javascript
import 'http'
import OpenAI from 'openai'

const openai = new OpenAI({
  httpAgent: new http.Agent()
})
```

And it all works! Same steps apply if you're using Anthropic btw.

**Comment by nakatsuka-k** [comment]
@tokisherbakov 
I was able to resolve the issue by modifying it to make the request using Fetch as shown below.

```typescript
      const openAiApiUrl = "https://api.openai.com/v1/chat/completions";
      
      const response = await fetch(openAiApiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${appConfig.openAiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-3.5-turbo",
          messages: [...messages],
          max_tokens: 256,
        }),
      });
```
