### ISSUE TITLE
Property 'text' does not exist on type 'MessageContent'

### ISSUE THREAD

**Issue by sebanimm** [openai/openai-node#919]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Since the `MessageContent` type includes the `TextContentBlock` type, so there must be a `text` property, but it doesn't work

### To Reproduce

```ts
const messages = await openai.beta.threads.messages.list(threadId, {
  order: "asc",
});

messages.data.at(-1)?.content[0].text.value;
//                                 ^
// Property 'text' does not exist on type 'MessageContent'.
//  Property 'text' does not exist on type 'ImageFileContentBlock'.ts(2339)
```

### Code snippets

```JavaScript
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
});
const assistantId = process.env.NEXT_PUBLIC_ASSISTANT_ID;
const threadId = process.env.NEXT_PUBLIC_THREAD_ID;

export async function receiveMessage() {
  const messages = await openai.beta.threads.messages.list(threadId, {
    order: "asc",
  });
  return messages.data.at(-1)?.content[0].text.value;
}
```

### OS

Windows 11

### Node version

v20.9.0

### Library version

4.52.3

**Comment by RobertCraigie** [comment]
TypeScript is complaining because you need to check that the content is actually a text block
```ts
const block = messages.data.at(-1)?.content[0];
if (block && block.type === 'text') {
  block.text.value;
}
```
your code will still work at runtime if the message only has text content blocks

**Comment by sebanimm** [comment]
> TypeScript is complaining because you need to check that the content is actually a text block
> 
> ```ts
> const block = messages.data.at(-1)?.content[0];
> if (block && block.type === 'text') {
>   block.text.value;
> }
> ```
> 
> your code will still work at runtime if the message only has text content blocks

Thank you for your answer!
