### ISSUE TITLE
extra_body parameter support

### ISSUE THREAD

**Issue by YunhaoLiu1228** [openai/openai-node#924]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I can't find the extra_body parameter in openai typescript SDK. Is it possible to support this parameter in typescript?

**Comment by RobertCraigie** [comment]
Hi @YunhaoLiu1228, we have no plans to add an `extra_body` argument, you can send undocumented params like so: https://github.com/openai/openai-node#undocumented-request-params
