### ISSUE TITLE
OpenAIError: Final run has not been received

### ISSUE THREAD

**Issue by neilord** [openai/openai-node#945]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hi! Our team is trying to deal with a lot of `OpenAIError: Final run has not been received` errors. Is it an OpenAI API issue, our end bug or is there something you could do on your end to fix it? Thanks!

### To Reproduce

1. Call Assistants Tools Stream API

### OS

macOS

### Node version

v20.11.1

### Library version

openai v4.46.1

**Comment by RobertCraigie** [comment]
@neilord this is likely an API issue, we don't raise a `Final run has not been received` error in the SDK anywhere.

**Comment by MarkMurphy** [comment]
> [@neilord](https://github.com/neilord) this is likely an API issue, we don't raise a `Final run has not been received` error in the SDK anywhere.

I'm not sure that's actually the case, at least in the latest code:

https://github.com/openai/openai-node/blob/2bce86509a45d96d17cfc837ddfd8ddc5995df8e/src/lib/AssistantStream.ts#L414

and 

https://github.com/openai/openai-node/blob/2bce86509a45d96d17cfc837ddfd8ddc5995df8e/src/lib/AssistantStream.ts#L298
