### ISSUE TITLE
Arguments of createImageEdit() are in the wrong order compared to documentation

### ISSUE THREAD

**Issue by php4fan** [openai/openai-node#95]
### Describe the bug

https://platform.openai.com/docs/api-reference/images/create-edit

![image](https://user-images.githubusercontent.com/13969584/223567027-3e859851-9126-4390-a4f5-0a4ed6bfed9d.png)

According to the documentation, the arguments of `OpenAIApi.createImageEdit` are supposed to be in this order:
```
image,
mask,
prompt,
...
```

but the reality is that the method expects them (and only works if they are) in this order instead:
```
image
prompt
mask
```

Either the documentation is incorrect, or it is a bug in the library. You decide, actually. The documented order makes way more sense, so I'd suggest you treat it as a bug in the library, although then you'll break backward compatibility.

Or, it would be actually pretty easy to heuristically detect what argument is what and to support both orders. Theoretically it's possible to have a prompt like "path/to/image.png" and an image file whose filename is "A painting of a rabbit doing drugs", but I think it's more useful to support the use case of inverted arguments for BC than the one of crazy filenames and filename-like prompts.

### To Reproduce

Run the code snippet.

### Code snippets

```JavaScript
const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);
const response = await openai.createImageEdit(
  fs.createReadStream("otter.png"),
  fs.createReadStream("mask.png"),
  "A cute baby sea otter wearing a beret",
  2,
  "1024x1024"
);
```

### OS

linux

### Node version

irrelevant

### Library version

3.2.1

**Comment by st3phhays** [comment]
I just spent way too much time trying to figure out why I kept getting an error message of "You must provide a prompt.". 

I can confirm using this order works IF you also supply a mask, but it states in the docs that a mask is not required. I have not been able to get it to work without supplying one. If a mask is not supplied, then I get the error of "Wrong type, expected 'integer' for requestBody parameter 'n'".

**Comment by MuLoo** [comment]
think you !!! you save my day!

**Comment by ShortBeard** [comment]
Thank you for this. I thought I was going insane 😆

**Comment by gezzergarcia** [comment]
I had the same issue, 
thank you @php4fan !!!

**Comment by kitfit-dave** [comment]
Looks like the typescript definition is "correct" (`createImageEdit(image: File, prompt: string, mask?: File | undefined[...]`) and the same as the implementation? I.e. it's a documentation error.
Also, you cannot have a required parameter following an optional one, so that is another strike against the documentation being correct (and changing the implementation to match)

**Comment by Astraport** [comment]
I get the error "You must provide a prompt." all the time, no order dependency. Very annoying.

**Comment by rattrayalex** [comment]
Thank you for reporting this! Agreed that the error in the docs would be preferred, and that the docs are unfortunately incorrect. Changing the argument order would be a backwards-breaking change.

A fix to the docs has been proposed here: https://github.com/openai/openai-openapi/pull/59

Note that our new [v4](https://github.com/openai/openai-node/discussions/182) of this library uses an object to specify these parameters, which you can use like so:

```ts
await openai.images.edit({
  image: fs.createReadStream("otter.png"),
  mask: fs.createReadStream("mask.png"),
  prompt: "A cute baby sea otter wearing a beret",
  n: 2,
  size: "1024x1024",
})
```

I hope this reduces any similar confusion, here and in the future!
