### ISSUE TITLE
Stop using polyfills for Node.js

### ISSUE THREAD

**Issue by mcollina** [openai/openai-node#951]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

My understanding is that this module use [polyfills](https://github.com/openai/openai-node/blob/22896e88e97c0e8621bf74c666a6fc7d9d832267/src/_shims/node-runtime.ts) for Node.js.
There is no need for doing so given you support Node.js v18+.

This causes compatibility issues with the rest of the ecosystem.

Ref https://github.com/fastify/fastify/issues/5584

**Comment by RobertCraigie** [comment]
Hi @mcollina, see #392 for some context. We were originally thinking about depending on `undici` but it looks like we'll be able to depend entirely on builtins!

Unfortunately that change won't land particularly quickly, is there anything we could to do in the meantime to be compatible with fastify?

**Comment by mcollina** [comment]
The problem is not actually in fastify. We [call]( `https://github.com/fastify/fastify/blob/9226a4793311c003e30dfddec4fd580deffcd28c/lib/reply.js#L710`) [`Readable.fromWeb()`](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options). 

I think providing a default utility to get a Node.js stream instead would remove the problem.

**Comment by Ethan-Arrowood** [comment]
👋 Hi Matteo!

Hopefully removing the polyfill will fix that user's issue. As @RobertCraigie mentioned, more work is happening behind the scenes to align the SDK with more Node.js built-ins and align on web standard APIs so the SDK is interoperable between any JS Runtime environment. 

Keep an eye out for future updates 🚀

**Comment by RobertCraigie** [comment]
@mcollina this will be fixed in the next release :)

https://github.com/openai/openai-node/pull/949

**Comment by RobertCraigie** [comment]
This was fixed in `v4.53.1`
