### ISSUE TITLE
Support for longer video/audio files in Whisper model

### ISSUE THREAD

**Issue by ioanmo226** [openai/openai-node#96]
### Describe the feature or improvement you're requesting

Currently, the Whisper model only supports video files that are up to 30 seconds long and audio files that are up to 25 MB in size. 

This limitation can be a challenge for users who want to process longer video/audio files.

To overcome this limitation, I propose implementing a feature that allows the user to split their video/audio files into smaller segments and send multiple requests to the Whisper API to process each segment.

This will enable users to process longer video/audio files while still taking advantage of the Whisper model's powerful capabilities. 

I would like to request the OpenAI team to consider implementing this feature or suggest any alternative solutions to handle longer videos/audio files using the Whisper model.

**Comment by RichCaloggero** [comment]
My experience with this API is that it only accepts mp3 files that are aprox. 8 mb in length; anything longer than this and the API generates a content length error.

Why? All the docs say that file length can be up to 25 mb!

I'm simply using:

```
createTranscription(fs.readStream("audio.mp3"), "whisper-1");
```

This works beautifully for files 8 mb and shorter!

What am I doing wrong?

**Comment by rattrayalex** [comment]
Closing this as it's an API feature request rather than a client library feature request. If you're still interested in this functionality, please post it in [community.openai.com](https://community.openai.com)
