### ISSUE TITLE
nodes 

### ISSUE THREAD

**Issue by BensenHsu** [openai/openai-node#97]

**Comment by BensenHsu** [comment]
> ### Describe the bug
> In network, other people can see my API Key!
> 
> <img alt="image" width="1253" src="https://user-images.githubusercontent.com/51500098/223651624-1f5eee29-9443-4590-ac12-6efbce25a371.png">
> 
> ### To Reproduce
> 1. Use this node.js library to send a request
> 2. Open network, in the authorization section, the API key is exposed.
> 
> ### Code snippets
> _No response_
> 
> ### OS
> macOS
> 
> ### Node version
> Node v16.14.2
> 
> ### Library version
> penai v3.0.1

@schnerd @jeevnayak @athyuttamre @buster95 @ceifa 
It's URGENT!!!

**Comment by ruskakimov** [comment]
You are not supposed to send requests to OpenAI API from a client machine.

https://platform.openai.com/account/api-keys
> Do not share your API key with others, or expose it in the browser or other client-side code.

Create an endpoint on your BE server (or use something like Firebase Cloud functions) that will send requests to OpenAI and return the result to your FE.

**Comment by ruskakimov** [comment]
I suggest you revoke your leaked key immediately.

**Comment by ruskakimov** [comment]
@BensenHsu Yup, it's a library for your Backend.

If you describe what you are trying to achieve, I can try pointing you in the right direction.

**Comment by schnerd** [comment]
@BensenHsu Network headers are not visible over the network as it should be an SSL (https) connection.

Passing API keys and secure tokens through the Authorization header is common practice in APIs.

Do you have any evidence or exact steps to replicate a scenario where an attacker on a separate machine can see this header value?

**Comment by BensenHsu** [comment]
> @BensenHsu Network headers are not visible to others over the network as it should be an SSL (https) connection.
> 
> Passing API keys and secure tokens through the Authorization header is common practice in APIs.
> 
> Do you have any evidence or exact steps to replicate a scenario where an attacker on a separate machine can see this header value?

@schnerd Because this is the screenshot sent by my user

**Comment by UXDart** [comment]
that screenshot on OP seems to be on a browser, are you using the nodejs lib in the browser? you need to do the call from a server if you will use you own api_key / if each user uses their api_key then anyway that user will see their user key. HTH

**Comment by schnerd** [comment]
@BensenHsu If this screenshot is from your user, it means your application is not set up correctly – you must have written your code in a way that it is making the request in the browser.

This library is meant for usage in node.js but I think it technically works if you accidentally use it from the browser too, which I'm guessing is what you're doing here.

Are you using a full-stack framework like next.js or something. In order to help you further, we'd need code examples that demonstrate how you are calling this library from your app.

**Comment by BensenHsu** [comment]
> @BensenHsu If this screenshot is from your user, it means your application is not set up correctly – you must have written your code in a way that it is making the request in the browser.
> 
> This library is meant for usage in node.js but I think it technically works if you accidentally use it from the browser too, which I'm guessing is what you're doing here.
> 
> Are you using a full-stack framework like next.js or something? In order to help you further, we'd need code examples that demonstrate how you are calling this library from your app.

@schnerd I'm using React, and import openai into my .JSX

**Comment by UXDart** [comment]
forget about the network tab / the key is in your JS file. you need to use a server to make the call

**Comment by BensenHsu** [comment]
> forget about the network tab / the key is in your JS file. you need to use a server to make the call

yea, I used to use a server to send the request to GPT-3, but now I want to try something differently, since you got this node.js.

**Comment by UXDart** [comment]
ok, but reset the key... / and go back to use server for the call / the word urg---ent in the title of this thread won't help you... but the opposite
