### ISSUE TITLE
`batches.list()` doesn't iterate properly with Azure OpenAI

### ISSUE THREAD

**Issue by Manouchehri** [openai/openai-node#977]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using `client.batches.list()` on an Azure OpenAI client, I'm unable to iterate through it like the documentation from OpenAI says I should be able to. https://platform.openai.com/docs/guides/batch/getting-started?lang=node

`client.batches.list()` currently returns a object that looks like this:

```
BatchesPage {
  options: {
    method: 'get',
    path: '/batches',
    query: {},
    headers: {
      Authorization: 'Bearer REMOVED'
    }
  },
  response: Response {
    cf: undefined,
    webSocket: null,
    url: 'https://REMOVED.openai.azure.com//openai/batches?api-version=2024-07-01-preview',
    redirected: false,
    ok: true,
    headers: Headers(13) {
      'apim-request-id' => '68da25df-8dc4-4b8c-82b7-cd859d6b5ece',
      'content-length' => '17552',
      'content-type' => 'application/json; charset=utf-8',
      'date' => 'Thu, 08 Aug 2024 23:15:22 GMT',
      'request-context' => 'appId=cid-v1:2d2e8e63-272e-4b3c-8598-4ee570a0e70d',
      'strict-transport-security' => 'max-age=31536000; includeSubDomains; preload',
      'vary' => 'Accept-Encoding',
      'x-aml-cluster' => 'vienna-eastus-02',
      'x-content-type-options' => 'nosniff',
      'x-ms-client-request-id' => 'Not-Set',
      'x-ms-region' => 'East US',
      'x-ms-response-type' => 'standard',
      'x-request-time' => '0.973',
      [immutable]: true
    },
    statusText: 'OK',
    status: 200,
    bodyUsed: true,
    body: ReadableStream { locked: true, [state]: 'closed', [supportsBYOB]: true, [length]: 0n }
  },
  body: {
    value: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ],
    first_id: 'batch_5d50b84a-f6e9-4ecc-a3c4-0a1a23a532f3',
    has_more: true,
    last_id: 'batch_c3dfc7a1-63b0-4437-a0e9-dd952e38e51f'
  },
  data: []
}
```

### To Reproduce

If you use the following code, you'll be able to reproduce the bug.

```typescript
const client = new AzureOpenAI({
  azureADTokenProvider,
  deployment: env.AZURE_OPENAI_DEPLOYMENT,
  endpoint: env.AZURE_OPENAI_ENDPOINT,
  apiVersion: "2024-07-01-preview"
});

const list = await client.batches.list();

for await (const batch of list) { // results in nothing being printed out
  console.log(batch);
}
```

### OS

macOS

### Node version

Cloudflare Worker v3.69.1

### Library version

openai v4.55.2

**Comment by RobertCraigie** [comment]
cc @kristapratico it looks like the Azure API is returning the data under a `value` property instead of `data` like the OpenAI API does. I think we'll just have to special case this in the SDKs?

**Comment by kristapratico** [comment]
Thanks for tagging me. I've reported this to the service team. I do suspect that Azure will align with what's defined in the [spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/authoring/preview/2024-07-01-preview/azureopenai.yaml#L962) and update this to use `data` so likely no need for a special case. I'll update when I know more.

**Comment by kristapratico** [comment]
This has been mitigated in the Azure service - the fix is deployed for `batches.list()` to return `data`. @Manouchehri thanks for your help in identifying the issue!

**Comment by kristapratico** [comment]
@Manouchehri it appears there were some complications with the initial hotfix and so it was reverted. The fix is being rolled out again, I expect it to use `data` shortly.
