### ISSUE TITLE
Structured outputs: base zod schema using `discriminatedUnion` does not generate a valid JSON schema

### ISSUE THREAD

**Issue by vicent4no** [openai/openai-node#995]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Using the StructuredOutputs documentation  and trying to generate a response using a Zod schema based on a plain discriminatedUnion produces an invalid output schema

```
{
  type: 'json_schema',
  json_schema: {
    name: 'final_schema',
    strict: true,
    schema: {
      anyOf: [Array],
      '$schema': 'http://json-schema.org/draft-07/schema#'
    }
  }
}
```

The issue specifically has to do with not having a `type` property inside of `schema` property

Is this solvable? 

Or should we **always** nest a discriminated union within a 'object' type property? In that case, it would be good to discriminate it in the documentation

Thanks a lot!

### To Reproduce

1. install openai 4.55.7 package
2. install zod ^3.23.8
3. Follow the code snippets

### Code snippets

```JavaScript
import { z } from 'zod';
import { zodResponseFormat } from 'openai/helpers/zod';

const BaseResponseSchema = z.object({
  status: z
    .literal('success'),
  file_source_ids: z
    .string()
    .array(),
   result: z.string()
});

const UnsuccessfulResponseSchema = z.object({
  status: z
    .enum([
      'missing_information',
      'could_not_answer',
    ]),
  explanation: z.string(),
});

const finalSchema = z.discriminatedUnion('status', [
          BaseResponseSchema,
          UnsuccessfulResponseSchema,
        ]);

const json = zodResponseFormat(finalSchema, 'final_schema');

console.log(json);
```

### OS

Debian

### Node version

22.6

### Library version

openai v4.55.7

**Comment by RobertCraigie** [comment]
> Or should we always nest a discriminated union within a 'object' type property? In that case, it would be good to discriminate it in the documentation

Yes unfortunately you currently have to nest the discriminated union inside an object.

Which documentation do you think would be most helpful?

**Comment by vicent4no** [comment]
Hey! Thanks for such a quick reply.

Understood.

Probably here, in the following list 
https://platform.openai.com/docs/guides/structured-outputs/supported-types
![image](https://github.com/user-attachments/assets/89861cef-464a-4ee9-8aaa-0b00085f87f8)
Maybe it could be specified that `anyOf` can not be used as a top level type.

This issue is a little bit obfuscated because since it is encouraged to use `Zod` it is not easily visible (unless you check out the source code for `zodResponseFormat` or log the output json) that a `discriminatedUnion` produces a `anyOf` that can not be used as a top level object.

A piece of documentation could also be added here 
https://platform.openai.com/docs/guides/structured-outputs/introduction
 at the beginning specifying this caveat

**Comment by vicent4no** [comment]
Thank you for [this update](https://platform.openai.com/docs/guides/structured-outputs/root-objects-must-not-be-anyof)

I think the ticket can be closed since this was effectively addressed
